### ISSUE TITLE
Not redirecting to login page when clicking on the browser's back button

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#7538] opened 2022-02-24 12:07 UTC
**Describe the bug**
My session ended and I was redirected to login page, then I clicked on the back button of the browser and got redirected to Message tab. I noticed these exceptions when trying to process the cookies:
Webapp:
<img width="700" alt="Screen Shot 2022-02-24 at 6 31 46 pm" src="https://user-images.githubusercontent.com/66472237/155519143-724572b9-572e-44f3-97ca-70b289538655.png">

Admin same thing:
<img width="700" alt="Screen Shot 2022-02-24 at 7 05 24 pm" src="https://user-images.githubusercontent.com/66472237/155520657-f9d3a35e-e560-44aa-887e-768711c04bc6.png">

**To Reproduce**
Steps to reproduce the behavior in admin app or webapp:
1. Login (I was using admin user)
2. Navigate across tabs.
3. Wait until session ends (or just delete the cookie)
4. You'll get the "session has experied" modal, click on "login" button.
5. You'll be redirected to login page.
6. Click on the browser's back button.
7. You'll be redirected to your last visited page (for example message tab) 
8. Notice: You won't get the "session has expired" modal.
9. Open browser's console and see exceptions. 

**Expected behavior**
When on login page and the session is expired, it should redirect to login page again when clicking back button.

**Environment**
- Instance: local 
- Browser: Chrome
- Client platform: MacOS
- App: webapp  and admin
- Version: 3.14.1

**Additional context**
I found this when testing: https://github.com/medic/cht-core/issues/7537

**Comment by dianabarsan** [comment] 2022-02-24 12:49
I tried replicating this on older versions and could as back as 3.12, but not on 3.11 or 3.10. 

It looks like the problem is that we're trying to parse a cookie that doesn't exist when [trying to determine the login redirect url](https://github.com/medic/cht-core/blob/master/webapp/src/ts/services/session.service.ts#L28). 
On admin side, it's the same cause, except manifesting in a different way, where we're trying to access a property of the undefined `userCtx` object.

**Comment by dianabarsan** [comment] 2022-02-24 12:50
I've added this to 3.14.1

**Comment by m5r** [comment] 2022-03-24 15:00
Important note: it turns out that uBlock Origin prevents the bug from occurring. Make sure to disable it when reviewing and testing.

**Comment by m5r** [comment] 2022-03-31 15:46
Update: I could reproduce this with 3.11 and 3.10. This bug (or feature) has to do with the browser's bfcache, see [related documentation](https://web.dev/bfcache/)  
Essentially, this is normal browser behavior where it restores the page and its state from memory without even hitting the network.

This was confirmed with the following snippet
```js
window.addEventListener('pageshow', (event) => {
  if (event.persisted) {
    console.log('This page was restored from the bfcache.');
  } else {
    console.log('This page was loaded normally.');
  }
});
```

There are some workarounds to this.
1. Disabling bfcache
```js
window.addEventListener('unload', function(){});
```

2. Check for the cookie validity when the user uses the back button after being logged out
```js
window.addEventListener('pageshow', (event) => {
  if (event.persisted && !document.cookie.match(COOKIE_NAME)) {
    location.href = '/login';
  }
});
```

I went with the second option which follows Google's recommendation of checking for any stale data with a `pageshow` event listener.

Aside from that, we also need to catch the error thrown when parsing the nonexistent cookie so that the inactivity timeout redirects properly to the login page after 1 minute.

**Comment by dianabarsan** [comment] 2022-04-18 15:04
This is ready for AT on `7538-redirect-to-login-back-button`.

**Comment by tatilepizs** [comment] 2022-04-19 15:47
**Config:** Default
**User:** admin
**Environment:** Local with docker helper script
**Platform:** WebApp 
**Browser:** Chrome

**Reproducible on** `Master`
After the session was ended, and the the back button of the browser was pressed, it was redirected to the last visited page.

[video](https://user-images.githubusercontent.com/94494491/164041779-4a195c1a-7c44-4e88-aeba-4b3e4bca7a37.mp4)

**Fixed on** `7538-redirect-to-login-back-button`
After the session was ended, and the the back button of the browser was pressed, it was redirected to the login page

[video](https://user-images.githubusercontent.com/94494491/164043488-d0b88b85-0b30-46ea-adbb-16bb81a3d4e0.mp4)

**Closed** 2022-04-19 19:16 UTC
Labels: Type: Bug, Priority: 1 - High

**Comment by latin-panda** [comment] 2022-04-19 19:18
Great job @tatilepizs and @m5r to get this issue solved 🎉 Thank you
As agreed in the Product call today, I've merge the PR on benefit of 3.15.0 release 🙂
cc: @mrjones-plip
