### ISSUE TITLE
Ability to customize icons shown on main tabs (contact, tasks, etc)

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6410] opened 2020-05-06 17:44 UTC
**What feature do you want to improve?**
The icon displayed on each of the main tabs (Messaging, Contacts, Tasks, Analytics, etc.) is not currently configurable.  In cases where users have <400px screen width, the text is hidden and only the icon appears so for some users, this icon may be the only descriptor they get about the purpose of that tab. It is therefore important that the tab be contextually relevant for the project and workflow. It is somewhat common to change the text that displays on each of these tabs and in those cases: it is important that the text and the icon align.

**Describe the improvement you'd like**
Add a new mechanism through which the tab icons can be configured.

**Additional context**
For the Covid-Moh-Ke project, MoH users have requested to change the text to "home" and the icon to something like a house.

Our default icon for tasks is not immediately self-evident and annecdotally may be a popular icon to change based on the project context.

**Comment by MaxDiz** [comment] 2020-05-06 19:47
After conversation with @abbyad , reluctantly adding this issue to 3.8.2 to meet immediate partner expectations.

**Comment by abbyad** [comment] 2020-05-06 19:54
I am not certain yet that it needs to be added to 3.8.2 yet, but is being prioritized to figure out how to best deal with a deployment where this has become a blocker.

**Comment by garethbowen** [comment] 2020-05-07 19:55
Dropping from 3.8.2 as that release has been stopped for now. Please reach out to product-management on Slack or comment here to discuss prioritising this.

**Comment by MaxDiz** [comment] 2020-05-14 21:39
removing 'covid' label since this no longer seems to be a blocker for the deployment

**Comment by abbyad** [comment] 2020-05-15 14:19
I believe this is still required for the deployment to switch back to a release. @SMurithi, @derickl, can one of you please confirm, and work to get this scheduled with @n-orlowski?

**Comment by MaxDiz** [comment] 2020-05-20 21:33
Confirmed that this issue is still a high priority for the MoH Ke deployment. Adding to the next roadmap planning discussion

**Comment by MaxDiz** [comment] 2020-06-01 14:07
Adding to the v3.10 release based on partner requirement. Per discussion with @garethbowen we can build a custom 3.9.0+icon branch post release (if needed) or wait for 3.10.0.

**Comment by SMurithi** [comment] 2020-06-12 14:12
I second the approach proposed by @n-orlowski. For partners such as MoH this flexibility is important.

**Comment by dianabarsan** [comment] 2020-06-12 14:22
@SMurithi can you please share the approach proposed by Nicole?

**Comment by SMurithi** [comment] 2020-06-12 14:35
@dianabarsan this is what I mean -  ability to upload any icon that conforms to the specs required (size, file type, pixelation/resolution etc).

**Comment by dianabarsan** [comment] 2020-06-17 05:19
Because of how our menu works and the multiple states that a header icon has (inactive, hovered, and active), there's a downside in allowing "any icon that conforms to the specs" to be a header icon. 

We allow `.png` and `.svg` images as icons. 

There are ways that we can apply an overlay over a png image to change its color, but these are not widely supported by browsers. If we allow png icons, they will be a static color without any hover/active effects. 

My initial thought was to filter out resource icons to the ones that are in svg format, but we can allow any icon with the above caveat. 

NB. There are websites that offer free png to svg image conversions and are fairly reliable. For example: https://onlineconvertfree.com/convert-format/png-to-svg/ .

**Comment by MaxDiz** [comment] 2020-06-17 19:57
@dianabarsan makes sense. If you can provide documentation on any limitations / guidance for best display, I think we're good to go. Thanks for looking into it!

**Comment by dianabarsan** [comment] 2020-06-26 03:46
Ready for AT on `6410-configurable-menu-icons`. 
Documentation PR https://github.com/medic/cht-docs/pull/161

**Comment by ngaruko** [comment] 2020-07-02 01:18
The Admin console Resource icon dropdowns only displays four options instead of the whole list in the `Icons` section; that this mean only these 4 are `svg` as in the dos @dianabarsan ? 
![image](https://user-images.githubusercontent.com/6979995/86305567-126c6080-bc66-11ea-8d8d-3dedab552e5b.png)

**Comment by dianabarsan** [comment] 2020-07-02 04:23
@ngaruko that's correct. you can also check which ones are svg's by looking at the `resources` document in the DB and checking its attachments to verify.

**Comment by dianabarsan** [comment] 2020-07-03 08:25
Merged into `master`.

**Closed by dianabarsan** 2020-07-03 08:25 UTC
Labels: Type: Improvement, UI/UX

**Comment by ngaruko** [comment] 2020-09-07 22:17
Notes for AT:
In `App Management`, click `Images` > `Header Tabs Icons`
![image](https://user-images.githubusercontent.com/6979995/92418505-e1eff800-f1bb-11ea-81e8-e456ad4e759d.png)

Either add a `font awesome icon` or select a saved `svg` resource icon. These can be added to the `resources` folder or uploaded manually on the `Icons` tab on the same `Images` page .
![image](https://user-images.githubusercontent.com/6979995/92418578-617dc700-f1bc-11ea-98ed-86c10153d77b.png)
