### ISSUE TITLE
Ci is failing for contributors 

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-core#9236] opened 2024-07-03 06:08 UTC
**Describe the bug**
Contributors have the jobs below failing with this error: ` Error: the string "Error response from daemon: manifest for medicmobile/cht-haproxy:4.10.0-8039-contactsummary-log.9772146005 not found: manifest unknown: manifest unknown\n" was thrown, throw an Error :)`

1.. ci-integration-all-k3d
<details><summary> Logs </summary>

```
> medic@4.10.0 ci-integration-all-k3d
> mocha --config tests/integration/.mocharc-k3d.js



Starting services......
INFO[0000] No clusters found                            

WARN[0000] No node filter specified                     

INFO[0000] portmapping '443:443' targets the loadbalancer: defaulting to [servers:*:proxy agents:*:proxy] 

INFO[0000] Prep: Network                                

INFO[0000] Created network 'k3d-cht-e2e'                

INFO[0000] Created image volume k3d-cht-e2e-images      

INFO[0000] Starting new tools node...                   

INFO[0000] Starting node 'k3d-cht-e2e-tools'            

INFO[0001] Creating node 'k3d-cht-e2e-server-0'         

INFO[0001] Pulling image 'docker.io/rancher/k3s:v1.28.8-k3s1' 

INFO[0004] Creating LoadBalancer 'k3d-cht-e2e-serverlb' 

INFO[0004] Using the k3d-tools node to gather environment information 

INFO[0004] HostIP: using network gateway 172.19.0.1 address 
INFO[0004] Starting cluster 'cht-e2e'                   
INFO[0004] Starting servers...                          

INFO[0004] Starting node 'k3d-cht-e2e-server-0'         

INFO[0008] All agents already running.                  
INFO[0008] Starting helpers...                          

INFO[0008] Starting node 'k3d-cht-e2e-serverlb'         

INFO[0015] Injecting records for hostAliases (incl. host.k3d.internal) and for 2 network members into CoreDNS configmap... 

INFO[0017] Cluster 'cht-e2e' created successfully!      

INFO[0017] You can now use it like this:                
kubectl config use-context k3d-cht-e2e
kubectl cluster-info

Error response from daemon: manifest for medicmobile/cht-haproxy:4.10.0-8039-contactsummary-log.977[21](https://github.com/medic/cht-core/actions/runs/9772146005/job/26977203552?pr=8454#step:14:22)46005 not found: manifest unknown: manifest unknown

  1) "before all" hook: beforeAll in "{root}"
INFO[0000] Deleting cluster 'cht-e2e'                   

INFO[0000] Deleting cluster network 'k3d-cht-e2e'       

INFO[0001] Deleting 1 attached volumes...               

INFO[0001] Removing cluster details from default kubeconfig... 

INFO[0001] Removing standalone kubeconfig file (if there is one)... 

INFO[0001] Successfully deleted cluster cht-e2e!        

Test done. Signing off ...

  0 passing (19s)
  1 failing

  1) "before all" hook: beforeAll in "{root}":
     Error: the string "Error response from daemon: manifest for medicmobile/cht-haproxy:4.10.0-8039-contactsummary-log.9772146005 not found: manifest unknown: manifest unknown\n" was thrown, throw an Error :)
      at thrown2Error (/home/runner/work/cht-core/cht-core/node_modules/mocha/lib/runner.js:1[24](https://github.com/medic/cht-core/actions/runs/9772146005/job/26977203552?pr=8454#step:14:25)1:10)
      at Runner.fail (/home/runner/work/cht-core/cht-core/node_modules/mocha/lib/runner.js:443:11)
      at cbHookRun (/home/runner/work/cht-core/cht-core/node_modules/mocha/lib/runner.js:532:14)
      at done (/home/runner/work/cht-core/cht-core/node_modules/mocha/lib/runnable.js:[31](https://github.com/medic/cht-core/actions/runs/9772146005/job/26977203552?pr=8454#step:14:32)0:5)
      at /home/runner/work/cht-core/cht-core/node_modules/mocha/lib/runnable.js:377:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)



Error: Process completed with exit code 1.

```
</details>

2.. ci-integration-sentinel-k3d
<details><summary> Logs </summary>

```
> medic@4.10.0 ci-integration-sentinel-k3d
> mocha --config tests/integration/.mocharc-sentinel-k3d.js



Starting services......
INFO[0000] No clusters found                            

WARN[0000] No node filter specified                     

INFO[0000] portmapping '443:443' targets the loadbalancer: defaulting to [servers:*:proxy agents:*:proxy] 

INFO[0000] Prep: Network                                

INFO[0000] Created network 'k3d-cht-e2e'                

INFO[0000] Created image volume k3d-cht-e2e-images      

INFO[0000] Starting new tools node...                   

INFO[0001] Creating node 'k3d-cht-e2e-server-0'         

INFO[0001] Starting node 'k3d-cht-e2e-tools'            

INFO[0001] Pulling image 'docker.io/rancher/k3s:v1.28.8-k3s1' 

INFO[0004] Creating LoadBalancer 'k3d-cht-e2e-serverlb' 

INFO[0004] Using the k3d-tools node to gather environment information 

INFO[0004] HostIP: using network gateway 172.19.0.1 address 
INFO[0004] Starting cluster 'cht-e2e'                   
INFO[0004] Starting servers...                          

INFO[0004] Starting node 'k3d-cht-e2e-server-0'         

INFO[0008] All agents already running.                  
INFO[0008] Starting helpers...                          

INFO[0008] Starting node 'k3d-cht-e2e-serverlb'         

INFO[0014] Injecting records for hostAliases (incl. host.k3d.internal) and for 2 network members into CoreDNS configmap... 

INFO[0016] Cluster 'cht-e2e' created successfully!      

INFO[0016] You can now use it like this:                
kubectl config use-context k3d-cht-e2e
kubectl cluster-info

Error response from daemon: manifest for medicmobile/cht-haproxy:4.10.0-8039-contactsummary-log.977[21](https://github.com/medic/cht-core/actions/runs/9772146005/job/26977203747?pr=8454#step:14:22)46005 not found: manifest unknown: manifest unknown

  1) "before all" hook: beforeAll in "{root}"
INFO[0000] Deleting cluster 'cht-e2e'                   

INFO[0000] Deleting cluster network 'k3d-cht-e2e'       

INFO[0000] Deleting 1 attached volumes...               

INFO[0000] Removing cluster details from default kubeconfig... 

INFO[0001] Removing standalone kubeconfig file (if there is one)... 

INFO[0001] Successfully deleted cluster cht-e2e!        

Test done. Signing off ...

  0 passing (18s)
  1 failing

  1) "before all" hook: beforeAll in "{root}":
     Error: the string "Error response from daemon: manifest for medicmobile/cht-haproxy:4.10.0-8039-contactsummary-log.9772146005 not found: manifest unknown: manifest unknown\n" was thrown, throw an Error :)
      at thrown2Error (/home/runner/work/cht-core/cht-core/node_modules/mocha/lib/runner.js:1[24](https://github.com/medic/cht-core/actions/runs/9772146005/job/26977203747?pr=8454#step:14:25)1:10)
      at Runner.fail (/home/runner/work/cht-core/cht-core/node_modules/mocha/lib/runner.js:443:11)
      at cbHookRun (/home/runner/work/cht-core/cht-core/node_modules/mocha/lib/runner.js:532:14)
      at done (/home/runner/work/cht-core/cht-core/node_modules/mocha/lib/runnable.js:[31](https://github.com/medic/cht-core/actions/runs/9772146005/job/26977203747?pr=8454#step:14:32)0:5)
      at /home/runner/work/cht-core/cht-core/node_modules/mocha/lib/runnable.js:377:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)



Error: Process completed with exit code 1.

```
</details>

**Comment by dianabarsan** [comment] 2024-07-08 09:48
Closing as duplicate of https://github.com/medic/cht-core/issues/9097

**Closed by dianabarsan** 2024-07-08 09:48 UTC
Labels: Type: Bug
