### ISSUE TITLE
Incorrect form summary delivery date in default pregnancy form

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#8045] opened 2023-01-25 07:26 UTC
**Describe the bug**
When submitting a pregnancy form, and using the estimated delivery date input option, the displayed delivery date is different from the actually selected one. 

This might be only the case now, when selecting a delivery date in February, and on a GMT+ timezone. 

**To Reproduce**
1. Load default config. 
2. Load a pregnancy form. Select `Expected date of delivery (EDD)` as the gestational age calculation method. 
3. Set the expected delivery date to be one month from now (In my case Feb 25th). 
4. Go to next page, and see that EDD is one day before your selected date, Feb 24th. 
5. Continue filling the form, and notice that on the summary page the EDD is displayed incorrectly. 
6. Submit the form. On submission, the correct delivery date is saved! 

**Expected behavior**
Actually selected date should be displayed. 

**Logs**
No errors

**Video**

https://user-images.githubusercontent.com/35681649/214503863-f30a679f-1d69-4211-8811-65b57c125be7.mp4

**Environment**
- Instance: local
- App: webapp
- Version: 4.1.0

**Additional context**
Discovered because an e2e test was failing locally. I should mention that I'm on GMT+2.

**Comment by dianabarsan** [comment] 2023-07-14 11:53
This is happening again today (Jul 14th)

**Comment by Benmuiruri** [comment] 2023-12-13 07:10
I don't think this is still an issue as of today (Dec 13, 2023). I followed the steps to reproduce but I did not see the bug. [1 min Loom video](https://www.loom.com/share/e654ce32778540018a21c9f72b403b47)

**Comment by latin-panda** [comment] 2023-12-18 12:51
Same, I can't reproduce this issue with the pregnancy form, I tried 25th February and other dates, and it's displaying as expected. 

https://github.com/medic/cht-core/assets/66472237/1ca502b3-4d00-4702-932d-807edeac50e3

<img width="400" src="https://github.com/medic/cht-core/assets/66472237/f2c58867-1f3c-4dea-bf5f-fd6c215e4090">

Closing issue

**Closed** 2023-12-18 12:51 UTC
Labels: Type: Bug, Config: ANC Reference (default)
