### ISSUE TITLE
Language translations not working when not supported by `make-plural`

### ISSUE THREAD

**Issue by craig-landry** [medic/cht-core#6848] opened 2021-01-15 20:41 UTC
This was previously addressed with https://github.com/medic/cht-core/issues/5705 and regressed in CHT 3.8. The regression comes due to an updated `messageformat` dependency in CHT 3.8.

The prior fix to `messageformat` was done via monkey patching, which was applicable for `messageformat` 2.2.1 and does not work in the current version of `messageformat` (2.3.0).

**Comment by dianabarsan** [comment] 2021-01-18 13:03
Just wanted to point out that the issue manifests a little bit differently now, compared to before. 
The reports list loads but when navigating to a contact, where we actually use pluralization, those translations will fail and the console will list errors: 

![image](https://user-images.githubusercontent.com/35681649/104918939-2f684700-599e-11eb-901e-d052bd7ab9df.png)

![image](https://user-images.githubusercontent.com/35681649/104919023-47d86180-599e-11eb-9837-a336c532a5e3.png)

**Comment by ngaruko** [comment] 2021-01-19 02:02
Tested using the branch `6848-dual-monkey-patch-message-format`, on a local machine, following these steps

1. checkout the master branch
2. do a local deployment as per [documentation](https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md#deploying-the-web-app) (basically `npm ci`, then `grunt`, then `grunt dev-api`, then `grunt-sentinel`, in a nutshell)
3. Go to [languages tab](http://localhost:5988/admin/#/display/languages) in the admin portal > display
4. Add new language (code :`ceb`, name :`Cebuano`)
5. Upload a translation file `messages-ceb.properties` (I copied the tagalog translation from the [config-icm](https://github.com/medic/config-icm/tree/86-changes/translations) repo and added a few translations (make Google Translate your friend) - Upload either manually from the UI/admin portal or with `medic-conf --local upload-custom-translations` - There is a warning in the terminal: `WARN 'cel' is not a recognized ISO 639 language code, please ask admin to set the name `
6. Create a user (first a health facility if it is a new db, with no seed data)
7. Log in as the new created user
8. Add a new person and a report that generates tasks 
9. Go to tasks and observe all translations look ok (default being English)
![image](https://user-images.githubusercontent.com/6979995/104977801-4cb41880-5a65-11eb-9c42-6d231ce1eedc.png)

10. Go to ['Edit User Profile'](http://localhost:5988/#/user), change the language to `Cebuano`
11. Observe errors on the console
12. Go to 'Tasks`, observe missing translations 
![image](https://user-images.githubusercontent.com/6979995/104977988-c1875280-5a65-11eb-93e0-b10c2ca1af09.png)

13. Go to contact and observe same...
14. Now, checkout the `` branch 
15. Log out and log in again as the user created above & change language to cebuano
16. Go to Task and observe translations work: 
17. Same with contact page : 
![image](https://user-images.githubusercontent.com/6979995/104978549-ecbe7180-5a66-11eb-91be-39ce7d6d9f08.png)

**Comment by ngaruko** [comment] 2021-01-19 02:34
One observation that need further investigation but not related to this PR:
Switching between language seems to be glitchy , one has to move between 2 or more clicks before the choice works. We have seen this [before](https://github.com/medic/cht-core/issues/6302), maybe a regression ?

**Comment by dianabarsan** [comment] 2021-01-20 10:21
@ngaruko please tell me if you consider this as ready to be merged.

**Comment by ngaruko** [comment] 2021-01-20 10:25
@dianabarsan Yes - This is ready. Please feel free to merge and release a beta (unless @binokaryg would like to include the datepicker in the release?) Then we will do a quick RT around languages/translations before the end of the week.

**Comment by binokaryg** [comment] 2021-01-20 10:33
I am still waiting for confirmation from the partner. Will it help if add the draft translations now and change them later before the final release if required?

**Comment by dianabarsan** [comment] 2021-01-20 13:43
Merged into `master` and backported to `3.10.x`.

**Closed by dianabarsan** 2021-01-20 13:43 UTC
Labels: Regression, Type: Bug
