### ISSUE TITLE
Gateway number validation is too strict

### ISSUE THREAD

**Issue by benkags** [medic/cht-core#5864] opened 2019-08-05 12:35 UTC
**Describe the bug**
With introduction of Africa's talking integration, we can now use a short code e.g 42341 as the gateway phone number. This is configurable in the app settings uploaded to the instance but the  UI validates against a value that is not a valid phone number.

**To Reproduce**
1. Navigate to the admin settings page on the webapp ideally running v3.6.0 and above as this is the version we expect integration to SMS aggregator AT to work.
2. Input a candidate short code in the **Gateway Phone Number** text field e.g 42341
3. Click submit to save.
4. You should observe the follow validation message: _This is number where mobile reporters should send their reports. It is also the number they will receive messages from.Not a valid phone number._ hindering you from saving.

**Expected behavior**
Ability to set a short code as the gateway phone number. (Rename the label while at it maybe ?)

**Screenshots**
![Screenshot from 2019-08-05 15-12-34](https://user-images.githubusercontent.com/3006199/62464769-2a0d4180-b796-11e9-9b57-19033942751d.png)

**Environment**
- Instance: https://cdc-mohke-dsru.dev.medicmobile.org
- App: webapp 
- Version: 3.6.0

**Comment by garethbowen** [comment] 2019-08-05 22:45
As a workaround I think you can disable this validation as per [the documentation](https://github.com/medic/medic-docs/blob/master/configuration/app-settings.md#optional-settings).

**Comment by wtekeu** [comment] 2019-10-31 18:53
@garethbowen what about adding two new options for phone validation:

1. partial_with_shortcode
2. full_with_shortcode

what do you think?

**Comment by garethbowen** [comment] 2019-10-31 19:58
IMO the problem is that we use the same level of validation throughout the app. I think it should only be applied when typing in a user's phone number which we don't expect to be a shortcode.

If we added the new options you suggest then these would also apply when adding users or contacts and I don't think that's correct.

The easiest solution I can think of is to remove the validation from this field altogether. Alternatively we could hardcode this field to use the gentler form of validation which allows shortcodes rather than using the configured level of validation.

**Comment by benkags** [comment] 2019-11-07 08:42
I had not realized that deactivating phone_number validation as per the [documenation](https://github.com/medic/medic-docs/blob/master/configuration/app-settings.md#optional-settings) as suggested above would deactivate for all phone number fields until your latest comment @garethbowen. That being the case, then hardcoding this particular field to allow for shortcodes is the probably best way forward.

**Comment by garethbowen** [comment] 2019-11-13 23:35
Ready for AT in `5864-gateway-number-validation`

**Comment by ngaruko** [comment] 2019-11-14 02:08
There are 3 
1 - Upon clicking `submit`, the gateway textbox adds a + sign in front of the code like so
![image](https://user-images.githubusercontent.com/6979995/68820380-f5dbe200-06ef-11ea-93a9-9716a473eb61.png)

 2 - There is another page where this gateway number is required: `Configuration wizard`,  shouldn't we apply the same custom validation there as well : 
![image](https://user-images.githubusercontent.com/6979995/68820555-7c90bf00-06f0-11ea-80e8-8a9a82eb14c9.png)

3- The submit button hangs ...but this is also on `master` and was most probably introduced by #5381  . Will create a separate issue for that:
![image](https://user-images.githubusercontent.com/6979995/68820474-363b6000-06f0-11ea-8a64-5fa6ba68a03a.png)

```angular.js:15567 TypeError: Cannot read property 'replace' of undefined
    at ChildScope.$scope.submit (sms-settings.js:59)
    at fn (eval at compile (angular.js:16418), <anonymous>:2:138)
    at callback (angular.js:28951)
    at ChildScope.$eval (angular.js:19393)
    at ChildScope.$apply (angular.js:19492)
    at HTMLButtonElement.<anonymous> (angular.js:28955)
    at HTMLButtonElement.dispatch (jquery.js:5237)
    at HTMLButtonElement.elemData.handle (jquery.js:5044)```

**Comment by ngaruko** [comment] 2019-11-14 02:18
^ or would you prefer we re-open #5381 @garethbowen for number 3 above?

**Comment by garethbowen** [comment] 2019-11-14 02:41
Raise a new issue I think - it's confusing when an issue is reopened when the code is already merged.

**Comment by garethbowen** [comment] 2019-12-02 21:09
Ready for AT in `5864-gateway-number-validation`

**Comment by ngaruko** [comment] 2019-12-03 07:07
LGTM
Have opened a different [issue](https://github.com/medic/cht-core/issues/6117) for the `submit` button not working . #6117

**Closed** 2019-12-03 07:09 UTC
Labels: Help wanted, Priority: 2 - Medium, Type: Bug
