### ISSUE TITLE
Make configurable, marking of outgoing messages as duplicates

### ISSUE THREAD

**Issue by benkags** [medic/cht-core#6094] opened 2019-11-07 08:34 UTC
**What feature do you want to improve?**
If a message similar to a recently sent out message is seen by the system, it is marked as duplicate and is never sent to the recipient. Generally, this is the desired behavior but there is a need to make it configurable such that this feature can be deactivated for a specif config. 

**Describe the improvement you'd like**
I imagine a configuration that allows specifying a delay i.e how long since last similar message was sent, that can be as low as 0 for cases where we do not want any messages to be marked as duplicate would be ideal.

**Describe alternatives you've considered**
Adding to the message something that makes the message slightly different from previous ones which works for some cases but not all.

**Additional context**
Imagine a situation where the system sends a validation message based on a user's submission but the user re-submits again using the same inputs. In this case, only the first validation message will go out and on subsequent submissions, the user will be left wondering if their submission was accepted.

**Comment by kennsippell** [comment] 2020-02-15 15:47
@benkags Can you help with the prioritization of this feature request? Is this relevant only for CDC-EBS or for other projects? How impactful is this to the CDC user experience?

**Comment by benkags** [comment] 2020-03-12 06:59
Users interacting with the system by sending the incorrect input are mean to get an auto-reply guiding them on sending in the correct thing. This is currently not happening if the user sends in the incorrect input in quick succession since the auto-replies following the first one are marked as duplicates and never sent to the user.

**Comment by benkags** [comment] 2020-03-12 07:03
cc @Maigua

**Comment by SCdF** [comment] 2020-04-03 14:33
This is caused by how https://github.com/medic/cht-core/issues/4715 was implemented.

We need to work out how to support both use cases simultaneously. Dev investigation needs to take place, but to me it seems likely that as long as are sending SMS to a known phone number we can send it as many times as we like?

The linked ticket above is, IMO, there to stop auto reply loops to ISPs and other random numbers.

**Comment by kennsippell** [comment] 2020-04-08 15:58
We are scaling our existing EBS systems to new counties and spinning up new EBS systems for our COVID response. Project teams feel this was the fourth most important issue to prioritise for COVID EBS scale-up response behind #5817 #6148 #6286.

**Comment by MaxDiz** [comment] 2020-04-24 21:07
Adding to v3.10 based on outcomes from prioritization meeting April 16, 2020.

**Comment by garethbowen** [comment] 2020-04-28 23:36
We can't allow this to be configured off completely for any form as this has been disastrous for projects in the past. However the current implementation is clearly naive and we can do something more clever here. For example, we could allow a certain number of duplicates (eg: 5) to be sent in a certain timeframe before stopping replies completely. This means if we get into an infinite loop with a bot we may waste 5 messages instead of 1, but the loop will be broken and an real user is unlikely to hit that limit.

@benkags Would that work for you?

**Comment by benkags** [comment] 2020-04-29 06:45
Yeah, I think that would work @garethbowen

**Comment by SCdF** [comment] 2020-04-29 10:20
@garethbowen is what I wrote here when I said:

> but to me it seems likely that as long as are sending SMS to a known phone number we can send it as many times as we like?

Not a correct understanding of the situation? Are there situations where we are receiving an SMS from a number that is attached to a patient that could be automated (and so disastrous in terms of infinite looping)? Or is it that while this is true it's harder to implement than just increasing the limit?

**Comment by garethbowen** [comment] 2020-04-29 19:02
We could have a higher limit for looping to known numbers perhaps, but I think even known numbers could end in an infinite loop, for example if the carrier blocks the message (because we're spamming too much, or the number is no longer in use, or... something?).

I also worry that for self-reporting workflows the number is likely to be unknown, at least initially. If they're struggling to work out how to send a message we want to keep sending them the error SMS rather than just radio silence.

**Comment by SCdF** [comment] 2020-04-30 08:56
> if the carrier blocks the message (because we're spamming too much, or the number is no longer in use, or... something?).

Ah, I was not aware these would present as those numbers

>  If they're struggling to work out how to send a message we want to keep sending them the error SMS rather than just radio silence.

Yeah, I wonder if we can get stats for this once we deploy

**Comment by garethbowen** [comment] 2020-05-25 21:30
Ready for AT in `6094-configurable-duplicates`.
[Documentation PR](https://github.com/medic/medic-docs/pull/224).

**Comment by dianabarsan** [comment] 2020-06-04 08:16
new documentation PR: https://github.com/medic/beta/pull/55

**Comment by ngaruko** [comment] 2020-07-06 02:26
LGTM

**Comment by dianabarsan** [comment] 2020-07-06 07:04
Merged into `master`.

**Closed by dianabarsan** 2020-07-06 07:04 UTC
Labels: COVID-19, Type: Improvement
