### ISSUE TITLE
Inconsistent date value in the list of deaths. 

### ISSUE THREAD

**Issue by ranjuts** [medic/cht-core#6066] opened 2019-10-25 11:01 UTC
**What feature do you want to improve?**
When you navigate to a list of deaths from the household profile, you can see a list of deaths with time of death displayed on the right hand corner. If the death happened today it displays as "00:00" and if happened a day or more ago, it displays as "1 day ago" and so on. 

**Describe the improvement you'd like**
Ideally, this should be consistent - if they death happened today, it should display as "0 days ago". 

**Describe alternatives you've considered**
None. The improvement described above should suffice. 

**Additional context**
![Screen Shot 2019-10-22 at 6 39 23 PM](https://user-images.githubusercontent.com/5404004/67566182-e4359900-f746-11e9-918a-7b4f65ef6102.png)

**Comment by garethbowen** [comment] 2019-10-28 22:03
Thanks for the report! I think this is a duplicate of #6053

**Closed** 2019-10-28 22:03 UTC
Labels: Type: Improvement
