### ISSUE TITLE
Ubuntu-18.04 github actions environment is deprecated

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7741] opened 2022-08-22 14:50 UTC
**Describe the issue**
[GH is deprecating the 18.04 CI runner](https://github.com/actions/runner-images/issues/6002) and implementing intentional outages to let people know about the deprecation. This is causing our builds to fail right now, and will continue to have schedule failure times:

* August 22, 12:00 UTC - August 22, 16:00 UTC
* August 30, 12:00 UTC - August 30, 18:00 UTC
* September 7, 12:00 UTC - September 7, 20:00 UTC
* September 15, 10:00 UTC - September 15, 20:00 UTC
* September 23, 10:00 UTC - September 23, 22:00 UTC
* October 3, 0:00 UTC - October 4, 0:00 UTC
* October 11, 0:00 UTC - October 12, 0:00 UTC
* October 19, 0:00 UTC - October 20, 0:00 UTC
* October 31, 0:00 UTC - November 1, 0:00 UTC
* November 8, 0:00 UTC - November 9, 0:00 UTC
* November 16, 0:00 UTC - November 17, 0:00 UTC
* November 24, 0:00 UTC - November 25, 0:00 UTC

**Describe the improvement you'd like**
We should upgrade our [build](https://github.com/medic/cht-core/blob/master/.github/workflows/build.yml) and [cleanup](https://github.com/medic/cht-core/blob/master/.github/workflows/cleanup.yml) flows to use a more recent version of ubuntu, presumably 22.04 if possible.  [Scalability](https://github.com/medic/cht-core/blob/master/.github/workflows/scalability.yml) already uses `runs-on: ubuntu-latest` so doesn't need to upgrade.

**Describe alternatives you've considered**
NA, we need our builds to run ;)

**Comment by jkuester** [comment] 2022-08-24 19:20
## Additional context

- [GH Blog post announcing change](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/)
- [GH Documentation regarding available runner images](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)
- [GH Blog post announcing `22.04` image is GA](https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/)

### Software differences

| Tool name                  | Ubuntu 18.04                                                                       | Ubuntu 20.04                                                                                                         | Ubuntu 22.04                                                                                   | Notes                                                                                                                                                                                                                                                                                                                                                                          |
|----------------------------|------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| AWS CLI                    | 1.18.173                                                                           | 2.0.62                                                                                                               | -                                                                                              | These two versions have major set of breaking changes. See migration guide for details                                                                                                                                                                                                                                                                                         |
| .NET Core                  | 2.1.x, 3.0.x, 3.1.x                                                                | 3.1, 5.0                                                                                                             | 6                                                                                              | .NET Core 3.0 was removed (3.0.100, 3.0.101, 3.0.102, 3.0.103). NET Core 3.0 has reached end of life, meaning it is no longer supported and not recommended to use. If you still need it, consider using setup-dotnet and UseNetCore tasks. Please consider using tasks to install any version on-flight:- actions/setup-dotnet (GitHub Actions)- Use .NET Core (Azure DevOps) |
| Java                       | 78(default)1112                                                                    | 811(default)                                                                                                         | -                                                                                              | If you need to use other versions of Java, consider using setup-java and Java tool installer tasks.                                                                                                                                                                                                                                                                            |
| Android                    | 17.0 - 30.0                                                                        | 27.0 - 30.0                                                                                                          | -                                                                                              | Android Platforms and build tools < 27.0 were removed from image. Consider installation in runtime using sdkmanager                                                                                                                                                                                                                                                            |
| Ruby                       | 2.5.1                                                                              | Default version: 2.7.xPre-cached versions: 2.5, 2.6, 2.7, 3.0, 3.1                                                   | Default version: 3.0.xPre-cached versions: 3.1                                                 | Default Ruby was changed from 2.5.x to 2.7.x. Consider using setup-ruby and UseRuby tasks. On GitHub Actions, ruby/setup-ruby can install any version on-flight so this change doesn't impact users                                                                                                                                                                            |
| Ruby toolcache             | 2.42.52.62.7                                                                       | 2.52.62.7                                                                                                            |                                                                                                | Ruby 2.4 will become unavailable via install tasks                                                                                                                                                                                                                                                                                                                             |
| Python3                    | 3.6.9                                                                              | Default version: 3.8.xPre-cached versions: 2.7, 3.6, 3.7, 3.8, 3.9, 3.10                                             | Default version: 3.10.xPre-cached versions: 3.7, 3.8, 3.9, 3.10                                | Default Python will be updated from 3.6 to 3.8. Consider using setup-python or UsePython to switch version. On GitHub Actions, actions/setup-python can install any version on-flight so this change doesn't impact users                                                                                                                                                      |
| PHP                        | 7.17.27.37.48.0                                                                    | 7.4, 8.0, 8.1                                                                                                        | 8.1                                                                                            | Deprecated all the versions besides the most recent one                                                                                                                                                                                                                                                                                                                        |
| Azure PowerShell           | 1.0.0, 1.6.0, 2.3.2, 2.6.0, 2.8.0, 3.1.0, 3.5.0, 3.8.0, 4.3.0, 4.4.0, 4.6.0, 4.7.0 | Installed: 7.3.2Zipped: 3.1.0, 4.4.0, 5.9.0, 6.6.0                                                                   | Installed: 7.3.2Zipped: -                                                                      | If your use-case requires using any of these versions, consider using tasks to install Az modules on-flight:- azure-powershell-action (GitHub Actions)- Azure PowerShell (Azure DevOps)****                                                                                                                                                                                    |
| Boost                      | 1.72.0                                                                             | -                                                                                                                    | -                                                                                              | Boost is not pre-installed on Ubuntu 20.04 image                                                                                                                                                                                                                                                                                                                               |
| MySQL                      | 5.7                                                                                | 8.0                                                                                                                  | -                                                                                              | See migration guide for more details about breaking changes                                                                                                                                                                                                                                                                                                                    |
| SVN                        | 1.9.7                                                                              | 1.13.0                                                                                                               | -                                                                                              | -                                                                                                                                                                                                                                                                                                                                                                              |
| Swig                       | 3.0.12                                                                             | 4.0.1                                                                                                                | -                                                                                              | -                                                                                                                                                                                                                                                                                                                                                                              |
| libcurl apt package        | libcurl3                                                                           | libcurl4                                                                                                             | -                                                                                              | -                                                                                                                                                                                                                                                                                                                                                                              |
| Clang                      | -                                                                                  | 10.0.0, 11.0.0, 12.0.0                                                                                               | 11.1.0, 12.0.1                                                                                 | clang 10 is not available for Ubuntu 22                                                                                                                                                                                                                                                                                                                                        |
| GCC/G++                    | -                                                                                  | 9.4.0 (default), 10.3.0                                                                                              | 9.4.0, 10.3.0, 11.2.0 (default)                                                                | the default version for Ubuntu 22 is different                                                                                                                                                                                                                                                                                                                                 |
| Erlang                     | -                                                                                  | 24.*                                                                                                                 | -                                                                                              | Erlang is not available for Ubuntu 22 at the moment                                                                                                                                                                                                                                                                                                                            |
| Swift                      | -                                                                                  | 5.*                                                                                                                  | -                                                                                              | Swift is not available for Ubuntu 22 at the moment                                                                                                                                                                                                                                                                                                                             |
| HHVM (HipHop VM)           | -                                                                                  | 4.*                                                                                                                  | -                                                                                              | HHVM is not available for Ubuntu 22 at the moment                                                                                                                                                                                                                                                                                                                              |
| OpenSSL                    | -                                                                                  | 1.1.*                                                                                                                | 3.*                                                                                            | The default OpenSSL in Ubuntu is now version 3                                                                                                                                                                                                                                                                                                                                 |
| PhantomJS                  | -                                                                                  | 2.1.1                                                                                                                | -                                                                                              | The software is deprecated as the latest version was released in 2016                                                                                                                                                                                                                                                                                                          |
| Firefox\geckodriver        | -                                                                                  | 99.*                                                                                                                 | -                                                                                              | Firefox is not available for Ubuntu 22 at the moment                                                                                                                                                                                                                                                                                                                           |
| MongoDB                    | -                                                                                  | 5.0.*                                                                                                                | -                                                                                              | MongoDB is not available for Ubuntu 22 at the moment                                                                                                                                                                                                                                                                                                                           |
| MS SQL Server Client Tools | -                                                                                  | SqlPackage 16.*sqlcmd 17.*                                                                                           | SQL tools are not available for Ubuntu 22 at the moment                                        |                                                                                                                                                                                                                                                                                                                                                                                |
| Go                         | -                                                                                  | Default version: 1.17.xPre-cached versions: 1.16, 1.17, 1.18                                                         | Default version: 1.18xPre-cached versions: 1.17, 1.18                                          | If your use-case requires using any of these versions, consider using tasks to install Go on-flight:- actions/setup-go (GitHub Actions)- Go Tool Installer (Azure DevOps)                                                                                                                                                                                                      |
| Node.js                    | -                                                                                  | Default version: 16.xPre-cached versions: 12, 14, 16                                                                 | Default version: 16.xPre-cached versions: 14, 16                                               | If your use-case requires using any of these versions, consider using tasks to install Node.js on-flight:- actions/setup-node (GitHub Actions)- Node.js Tool Installer (Azure DevOps)                                                                                                                                                                                          |
| PyPy                       | -                                                                                  | 2.7, 3.6, 3.7, 3.8, 3.9                                                                                              | 3.7, 3.8, 3.9                                                                                  | Deprecated all the versions besides the most recent ones                                                                                                                                                                                                                                                                                                                       |
| Docker images              | -                                                                                  | Alpine: 3.12, 3.13, 3.14buildpack-deps: bullseye, buster, stretchdebian: 9, 10, 11node: 12, 14, 16ubuntu: 16, 18, 20 | Alpine: 3.14, 3.15buildpack-deps: bullseye, busterdebian: 10, 11node: 14, 16ubuntu: 18, 20, 22 | Deprecated all the versions besides the most recent one                                                                                                                                                                                                                                                                                                                        |

(Sources: https://github.com/actions/runner-images/issues/1816 https://github.com/actions/runner-images/issues/5490)

**Comment by garethbowen** [comment] 2022-08-24 20:40
It's also worth checking other repos and fixing those at the same time.

**Comment by jkuester** [comment] 2022-08-24 22:27
Related: https://github.com/medic/app-services-team/issues/400

**Comment by jkuester** [comment] 2022-08-26 22:46
Wanted to record here that after a discussion with @garethbowen, we have decided to pin our workflows to the latest tag version (`ubuntu-22.04`) instead of using the `ubuntu-latest` tag.  The idea here is that in the future it is pretty easy to upgrade the tag version when it gets deprecated. At that time, if there are build issues it will be obvious that they were caused by the image changing.  If we used `ubuntu-latest`, GitHub will announce on their blog when they are moving that tag to a new version, but if it causes actual build issues in some of our workflows it will not be immediately obvious what is issue is. It seems better to commit to a small amount of maintenance work later, to avoid the possibility of wasting a ton of time debugging an issue caused by the tag moving...

**Comment by jkuester** [comment] 2022-08-26 22:50
I have tried to update all of the Medic projects that are directly maintained by the Product team engineers (that have GH workflows). I have not updated any projects that I understood to be maintained by app-services or by SRE.  I also did not touch new unreleased projects.  

Please call them out if I have missed any or if I should not have included any of the repose in the list below!

PRs:
- https://github.com/medic/cht-core/pull/7748
- https://github.com/medic/cht-docs/pull/755
- https://github.com/medic/cht-android/pull/299
- https://github.com/medic/cht-conf/pull/503
- https://github.com/medic/cht-nootils/pull/29
- https://github.com/medic/cht-couch2pg/pull/124
- https://github.com/medic/couch2pg/pull/39
- https://github.com/medic/translation-checker/pull/8
- https://github.com/medic/rapidpro2pg/pull/6
- https://github.com/medic/cht-sync/pull/8
- https://github.com/medic/cht-gateway/pull/185
- https://github.com/medic/medic-builds-repo/pull/27

**Comment by mrjones-plip** [comment] 2022-08-30 21:09
FYI, [update from github](https://github.com/actions/runner-images/issues/6002#issuecomment-1231949367) is::

> The deprecation date has shifted to March 1st, 2023 to give more time to adapt the workflows to Ubuntu20 or Ubuntu22.
The brownout schedule is also adjusted and now has shortened periods.

**Comment by mrjones-plip** [comment] 2022-09-02 23:13
yet [another update](https://github.com/actions/runner-images/issues/6002#issuecomment-1235119350) from GH:

> We have decided to prolong the deprecation until the official end of life — April 2023. Brownouts schedule has been adjusted as well to reflect the prolonged deprecation

**Comment by jkuester** [comment] 2022-09-19 19:11
This has now been completed on all the above-linked repos!

**Closed by jkuester** 2022-09-19 19:11 UTC
Labels: Type: Technical issue
