### ISSUE TITLE
Feedback docs: "403: Failed to load template"

### ISSUE THREAD

**Issue by binokaryg** [medic/cht-core#7150] opened 2021-06-16 09:15 UTC
**Describe the bug**
One user of brac-ug (version 3.9.2) encountered this error four times in April 2021, as recorded in the feedback docs.
`[$templateRequest:tpload] Failed to load template: templates/... (HTTP status: 403 )`

**Logs**
```
1. [$templateRequest:tpload] Failed to load template: templates/directives/actionbar.html (HTTP status: 403 )
https://errors.angularjs.org/1.7.8/$templateRequest/tpload?p0=templates%2Fdirectives%2Factionbar.html&p1=403&p2=
2. [$templateRequest:tpload] Failed to load template: templates/directives/header.html (HTTP status: 403 )
https://errors.angularjs.org/1.7.8/$templateRequest/tpload?p0=templates%2Fdirectives%2Fheader.html&p1=403&p2=
3. [$templateRequest:tpload] Failed to load template: templates/modals/version_update.html (HTTP status: 403 )
https://errors.angularjs.org/1.7.8/$templateRequest/tpload?p0=templates%2Fmodals%2Fversion_update.html&p1=403&p2=
4. [$templateRequest:tpload] Failed to load template: templates/partials/about.html (HTTP status: 403 )
https://errors.angularjs.org/1.7.8/$templateRequest/tpload?p0=templates%2Fpartials%2Fabout.html&p1=403&p2=
```
All 4 errors in April '21  were encountered from the About page.

**Environment**
- Instance: brac-ug.app.medicmobile.org
- Version: 3.9.2

**Additional context**
Similar errors are being recorded 4 to 8 times a month since we started collecting the feedback docs in August 2020 for this project. There are 6 users who have had this error with a total of 39 times so far.

Interestingly, we didn't see this error in May 2021, but it's back in June 2021.

**Comment by dianabarsan** [comment] 2021-06-18 04:07
This seems like quite a peculiar AngularJS template cache failure. 
Given that we're off AngularJS and this seems fairly infrequent, I'm not sure this will warrant spending time on investigating. I'm leaning towards thinking this is an AngularJS bug, which will be unlikely to be easily fixed/patched/worked around. 
I personally have never seen this error, nor have I ever heard of any QA experiencing this. 

> There are 6 users who have had this error with a total of 39 times so far
And all of these are on the About page?

**Comment by binokaryg** [comment] 2021-06-18 07:37
Only 7 of now total 43 (up from 39 before) are on the About page.
32 of them are on the Home page, and 4 on specific task action: `0~family_survey_yields_family_survey`.

**Comment by garethbowen** [comment] 2021-06-20 18:56
There are all sorts of cache errors that could happen but the only way I can think a 403 makes sense is if the user is logged out when downloading the templates file from the server. If this is the case then it's probably not a big deal because they're probably redirected to the login page so from the user's perspective everything is working as expected.

@binokaryg Can you tell if these are offline users or online users?

In general I agree with Diana - it's highly unlikely this specific error is reproducible in 3.11+ due to the Angular upgrade.

**Comment by binokaryg** [comment] 2021-06-21 10:52
@garethbowen All the 6 users are offline users who have this in the roles:
 `["district-manager", "kujua_user", "data_entry", "district_admin"]`.

**Comment by dianabarsan** [comment] 2021-06-21 11:09
I wonder if this could be a service worker fluke.

**Comment by latin-panda** [comment] 2024-08-19 07:52
Closing issue.
- Given that 3.9 support ended on 9-Dec-2020. 
- We now use Angular 17, and the code is different
- The actionbar component was removed [here](https://github.com/medic/cht-core/issues/8181)
- And no more reports since Jun 2021.

**Closed by latin-panda** 2024-08-19 07:52 UTC
