### ISSUE TITLE
Searching for a contact name that has a short value will return no results.

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#7288] opened 2021-09-01 19:51 UTC
**Describe the bug**
Searching for a contact name that has a short value will return no results.

The name could be  `Steve Kshlerin I` or  `Steve I`

**To Reproduce**
1. Login and navigate to contacts page. 
2. Add a new person that is name `Steve Kshlerin I`
3. Navigate to contacts page.
4. Search in the search bar for `Steve`
5.  The contact is returned
4. Search in the search bar for `Steve Kshlerin`
5.  The contact is returned
6.  Search in the search bar for `Steve Kshlerin  I`
7. Nothing is returned

**Expected behavior**
The search should locate the contact and return a row for that contact. 

**Logs**
If applicable, include the server or browser logs.

**Screenshots**

https://user-images.githubusercontent.com/10531066/131734925-28a1c49a-6791-450a-b85e-4910d1ca0c14.mp4

**Environment**
- Instance: gamma.dev
- Browser: chrome
- Client platform: windows
- App: webapp
- Version: 3.12.x

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by garethbowen** [comment] 2024-01-26 08:18
This came up on the forum: https://forum.communityhealthtoolkit.org/t/unexpected-search-results/3288/3

**Comment by garethbowen** [comment] 2024-01-26 08:20
The root cause of this is the server ignores short search terms when indexing the doc ("I" in this case) but the client does not when searching. We need to modify the client code to be identical to the server code. This will also help performance because sending a search for a short word that matches lots of docs is a terrible idea.

**Comment by garethbowen** [comment] 2024-01-30 10:43
Fixed in 4.6.0

**Closed by garethbowen** 2024-01-30 10:43 UTC
Labels: Type: Bug
