### ISSUE TITLE
Investigate / discuss Enketo performance

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#4114] opened 2018-01-22 14:27 UTC
A large part of our application is clicking around enketo forms. They can often be slow, especially on more complex forms or slower phones.

What is the state of us investigating Enketo performance? Have we picked the low hanging fruit and we think it's as fast as it's reasonably going to be? Or have we not really looked into it? Do we understand the current performance situation?

cc. @alxndrsn

**Comment by alxndrsn** [comment] 2018-01-22 15:04
> Do we understand the current performance situation?

Not really.  If there are examples of poor performance, it would be great to get some of these recorded.  I guess that would be a combination of handset and form, although I guess there could also be some affect caused by `contact-summary.js` configuration.

**Comment by sglangevin** [comment] 2018-01-23 03:10
I do have some example forms that you can try. The CiC seguimiento form is one of them - it's a long and complex form. But even some of the shorter forms can be slow to load on my Tecno, for example. I can look for a few examples today to share with you.

**Comment by SCdF** [comment] 2018-01-23 08:39
Thanks @sglangevin that would be really helpful. I think we should schedule / time box some time for a developer to go through those complex forms and maybe see if there are any obvious improvements to enketo's (or our use of enketo) performance.

**Comment by alxndrsn** [comment] 2018-01-23 08:44
`enketo-core` has a specific **`performance`** label, which may be of interest following: https://github.com/enketo/enketo-core/issues?q=is%3Aissue+performance+label%3Aperformance

**Comment by sglangevin** [comment] 2018-01-23 09:02
I've sent @SCdF the seguimiento form as a start and will follow up with other examples later today.

**Comment by sglangevin** [comment] 2018-01-23 09:49
Seguimiento form and properties file can be found here: https://github.com/medic/medic-projects/tree/master/cic-guatemalav2/forms/app

**Comment by alxndrsn** [comment] 2018-01-23 09:57
Perhaps worth specifying the commit at which poor performance is known: https://github.com/medic/medic-projects/tree/531097741fab09a079504f979bfe6d78d5a675f0

**Comment by garethbowen** [comment] 2018-01-29 17:32
It would be really useful to compare the CHPs we followed on the LG site visit to see if there's a reason why one had acceptable performance and the other had unacceptable performance.

**Comment by sglangevin** [comment] 2018-01-31 18:30
In terms of performance, I'm more concerned about the time CHWs are waiting behind a spinner than I am about loading of forms. I'd propose focusing on start-up time as that is a big pain point right now for partners. We have #4130 but is there an issue for the profiling that @alxndrsn is doing re: start-up load time and PouchDB performance? If so, I'd like us to swap this ticket for that one and move this one to a later release.

**Comment by SCdF** [comment] 2018-02-01 08:46
It would be interesting to know how frequently CHWs deal with start up. In the past we have presumed that it was rare, but perhaps that is not the case.

Anyway, as long as this doesn't get lost I have no personal issue with other performance issues being prioritised over it.

**Comment by sglangevin** [comment] 2018-02-01 19:15
My understanding from what I've heard is that they deal with start up a lot because they might close the app between households they are visiting. Also, some CHPs have been using our app for a long time and have a lot of data on their phone, so start-up issues just become more acute over time while I would imagine Enketo performance is more constant over time (I could be wrong about that though).

**Comment by garethbowen** [comment] 2024-01-02 12:54
Closing as ancient. Recent enketo-core releases have significantly improved performance since this issue was raised and we're getting better at tracking real world performance. This is a continuous process.

**Closed by garethbowen** 2024-01-02 12:54 UTC
Labels: Type: Performance, Priority: 2 - Medium
