### ISSUE TITLE
Make it easier to complete all tasks at a household in the same visit

### ISSUE THREAD

**Issue by amandacilek-zz** [medic/cht-core#5886] opened 2019-08-12 22:56 UTC
Relates to #5776 (make it clear that tasks can be completed anywhere in the window). Assumes that #5697 and #5710 have already been completed (updating hierarchy levels, adding belongs to breadcrumbs to tasks). 

**Is your feature request related to a problem? Please describe.**
Some CHWs have a hard time navigating the tasks page when it is organized by due date. What we have heard is that they would find it more useful to have the tasks organized by area or household, so that they can prioritize other tasks nearby. 

**Describe the solution you'd like**
1. Add the ability to group tasks together by family, and then sort those grouped families by nearest due date. This means that tasks for the same family will always appear next to each other, but the family groupings will not be sorted alphabetically but instead by due date.

Referring to this mockup:
![Screen Shot 2019-08-12 at 3 46 36 PM](https://user-images.githubusercontent.com/26235957/62903753-a238b180-bd18-11e9-8b0a-ca911ec3a099.png)

- The first two tasks are in the Beatrice Bass Family group. Because there is a task due today, this group (the Beatrice Bass Family group) is first.
- There is only one task for the Zelda Zed family. It comes next because the task is due in 1 day.
- The last two tasks are for Amanda Allen’s family. Even though this family would alphabetically go first, the group comes last because there aren’t any tasks due for at least 2 days.
- Note: The horizontal lines separating family groups are just for mockup purposes, no intended UI update.

2. Add a sort icon to the top tasks bar which gives users the choice to either filter "By date" or "By family". Also, I recommend that we change the default sort so that we sort "By family" by default.

![Screen Shot 2019-08-12 at 3 49 39 PM](https://user-images.githubusercontent.com/26235957/62903821-da3ff480-bd18-11e9-8e4e-1838fc518d47.png)

**Describe alternatives you've considered**
Considered a true alphabetical sort of tasks by family name, but this isn't as helpful, since it might put a task due in 2 weeks for Amanda Allen's family at the very top of the list.

**Comment by MaxDiz** [comment] 2020-03-10 23:45
based on conversation with @n-orlowski , removing from release and returning to the backlog for future consideration

**Comment by n-orlowski** [comment] 2020-03-18 17:50
<img width="662" alt="Screen Shot 2020-03-18 at 10 47 22 AM" src="https://user-images.githubusercontent.com/59581790/76990875-e5d64800-6905-11ea-85dd-560da719ddb0.png">

Latest iteration on this based on https://github.com/medic/cht-core/issues/5776

**Comment by ecsalomon** [comment] 2020-09-29 12:56
A relevant story from a deployment:

> **Background:**
> An issue was reported of perceived duplicate tasks for a person. On investigation, the tasks belonged to 2 different people from different families with similar names.
> 
> **Problem:**
> There wasn't a way of easily establishing that these were different persons since it is only the name of the person that's indicated on the tasks list. This also implies that even if the user is aware of the 2 persons with similar names, data capture can be mixed up as he/she can't tell which person is being worked on.

**Comment by MaxDiz** [comment] 2020-10-18 13:32
adding to 3.12 based on roadmap discussion. @n-orlowski please make sure design is complete and work with @michaelkohn to scope dev requirements

**Comment by n-orlowski** [comment] 2020-11-04 20:46
Reviewing the designs above we've noticed that once the top item (grouped by family and sorted by due date) is cleared, the task list will rearrange itself to show the next due item and its relative family (instead of keeping the initial task grouping at the top).

My proposal is to simplify and have the tasks be sorted only by household name (same order as the People tab). In the scenario described where a CHW is in a specific area and wants to prioritize tasks nearby, sorting alphabetically makes it easier to find those households than households grouped by due date.

This is also a more conventional sort order which is something to keep in mind when considering potential future sorting and filtering states.

@yembrick, tagging for your input as I believe you were involved in this initial design!
cc @michaelkohn 

<img width="873" alt="Screen Shot 2020-11-04 at 12 43 18 PM" src="https://user-images.githubusercontent.com/59581790/98165801-7d4bd380-1eb4-11eb-8602-f877f65399e3.png">

**Comment by yembrick** [comment] 2020-11-10 19:40
I see what you are saying here. 

Playing this out a bit... say the CHW has the page sorted by due date to see their most time pressing tasks. Then the CHW goes to the household with the nearest due date to complete the task. To see other tasks for that household they would have to manually change the sort order to family. Is this something we imagine the CHW would do every time they visit the household? Would they start a day with the due date view, to plan their household visit schedule and then change to household sort for the actual visits? 

I don't love having to switch back and forth to see this info, but agree that the previous design doesn't really work as tasks are completed and the page re-arranges. That seems like it would be confusing and likely frustrating. I think this new proposal is better, even it requires a manual step to change the sort. I definitely agree its more extensible as well, as we might introduce other sorting options in the future.

**Comment by ecsalomon** [comment] 2020-11-12 17:25
Feel free to tell me this is a terrible idea and/or is not feasible, but what if grouping tasks by family gave a family summary instead of the individual tasks with something like `3 tasks for two people` and the _soonest_ due date. Then, to see the tasks for that family, you clicked into a page that has that family's tasks. When you complete a task, you go back to _the family's task page_ rather than the list of families. Would this allow the families to be sorted by task due date without the re-ordering issue?

**Comment by n-orlowski** [comment] 2020-12-04 19:31
<img width="1314" alt="tasks-grouping" src="https://user-images.githubusercontent.com/59581790/101202565-717c3a00-3637-11eb-9806-ce93431cca5b.png">

Working with the team we have come up with our desired V1 and V2 solutions to address the scenarios of CHWs wanting to easily find and complete available tasks within the same household and to find tasks for households nearby. 

We'd like to be able to (V1) sort and group tasks and (V2) to add an interstitial page once a task is submitted to prompt users to complete other tasks within that group. For this issue I'll focus on V1:

- Default sort by due date as this is how CHWs prioritize their work
- Dropdown sort selection to view task groups (in this example, by household and "general" for tasks that are not associated to a household)
- Groups are labelled and ordered numerically for days left and alphabetically for households 
- Tasks within groups are ordered by due date (ex. within household A, show tasks that are due soonest)
- Once a task is submitted, return to the same sort order
- If the user leaves the task tab (ex. closes app, opens other tab) and returns to it, default to due date view

The third screen (priority) is an example of how this pattern might scale to include future sorting options.

Questions: cc @garethbowen 

- If we are collecting GPS data are we able to sort by household task distance? ex. within 2km, 5km+? This might be a more efficient way to find nearby tasks than scrolling through names
- This specific issue refers to households but I'm wondering if we are able to make these groups configurable so that other non-household apps may utilize this feature in a way to better suit?

As always, let me know if I missed anything ✌️

**Comment by kennsippell** [comment] 2020-12-04 20:04
Very curious about the interface being exposed to app developers. Sounds like we can define groups, assign tasks into one or more groups by sortable key. The default proposed here is "no grouping" (sort by due date) - could app builders select the default (eg. two apps right now would want the "priority" grouping by default).

**Comment by garethbowen** [comment] 2020-12-06 19:45
> If we are collecting GPS data are we able to sort by household task distance? ex. within 2km, 5km+? This might be a more efficient way to find nearby tasks than scrolling through names

This is definitely an idea worth exploring but I think it's probably outside the scope of this issue. Currently the GPS is collected based on where the form was filled in which isn't always at the family home. I think to do this properly we would want to add a location widget to the family registration to explicitly set the location of the family home. It may also be technically challenging to work how out far apart two GPS coordinates are, so I wouldn't like to see that derail the other improvements in this issue.

> This specific issue refers to households but I'm wondering if we are able to make these groups configurable so that other non-household apps may utilize this feature in a way to better suit?

Because contact types are configurable the system doesn't know which type is a "household". I imagined that the implementation would be something like "allow sorting by the lowest place contact type you can see". Depending on how the replication depth is configured this may be useful for supervisors to group based on clinics.

> Can this address #5997?

I think that can be done separately by adding an additional filter option to this filter.

> Very curious about the interface being exposed to app developers. Sounds like we can define groups, assign tasks into one or more groups with an associated sortable key?

Currently I don't see that specified in the design. As in my comments above my initial thought was to implement this based on the configured contact types. I'd prefer that we implement a few hardcoded filters (eg: date, contact, priority) and if necessary allow them to be toggled on and off, with a configurable default. This allows the Product team to regression test pre-release and optimise the performance of each filter.

> The default proposed here is "no grouping" (sort by due date) - could app builders select the default

The concern with setting the default sorting by contact group is that tasks for the Yankovic family will always be at the bottom, so even overdue tasks will probably be missed. So I don't think that sorting by contact group should ever be the default.

> ...two apps right now would want the "priority" grouping by default

Priority sorting is covered by [a separate issue](#5997) so it would be good to flag these projects there to help with the design of that feature.

**Comment by yembrick** [comment] 2020-12-09 15:56
Thanks for these updates everyone. I really like your suggestions @n-orlowski , this feels like a big improvement. Upon further reflection, Id like to propose v1 and v2 be tackled together - including the summary page for other group tasks in this issue.  I am not seeing v1 as an MVP and v2 as an improvement. Either option alone feels incomplete to me. This has been on the roadmap for a long time, and we've had such strong feedback from users about this being a priority area of improvement in the UI. @MaxDiz @garethbowen can we talk about this from a scheduling perspective?

**Comment by MaxDiz** [comment] 2020-12-09 17:14
Hi @yembrick this issue is currently scheduled in v3.12 (next release). Breaking into v1 / v2 is new from the release prioritization. We can discuss at the next roadmap planning meeting.

**Comment by kennsippell** [comment] 2020-12-15 00:43
> we've had such strong feedback from users about this being a priority area of improvement in the UI

@yembrick Do recall which users gave this feedback? Which apps?

**Comment by yembrick** [comment] 2020-12-15 17:38
Gosh, some of this was a long time ago, it would take me a bit of time to find notes from those visits. We ran a session with LG-Uganda CHWs on redesign for tasks page back in maybe 2016/7. Also with the LG-K IN Predictive Algorithms group in 2019. This was discussed with Muso CHWs last year, but I wasn't there for that and can't recall exactly how this ranked against other improvements to tasks page.

**Comment by kennsippell** [comment] 2020-12-15 19:36
I'm wondering how we are going to measure this feature's success quantitatively, and which partners we have discussed this experiment with to ensure they will prioritise a cht-core upgrade to pilot, train, and give feedback when 3.12 is ready. I think this issue sounds like a really great experiment with a solid founding to add potential value to apps and users. 

That said, https://github.com/medic/cht-core/issues/5997 has quite some overlap with this issue (largely same UI). Tasks by priority are in-use today by two (or three?) CHT apps (Niger, Goma, Moh-Kenya?) that [use hacks](https://github.com/medic/config-msf/blob/master/niger/tasks.js#L87) to create task priority via static due-dates, and [overwrite](https://github.com/medic/config-msf/blob/master/niger/translations/messages-fr.properties#L1) parts of the UI to make them disappear. For these apps, tasks by priority is a requirement (tasks have no duedate) and it's possible this feature could be implemented in a way that would make those apps ineligible to upgrade to >3.12 until https://github.com/medic/cht-core/issues/5997 is fixed. Just wanting to call out that concern to improve the changes it will be mitigated successfully.

**Comment by yembrick** [comment] 2020-12-15 20:03
Thats really interesting @kennsippell - I am not yet familiar with those task by priority implementations that have happened recently, thanks for sharing! I know @n-orlowski thought about the "priority" tag/sort in this design, but not sure how these are considered in a staggered development across these 2 issues. 

I think this is an experiment we could test with any partner that upgrades to 3.12, that was previously on 3.8 to have had some task data collected. There's a small pool of partners that might be. Theres an interesting conversation here on how ready and willing the users need to be, and how that improves our timelines (due to willingness to upgrade mainly).

**Comment by MaxDiz** [comment] 2020-12-22 01:38
Following on our Dec-2020 Roadmap Planning meeting, we decided to split this issue into 2 improvements based on the designs [shown here](https://github.com/medic/cht-core/issues/5886#issuecomment-738974698). Both issues should be scheduled in v3.12 to kick-off the release.

**Comment by n-orlowski** [comment] 2021-06-24 21:13
Updated designs after our user testing with PIH, BRAC and alignment from D-Tree:

**Mobile**
<img width="1162" alt="Screen Shot 2021-06-24 at 10 54 05 AM" src="https://user-images.githubusercontent.com/59581790/123310029-812b7500-d4da-11eb-9b19-d18be3ca1785.png">

**Desktop**
<img width="1397" alt="Screen Shot 2021-06-24 at 1 55 04 PM" src="https://user-images.githubusercontent.com/59581790/123331175-cad48980-d4f3-11eb-9834-67cfd702b627.png">

- When a user submits a form where the household has additional tasks, display them in the following (interstitial) screen. If no additional household tasks, return to main task list.
- On the mobile interstitial page, the user can begin a new task directly or tap the X in the title to return to their main task list. If the user taps the X, they are asked to confirm they want to leave this page as there is no way to return to this view in the task tab
- On the desktop interstitial page, clicking anywhere but the other household tasks on the right will trigger the confirmation modal.
- Continue to show the interstitial until all household tasks are complete
- Once all household tasks in the interstitial are complete and the user submits the final form, return them to the task list and update the toaster to confirm that "All household tasks completed"
- The tasks displayed in the interstitial should be the same list that is displayed in the People tab on the household page (not relevant for facilities). 

**Metrics to track (cc @helizabetholsen )**
- Number of tasks completed per household in one visit
- Number of outstanding tasks in household after visit
- Use case break down
- Total number of household tasks
- Number of cancelled tasks
- Frequency of household visits

**Future iterations and considerations:**
- Extra configuration to differentiate tasks that are not done in-household (ex. phone follow ups, signal verifications)
- Location data for "tasks near me"


Please add anything I've missed!

**Comment by n-orlowski** [comment] 2021-07-02 16:14
Following up after a call with PIH who is interested in upgrading to 3.13 for this feature; they believe that, if this is the only UI change, minimal training will be needed and that all users should be upgraded and trained together with no additional support needed from us (ex. no need for feature flags, "what's new" modal at this point).

**Comment by dianabarsan** [comment] 2021-07-23 05:59
Just to clarify, this issue doesn't cover any changes done to sorting the task list, and the only changes it covers are described in this comment: https://github.com/medic/cht-core/issues/5886#issuecomment-867955497

**Comment by n-orlowski** [comment] 2021-07-23 16:20
@dianabarsan confirming no sorting changes to the list for this ticket 🙂

**Comment by garethbowen** [comment] 2021-07-25 19:08
@n-orlowski Would you mind editing the issue name to summarise the solution we've landed on to avoid confusion?

**Comment by n-orlowski** [comment] 2021-07-26 16:54
@garethbowen Unfortunately I don't have edit privileges as I didn't open the issue 🙃

**Comment by dianabarsan** [comment] 2021-07-29 16:24
I have some questions about metrics to track: 

> Number of tasks completed per household in one visit

If we choose to track this directly from code - for example count how many tasks were submitted for one household before the user navigates away from the landing page to submit a different task - we could get incorrect metrics if the user navigates away and then comes back and continues to submit tasks for this household. 

Is it possible to track this directly from postgres? For example query for tasks that were updated to get the completed state in one household within one day (? I suppose that's what counts for "one visit" for one household). 
Otherwise, we'd probably have to do something similar in code when we record telemetry at the beginning of next day, to get correct numbers. 

> Number of outstanding tasks in household after visit

Same applies for this, we'd need a daily count for this to be accurate. Otherwise random navigation would skew the numbers. 

> Use case break down

I'm not sure I understand what this means. 

> Total number of household tasks

Is this just "visible" tasks? Should this also include: canceled, failed, or future tasks? 

> Number of cancelled tasks

Is this per household? 

> Frequency of household visits

We already track when tasks are submitted in telemetry. Would it be helpful if we track the specific "place" that was visited in the telemetry value that we store (that would increase the size of the telemetry document that replicates to the server)?
This could be calculated directly from postgres, as any submitted report (not just by completing a task) could represent a household visit, so it's not directly related to this new landing page. 


Thanks for the feedback!

**Comment by helizabetholsen** [comment] 2021-08-02 17:03
These are great questions @dianabarsan! I have some answers below :) 

I have some questions about metrics to track:

> Number of tasks completed per household in one visit


_If we choose to track this directly from code - for example count how many tasks were submitted for one household before the user navigates away from the landing page to submit a different task - we could get incorrect metrics if the user navigates away and then comes back and continues to submit tasks for this household._

**I see your point and agree that it might make more sense to configure this in Postgres! Looping in @yrimal for his thoughts here. **

_Is it possible to track this directly from postgres? For example query for tasks that were updated to get the completed state in one household within one day (? I suppose that's what counts for "one visit" for one household).
Otherwise, we'd probably have to do something similar in code when we record telemetry at the beginning of next day, to get correct numbers._

> Number of outstanding tasks in household after visit


_Same applies for this, we'd need a daily count for this to be accurate. Otherwise random navigation would skew the numbers._

**I agree, this makes sense!**

> Use case break down


_I'm not sure I understand what this means._

**This means is this an ANC task, PNC, etc. it would be great to know this in case there are clusters of tasks that are completed or not during household visits. I'm particularly interested in common tasks that might not be completed, ie. family planning**

> Total number of household tasks


_Is this just "visible" tasks? Should this also include: canceled, failed, or future tasks?_

**This should include canceled, failed and future tasks ideally**

> Number of cancelled tasks


_Is this per household?_

**Yes**

> Frequency of household visits


_We already track when tasks are submitted in telemetry. Would it be helpful if we track the specific "place" that was visited in the telemetry value that we store (that would increase the size of the telemetry document that replicates to the server)?_
_This could be calculated directly from postgres, as any submitted report (not just by completing a task) could represent a household visit, so it's not directly related to this new landing page._

**I'm comfortable with calculating this in postgres but want to check with @yrimal to ensure this is feasible across projects**

Thanks for the feedback!

**Comment by dianabarsan** [comment] 2021-09-08 08:49
This is ready for AT on `5886-task-improvements`. 

Implementation details: 
- the landing page is only displayed to users that have "can_view_tasks_group" permission. If users are missing the permission, the page is not displayed. Default config is updated to grant this permission to the "chw" role.
- the landing page is only displayed after submitting a task. Routing to the URL manually or using browser history won't display the page, and instead redirect to the task list page. 
- depending on the last submitted task, the page displays tasks that are "Ready" and that belong to the same leaf type place as the last submitted task's owner contact. If no tasks are found or a leaf type place was not found in the contact's lineage, the page is not displayed.
For example (with default hierarchy), submitting a task about a:
a) `person` contact that belongs to a `clinic`, will display all "Ready" tasks that belong to the clinic or any person belonging to the clinic
b) `clinic` contact, will display all ready tasks for that clinic or any person belonging to the clinic
c) `person` contact that belongs to a `health_center`, will not display the page
d) `health_center` contact, will not display the page
- if the page should be displayed (user has permission, contact belongs to or is leaf type place), but all tasks are completed, the page is not displayed and the snackbar should say "All household tasks completed".
- when the page is displayed, navigating away from the page to either: a) another unrelated page (like contacts or reports) or b) a task that is NOT from the same leaf type place, the user should see a modal to confirm navigation, similar to the form edited popup but with different text. The modal should work the same as the form modal, with cancel keeping the user on the page and confirmation navigating away.
If the user navigates to a task that is from the same leaf type place - whether the click is in the LHS or RHS list, the page should redirect to the task directly, without a modal.
- the tasks displayed on the page should be identical to the ones displayed on the contact page of the place, including the styling
- For performance reasons (so the user isn't stuck in a loading screen for many seconds while waiting to display tasks), the page uses the tasks that are stored for the tasks list (main component), and cherry picks which tasks to display based on the previous task's contact. This list can become stale between recalculations - this behavior already exists in the tasks list. Also, the list will exclude the last submitted task. The tasks are re-cherry picked every time the main task list is updated.
- Also for performance reasons, the associated leaf type place is "preloaded" into the store by the task content component, after the form has been rendered (while the database has downtime).

https://user-images.githubusercontent.com/35681649/132477764-52c4c35f-4de6-4e26-a287-77cd8585c752.mp4

Recorded telemetry when loading the page:

- tasks:group:all-tasks - total number of tasks for the place, all statuses
- tasks:group:cancelled - number of cancelled tasks for the place
- tasks:group:ready - number of tasks in "Ready" state
- tasks:group:ready:<task_title> - breakdown of "Ready" tasks by task task_title
- tasks:group:modal:confirm - when the user confirms the navigation modal
- tasks:group:modal:reject - when the user rejects the navigation modal
- rules-engine:tasks-breakdown:some-contacts - when fetching tasks counts in the tasks group page

Documentation PR pending.

**Comment by ngaruko** [comment] 2021-09-14 06:11
Tested on local


1. tasks group landing page displayed on task completion 
![image](https://user-images.githubusercontent.com/6979995/133198548-45ad5969-b892-4954-ba99-483fd0a8b233.png)


2. modal displayed when clicking on a task from another group 
![image](https://user-images.githubusercontent.com/6979995/133199010-0026f833-56fd-48d7-b5ef-7bc4ef5a0307.png)

3. not display modal when clicking list task from same group
4. Page not shown when there are no more household tasks 
![image](https://user-images.githubusercontent.com/6979995/133199275-f818d042-4314-4f67-93c0-300d80baa9a0.png)

5. Page not displayed when submitting task for contact with no leaf type place in lineage 
![image](https://user-images.githubusercontent.com/6979995/133199371-221f3266-03e5-4988-bd12-e1cda722b800.png)

6. supervisor user - task landing page not displayed after task completion

**Comment by dianabarsan** [comment] 2021-09-14 13:35
Merged to `master`.

**Closed by dianabarsan** 2021-09-14 13:35 UTC
Labels: Type: Feature, Tasks, Priority: 2 - Medium
