### ISSUE TITLE
Confirmation prompt for "Cancel" button in forms

### ISSUE THREAD

**Issue by gkesh** [medic/cht-core#7910] opened 2022-11-16 17:36 UTC
**Problem Statement**
A recent implementation of CHT has yielded a lot of feedback and one of the most popular among them is accidental cancellation of forms. When filling the forms, particularly long ones, users have noted that due to accidental presses they get exited out of a partially filled form quite often. This has resulted in considerable delays during form submissions and extreme inconvenience for the people being surveyed.

**Solution**
A prompt requesting confirmation whether the user really intends to exit out of the form or not. A simple popup with "yes" or "no" option could save a lot of time for both the users and the patients.

**Concept Screenshots**
|||
| --| -- |
| ![Screenshot from 2022-11-16 23-00-36](https://user-images.githubusercontent.com/27612533/202252311-043bb66f-e935-4aac-9c9f-4a8eea512be0.png) | ![cancel-concept](https://user-images.githubusercontent.com/27612533/202252591-7ca5f36a-e116-4b5b-a408-0d1945ebd6d0.png) |

**Comment by garethbowen** [comment] 2022-11-16 19:50
@gkesh Thanks for raising this issue. There is already an exit confirmation dialog which should show so this may be a bug.

Firstly, which version of CHT Core is deployed?

Secondly, can you provide reproduction steps, for example, are you clicking the `x` at the top of the form, using a phones back button, etc?

**Comment by gkesh** [comment] 2022-11-22 06:52
I am using version 3.17.0 (November 1) and this can be reproduced using a mobile interface as shown in the images. The detailed version of it would be the following:

**Comment by garethbowen** [comment] 2022-11-22 22:41
@gkesh Thanks for the update. I tried reproducing this with 3.17.0 in a browser and the confirm dialog showed up for me:

![Screenshot from 2022-11-23 11-40-04](https://user-images.githubusercontent.com/2064938/203435861-260ff76d-1848-4051-b0c1-612484cb5b6a.png)

What "Web browser emulator" are you using?

Have you got a dev instance I can try to replicate this error on?

**Comment by gkesh** [comment] 2022-12-09 09:58
This is an issue I ran into with the android app, maybe I am in wrong repo but the issue still persists on my end. @garethbowen I was wondering if you could look into it because this seems to be a major issue plaguing users on our side as our forms are specially long. Sadly, since all the data and forms on our active test instances are confidential, I cannot help on that end. However, I was able to replicate the same behavior on a simple sample form running on the default configuration. I was using the app on a Pixel 4a instance of the AVD Android Emulator on Android Studio.

Please keep in mind the error can only be replicated on the CHT Android app.

**Comment by garethbowen** [comment] 2022-12-11 23:05
@gkesh My colleague @michaelkohn managed to reproduce this when starting from the Contacts tab (as opposed to the Reports tab as in my instructions above). I've reclassified this as a bug and will dig into it this week.

**Comment by garethbowen** [comment] 2022-12-12 01:58
Curiously I can reproduce it with the "death report" form but not the "covid-19 assessment" form...

**Comment by garethbowen** [comment] 2022-12-12 10:56
Ok, here's what I have so far.

1. With the "death report" form (included below) on demo-cht I can reliably reproduce the error on all devices on 3.17.0 and 4.1.0.
2. By adding breakpoints to the enketo-core library I found that the edited event fires before our Enketo service registers the event listener, which means our state is never notified.
3. The enketo-core library only fires that event the first time the form is edited so no matter what the user does the warning is never shown.
4. In the "death report" form on demo-cht there is this line with `calculate="today()"`. If I remove this line, then everything works as expected.
5. In our Enketo service we have a `forceRecalculate` function with a line `form.calc.update();` which updates all the calcs before the event listeners are registered. If I comment out that line then everything works as expected. This was introduced as a fix for #3870

One workaround would be to modify the form to not use `now()` or `today()` if possible.

An ideal solution would be to remove the forceRecalculate as it's possible it's no longer needed in the updated enketo-core.

If that's not possible we could register the listeners before calling forceRecalculate but that might cause the form to always be dirty. This would be preferable to the current situation but still not ideal.

```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>Death report</h:title>
    <model>
      <itext>
        <translation lang="en">
          <text id="/death_report/death_details/date_of_death:jr:constraintMsg">
            <value>Date of death can only be from today up to 1 year ago.</value>
          </text>
          <text id="/death_report/death_details/date_of_death:label">
            <value>Date of Death</value>
          </text>
          <text id="/death_report/death_details/death_information:label">
            <value>Provide any relevant information related to the death of <output value=" /death_report/patient_name "/>.</value>
          </text>
          <text id="/death_report/death_details/place_of_death:label">
            <value>Place of death</value>
          </text>
          <text id="/death_report/death_details/place_of_death_other:label">
            <value>Specify other</value>
          </text>
          <text id="/death_report/death_details:label">
            <value>Death details</value>
          </text>
          <text id="/death_report/group_review/r_death_info:label">
            <value>&lt;div style=&quot;text-align:center;&quot;&gt;Relevant Information: <output value=" /death_report/death_details/death_information "/>&lt;/div&gt;</value>
          </text>
          <text id="/death_report/group_review/r_followup:label">
            <value>Follow Up&lt;i class="fa fa-flag"&gt;&lt;/i&gt;</value>
          </text>
          <text id="/death_report/group_review/r_followup_note:label">
            <value>A death confirmation task will show immediately.</value>
          </text>
          <text id="/death_report/group_review/r_key_instruction:label">
            <value>&lt;b&gt;Important Information&lt;/b&gt;&lt;i class="fa fa-warning"&gt;&lt;/i&gt;</value>
          </text>
          <text id="/death_report/group_review/r_patient_details:label">
            <value>&lt;div style=&quot;text-align:center;&quot;&gt;<output value=" /death_report/patient_name "/>
<output value=" /death_report/group_review/c_patient_age "/>
Date of Death: <output value=" /death_report/death_details/date_of_death "/>&lt;/div&gt;</value>
          </text>
          <text id="/death_report/group_review/r_referral:label">
            <value>&lt;b&gt;You will never be able to do any follow ups on <output value=" /death_report/patient_name "/> when you submit this death report.&lt;/b&gt;</value>
          </text>
          <text id="/death_report/group_review/r_summary_details:label">
            <value>Patient Details&lt;I class="fa fa-user"&gt;&lt;/i&gt;</value>
          </text>
          <text id="/death_report/group_review/submit:label">
            <value>&lt;h4 style="text-align:center;"&gt;To finish, be sure to click the Submit button.&lt;/h4&gt;</value>
          </text>
          <text id="/death_report/inputs/contact/_id:label">
            <value>What is the patient's name?</value>
          </text>
          <text id="/death_report/inputs/contact/date_of_birth:label">
            <value>Date of Birth</value>
          </text>
          <text id="/death_report/inputs/contact/name:label">
            <value>Name</value>
          </text>
          <text id="/death_report/inputs/contact/parent/parent/contact/name:label">
            <value>CHW name</value>
          </text>
          <text id="/death_report/inputs/contact/parent/parent/contact/phone:label">
            <value>CHW phone</value>
          </text>
          <text id="/death_report/inputs/contact/parent/parent/contact:label">
            <value>Contact</value>
          </text>
          <text id="/death_report/inputs/contact/parent/parent:label">
            <value>Parent</value>
          </text>
          <text id="/death_report/inputs/contact/parent:label">
            <value>Parent</value>
          </text>
          <text id="/death_report/inputs/contact/patient_id:label">
            <value>Patient ID</value>
          </text>
          <text id="/death_report/inputs/contact/sex:label">
            <value>Sex</value>
          </text>
          <text id="/death_report/inputs/contact:label">
            <value>Contact</value>
          </text>
          <text id="/death_report/inputs/source:label">
            <value>Source</value>
          </text>
          <text id="/death_report/inputs/source_id:label">
            <value>Source ID</value>
          </text>
          <text id="/death_report/inputs:label">
            <value>Patient</value>
          </text>
        </translation>
      </itext>
      <instance>
        <death_report delimiter="#" id="death_report" prefix="J1!death_report!" version="2018-11-28 06:42:06">
          <inputs>
            <meta tag="hidden">
              <location>
                <lat/>
                <long/>
                <error/>
                <message/>
              </location>
            </meta>
            <source>user</source>
            <source_id/>
            <contact>
              <_id/>
              <name/>
              <patient_id/>
              <date_of_birth>0</date_of_birth>
              <sex/>
              <parent>
                <parent>
                  <contact>
                    <name/>
                    <phone/>
                  </contact>
                </parent>
              </parent>
            </contact>
          </inputs>
          <source/>
          <source_id/>
          <patient_age_in_years>0</patient_age_in_years>
          <patient_age_in_months>0</patient_age_in_months>
          <patient_age_in_days/>
          <patient_uuid tag="hidden"/>
          <patient_id/>
          <patient_name/>
          <phase/>
          <t_death_confirmation/>
          <t_death_confirmation_date/>
          <death_details>
            <date_of_death/>
            <place_of_death/>
            <place_of_death_other/>
            <death_information/>
          </death_details>
          <group_review tag="hidden">
            <submit/>
            <r_summary_details/>
            <c_patient_age/>
            <r_patient_details/>
            <r_death_info/>
            <r_key_instruction/>
            <blank_note/>
            <r_referral/>
            <r_followup/>
            <r_followup_note/>
          </group_review>
          <meta tag="hidden">
            <instanceID/>
          </meta>
        </death_report>
      </instance>
      <instance id="contact-summary"/>
      <bind nodeset="/death_report/inputs" relevant="./source = 'user'"/>
      <bind nodeset="/death_report/inputs/source" type="string"/>
      <bind nodeset="/death_report/inputs/source_id" type="string"/>
      <bind nodeset="/death_report/inputs/contact/_id" type="db:person"/>
      <bind nodeset="/death_report/inputs/contact/name" type="string"/>
      <bind nodeset="/death_report/inputs/contact/patient_id" type="string"/>
      <bind nodeset="/death_report/inputs/contact/date_of_birth" type="string"/>
      <bind nodeset="/death_report/inputs/contact/sex" type="string"/>
      <bind nodeset="/death_report/inputs/contact/parent/parent/contact/name" type="string"/>
      <bind nodeset="/death_report/inputs/contact/parent/parent/contact/phone" type="string"/>
      <bind calculate="../inputs/source" nodeset="/death_report/source" type="string"/>
      <bind calculate="../inputs/source_id" nodeset="/death_report/source_id" type="string"/>
      <bind calculate="floor( difference-in-months(  /death_report/inputs/contact/date_of_birth , today() ) div 12 )" nodeset="/death_report/patient_age_in_years" type="string"/>
      <bind calculate="difference-in-months(  /death_report/inputs/contact/date_of_birth , today() )" nodeset="/death_report/patient_age_in_months" type="string"/>
      <bind calculate="floor(decimal-date-time(today()) - decimal-date-time( /death_report/inputs/contact/date_of_birth ) )" nodeset="/death_report/patient_age_in_days" type="string"/>
      <bind calculate="../inputs/contact/_id" nodeset="/death_report/patient_uuid" type="string"/>
      <bind calculate="../inputs/contact/_id" nodeset="/death_report/patient_id" required="true()" type="string"/>
      <bind calculate="../inputs/contact/name" nodeset="/death_report/patient_name" type="string"/>
      <bind calculate="2" nodeset="/death_report/phase" type="string"/>
      <bind calculate="&quot;yes&quot;" nodeset="/death_report/t_death_confirmation" type="string"/>
      <bind calculate="today()" nodeset="/death_report/t_death_confirmation_date" type="string"/>
      <bind constraint="(decimal-date-time(.) &lt;= decimal-date-time(today()))
and floor(decimal-date-time(today()) - decimal-date-time(.)) &lt;= 365" jr:constraintMsg="jr:itext('/death_report/death_details/date_of_death:jr:constraintMsg')" nodeset="/death_report/death_details/date_of_death" required="true()" type="date"/>
      <bind nodeset="/death_report/death_details/place_of_death" required="true()" type="select1"/>
      <bind nodeset="/death_report/death_details/place_of_death_other" relevant="selected(../place_of_death, 'other')" required="true()" type="string"/>
      <bind nodeset="/death_report/death_details/death_information" type="string"/>
      <bind nodeset="/death_report/group_review/submit" readonly="true()" type="string"/>
      <bind nodeset="/death_report/group_review/r_summary_details" readonly="true()" type="string"/>
      <bind calculate="if(../../patient_age_in_days &lt; 31, 
concat(../../patient_age_in_days, ' days old'),
if(../../patient_age_in_months &lt; 12, 
concat(../../patient_age_in_months, ' months old'), 
concat(../../patient_age_in_years, ' years old')))" nodeset="/death_report/group_review/c_patient_age" type="string"/>
      <bind nodeset="/death_report/group_review/r_patient_details" readonly="true()" type="string"/>
      <bind nodeset="/death_report/group_review/r_death_info" readonly="true()" relevant=" /death_report/death_details/death_information  != ''" type="string"/>
      <bind nodeset="/death_report/group_review/r_key_instruction" readonly="true()" type="string"/>
      <bind nodeset="/death_report/group_review/blank_note" readonly="true()" type="string"/>
      <bind nodeset="/death_report/group_review/r_referral" readonly="true()" type="string"/>
      <bind nodeset="/death_report/group_review/r_followup" readonly="true()" type="string"/>
      <bind nodeset="/death_report/group_review/r_followup_note" readonly="true()" type="string"/>
      <bind calculate="concat('uuid:', uuid())" nodeset="/death_report/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body class="pages">
    <group appearance="field-list" ref="/death_report/inputs">
      <label ref="jr:itext('/death_report/inputs:label')"/>
      <group ref="/death_report/inputs/contact">
        <label ref="jr:itext('/death_report/inputs/contact:label')"/>
        <input appearance="db-object" ref="/death_report/inputs/contact/_id">
          <label ref="jr:itext('/death_report/inputs/contact/_id:label')"/>
        </input>
        <group ref="/death_report/inputs/contact/parent">
          <label ref="jr:itext('/death_report/inputs/contact/parent:label')"/>
          <group ref="/death_report/inputs/contact/parent/parent">
            <label ref="jr:itext('/death_report/inputs/contact/parent/parent:label')"/>
            <group ref="/death_report/inputs/contact/parent/parent/contact">
              <label ref="jr:itext('/death_report/inputs/contact/parent/parent/contact:label')"/>
            </group>
          </group>
        </group>
      </group>
    </group>
    <group appearance="field-list" ref="/death_report/death_details">
      <label ref="jr:itext('/death_report/death_details:label')"/>
      <input ref="/death_report/death_details/date_of_death">
        <label ref="jr:itext('/death_report/death_details/date_of_death:label')"/>
      </input>
      <select1 ref="/death_report/death_details/place_of_death">
        <label ref="jr:itext('/death_report/death_details/place_of_death:label')"/>
        <item>
          <label>Health facility</label>
          <value>health_facility</value>
        </item>
        <item>
          <label>Home</label>
          <value>home</value>
        </item>
        <item>
          <label>Other</label>
          <value>other</value>
        </item>
      </select1>
      <input ref="/death_report/death_details/place_of_death_other">
        <label ref="jr:itext('/death_report/death_details/place_of_death_other:label')"/>
      </input>
      <input appearance="multiline" ref="/death_report/death_details/death_information">
        <label ref="jr:itext('/death_report/death_details/death_information:label')"/>
      </input>
    </group>
    <group appearance="field-list summary" ref="/death_report/group_review">
      <input ref="/death_report/group_review/submit">
        <label ref="jr:itext('/death_report/group_review/submit:label')"/>
      </input>
      <input appearance="h1 yellow" ref="/death_report/group_review/r_summary_details">
        <label ref="jr:itext('/death_report/group_review/r_summary_details:label')"/>
      </input>
      <input ref="/death_report/group_review/r_patient_details">
        <label ref="jr:itext('/death_report/group_review/r_patient_details:label')"/>
      </input>
      <input ref="/death_report/group_review/r_death_info">
        <label ref="jr:itext('/death_report/group_review/r_death_info:label')"/>
      </input>
      <input appearance="h1 blue" ref="/death_report/group_review/r_key_instruction">
        <label ref="jr:itext('/death_report/group_review/r_key_instruction:label')"/>
      </input>
      <input ref="/death_report/group_review/blank_note"/>
      <input appearance="h1 red" ref="/death_report/group_review/r_referral">
        <label ref="jr:itext('/death_report/group_review/r_referral:label')"/>
      </input>
      <input appearance="h1 green" ref="/death_report/group_review/r_followup">
        <label ref="jr:itext('/death_report/group_review/r_followup:label')"/>
      </input>
      <input ref="/death_report/group_review/r_followup_note">
        <label ref="jr:itext('/death_report/group_review/r_followup_note:label')"/>
      </input>
    </group>
  </h:body>
</h:html>
```

**Comment by jkuester** [comment] 2022-12-12 22:05
To build on what @garethbowen is saying, I think using the `now()` or `today()` functions in a `calculation` is causing Enketo to set the value for these `calculate`s _as soon as the form is loaded by Enketo_.  And that is before we actually get the listener registered.  Normally an `edit` event would be fired as soon as the user enters input into a form and we register the edit listener _before_ displaying the form to the user to catch that event being fired.  The problem here is that Enketo, itself, is triggering the event in some cases when calculating the value for the `calculate`.  Also, to be clear, it is the listener for the edit event that controls whether or not the dialog should be shown when the user tries to close the form (if there was no input to the form, it should close without popping the dialog).  

I am very curious as to what could have caused this regression in `3.17` :thinking: (or perhaps it was broken in some previous versions as well...).

- Removing `form.calc.update();` is an interesting idea!
	- I would not be surprised if this code is unnecessary in `4.x` with the new version of Enekto. They changed _a lot_ of the internals for handling random stuff like this to make it work better. So #3870 might not even be a problem anymore
	- That does not really help, though, for `3.17`...
- Registering the listener earlier also seems like a viable idea
  - However, if this ends up meaning that _every form_ will always be dirty then it seems like we might as well drop the `edit` listener logic altogether....

**Comment by garethbowen** [comment] 2022-12-12 23:23
> I am very curious as to what could have caused this regression in 3.17 thinking (or perhaps it was broken in some previous versions as well...).

I think it probably regressed a long time ago, but because it fails silently we didn't notice.

**Comment by garethbowen** [comment] 2022-12-12 23:52
I've run out of time to ship this before my vacation so I've asked @jkuester to look after it while I'm away.

**Comment by jkuester** [comment] 2022-12-14 18:54
I am not sure about the exact cause of this behavior, but I have observed that another work-around when your form has `calculate="today()"` would be replace that with `calculate="date(decimal-date-time(today()))"`.  The end result should be the same value, but apparently nesting it in the `decimal-date-time` conversion is enough to get Enketo to delay the calculation until user input actually happens...

**Comment by garethbowen** [comment] 2022-12-15 00:47
> is enough to get Enketo to delay the calculation until user input actually happens...

I have a theory that it's not about delaying the calculation, but certain functions marking the form edited and some not. Something like, every time you call `today()` you get a different value so enketo calls the edited listener, but if you convert it to a different type and the result is equal to the previous value, then the edited listener isn't called.

**Comment by jkuester** [comment] 2022-12-15 16:38
Yes!  You are correct!  I have been able to confirm that this behavior is caused by the fact that Enketo recalculates the values of `calculate` fields two [different](https://github.com/enketo/enketo-core/blob/561d832905bcc3eb98bdd1ee1a7beee551eb34d0/src/js/form.js#L342) [times](https://github.com/enketo/enketo-core/blob/561d832905bcc3eb98bdd1ee1a7beee551eb34d0/src/js/form.js#L419) when initializing a form.  If the value for one of the calculations changes between these calls, then an `edited` event is triggered during for initialization.  

The reason the `decimal-date-time` workaround works is because the value produced by that function is rounded to ~12 decimal places and as long as the form inits fast enough, the time between the calc calls is not enough to cause the values to actually be different....

Also, just want to note that this is not a new issue.  This behavior has existed at least since `3.9`.

**Comment by jkuester** [comment] 2022-12-15 22:36
After some additional testing, I have confirmed that the extra call to `form.calc.update()` is still needed (even in `4.x`) to address https://github.com/medic/cht-core/issues/3870.  So, removing that call is probably not the best option.  

So far, the most simple solution (for both `3.x` and `4.x`) that I have found is just to update the `renderFromXmls` function in the enekto service to set `this.currentForm.editStatus = false;` after `forceRecalculate` is called.  This will cause the `edited` event to be re-triggered when the user actually interacts with the form.

**Comment by jkuester** [comment] 2022-12-21 16:39
@medic/quality-assurance this is ready for AT on from [7910_cancel_dialog](https://github.com/medic/cht-core/tree/7910_cancel_dialog).  To recreate the behavior, you can load up this form:

```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms">
  <h:head>
    <h:title>Enketo Widgets</h:title>
    <model>
      <itext>
        <translation lang="en">
          <text id="/enketo_widgets/name:label">
            <value>Name</value>
          </text>
        </translation>
      </itext>
      <instance>
        <enketo_widgets id="enketo_widgets" prefix="J1!enketo_widgets!" delimiter="#" version="2022-12-20 00:00:00">
          <name/>
          <today/>
          <meta tag="hidden">
            <instanceID/>
          </meta>
        </enketo_widgets>
      </instance>
      <instance id="contact-summary"/>
      <bind nodeset="/enketo_widgets/name" type="string"/>
      <bind nodeset="/enketo_widgets/today" type="string" calculate="now()"/>
      <bind nodeset="/enketo_widgets/meta/instanceID" type="string" readonly="true()" calculate="concat('uuid:', uuid())"/>
    </model>
  </h:head>
  <h:body class="pages">
    <input ref="/enketo_widgets/name">
      <label ref="jr:itext('/enketo_widgets/name:label')"/>
    </input>
  </h:body>
</h:html>
```

- Open the form
- Type something in the "Name" field
- Tap the "Cancel" button

A dialog _should_ pop up asking if you really want to cancel the form.  However, due to the bug, that dialog will not display for this form.

**Comment by tatilepizs** [comment] 2023-01-02 17:21
### Test Details

**Config:** Default
**Platform:** WebApp
**Browser:** Chrome

---

### Reproducible on `Master`

**Environment:** Local - [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:master/docker-compose/cht-core.yml) and [cht-couchdb.yml](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:master/docker-compose/cht-couchdb.yml).

Using the form provided in the [previous comment](https://github.com/medic/cht-core/issues/7910#issuecomment-1361645519) the confirmation pop-up was **not displayed** when the cancel button was pressed.

<details>
<summary>Video attached</summary>

[video](https://user-images.githubusercontent.com/94494491/210261800-a244f251-db89-4cc3-bfb8-5eadbf84a0c5.mov)

</details>


### Fixed on `7910_cancel_dialog`

**Environment:** Local using [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7910_cancel_dialog/docker-compose/cht-core.yml) and [cht-couchdb.yml](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:7910_cancel_dialog/docker-compose/cht-couchdb.yml)

Using the form provided in the [previous comment](https://github.com/medic/cht-core/issues/7910#issuecomment-1361645519) the confirmation pop-up **was successfully displayed** when the cancel button was pressed and the form was incomplete.

<details>
<summary>Video attached</summary>

[video](https://user-images.githubusercontent.com/94494491/210262335-0222ca97-4cdc-46f2-ba31-9cbb8a08bee5.mov)

</details>

---

Test passed successfully. :tada:

**Closed** 2023-01-04 14:26 UTC
Labels: Type: Bug, Affects: 4.0.0, Affects: 3.16.0, Affects: 3.13.0, Affects: 3.14.0, Affects: 3.14.1, Affects: 3.11.0, Affects: 3.11.1, Affects: 3.11.2, Affects: 3.11.3, Affects: 3.12.0, Affects: 3.12.1, Affects: 3.14.2, Affects: 3.15.0, Affects: 3.17.0, Affects 4.0.1, Affects 3.16.1, Affects 3.17.1, Affects: 4.1.0, Affect: 3.10.0

**Comment by garethbowen** [comment] 2023-01-26 03:35
> which milestones should we target with this issue?

@jkuester Do you mean, should we backport this to previous versions? I'm tempted to not backport it as while it's annoying to users, it's not strictly blocking them from their work. What do you think?

**Comment by jkuester** [comment] 2023-01-26 16:09
@garethbowen yes, that is what I was wondering.  I agree that this does not really need to be back-ported unless someone asks for it.
