### ISSUE TITLE
Allow users to report client-side crashes via screenshots

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#8039] opened 2023-01-19 19:23 UTC
**What feature do you want to improve?**
Currently when a CHT application causes a crash, the user sees a basic error message with no actionable in distinguishable details.
![image](https://user-images.githubusercontent.com/9014751/213537506-df9be9ad-f1f4-4ae0-847e-391802b4478c.png)

Although the details of the crash are recorded via feedback documents - it would sometimes be useful for users to report their users via screenshot. 

Example: an app developer in an offline context is working beside a user who experiences a crash.
Example: a user experiences a crash which cannot be found in feedback docs
Example: an app developer is asked to help fix crashes in an app where they don't have access.

**Describe the improvement you'd like**
It'd be great if the crashing stack was hidden by default but the user could choose to view it. 
![image](https://user-images.githubusercontent.com/9014751/213540367-aa73ea68-90c0-49b1-b267-3b600fcd2e16.png)

Clicking details could show some details would would allow an app developer to fix the problem:
![image](https://user-images.githubusercontent.com/9014751/213541514-511f9aab-f998-419f-ae01-647a07f1108c.png)

I'm not sure what will realistically fit in a screenshot - but it might also be valuable to include:

* top of crash stack
* instance url
* username
* current date time
* last successful sync time

**Comment by kennsippell** [comment] 2023-01-19 19:34
I also think we should remove `reload` or replace it with `sync`. I'm unclear if reloading ever solves the problem? What users should be doing to resolve this is communicating and syncing fixes.

**Comment by dianabarsan** [comment] 2023-01-23 09:51
> I'm unclear if reloading ever solves the problem? 

I believe reloading was an acceptable solution in the past, when tasks were calculated in memory. Reloading would be like a complete try again action, in case the error was transitory. 

In the current context, I agree that sync-ing is probably a better action to take. One scenario where reloading might help and syncing would not is when the error is caused by views not being up to date and internal requests timing out.

**Comment by jonathanbataire** [comment] 2023-02-24 07:23
Hey @n-orlowski could you look at some mock ups weve have for this :) Thanks cc @kennsippell 
![Screenshot from 2023-02-24 10-09-34](https://user-images.githubusercontent.com/32832540/221116627-ce420097-685a-47dc-aa79-727b032a40d4.png)
![Screenshot from 2023-02-24 10-09-19](https://user-images.githubusercontent.com/32832540/221116662-5799de85-f21c-477b-860a-d5c952141539.png)
![i1](https://user-images.githubusercontent.com/32832540/221116944-de1ad95a-cdec-42d3-ae15-8e82d7cf3cb0.png)

![i2](https://user-images.githubusercontent.com/32832540/221117067-c70eff31-42ee-4c30-8965-88824fbfdd5f.png)
![i4](https://user-images.githubusercontent.com/32832540/221117164-0092586c-c45e-435b-9b7c-131253dc005a.png)
![i5](https://user-images.githubusercontent.com/32832540/221117254-12e38a31-708e-4fb2-9f4d-5d64e4f9e0c2.png)

**Comment by kennsippell** [comment] 2023-02-24 09:03
Hey @jonathanbataire Were you going to include other information in the screenshot also? Or just the crash stack? We had spoke about including: 

- top of crash stack
- instance url
- username
- current date time
- last successful sync time

**Comment by jonathanbataire** [comment] 2023-02-24 09:14
> Hey @jonathanbataire Were you going to include other information in the screenshot also? Or just the crash stack? We had spoke about including:
> 
> * top of crash stack
> * instance url
> * username
> * current date time
> * last successful sync time

All this info is there
No full crash stack trace though just the top bit of it i can make it get more

**Comment by kennsippell** [comment] 2023-02-24 09:21
Apologies.  Can we format it a little and only put code in the `<code>` tag?
Why not include as much stack as we can? Like put it at the bottom after the other information and let it overflow off the bottom of the page (but just maybe no scrolling so the screenshot is always at the top)?

**Comment by n-orlowski** [comment] 2023-03-01 02:16
Hiya! Is there a reason to keep the details hidden within the link? IMO it would be more straightforward to see the error message expanded (+1 for formatted list for ease of readability) and a single link to reload or sync

**Comment by jonathanbataire** [comment] 2023-03-10 08:56
@n-orlowski how is this? Its been tweaked a bit to hav the error message at the bottom where it's allowed to overflow
![Screenshot from 2023-03-10 11-52-10](https://user-images.githubusercontent.com/32832540/224269731-349353fc-0354-4d6d-ab87-c3c029189bfc.png)

**Comment by n-orlowski** [comment] 2023-03-10 18:26
Looks good! Small tweaks could be to move the Reload link to be right aligned (usually where a user would close / exit) and to add a bit more padding above/below the list items to make the label title and content more clearly grouped

**Comment by jonathanbataire** [comment] 2023-03-13 13:07
@n-orlowski 
![Screenshot from 2023-03-13 16-04-21](https://user-images.githubusercontent.com/32832540/224710051-0dcae201-125c-4926-9d15-d02d66b9f5a6.png)

**Comment by n-orlowski** [comment] 2023-03-14 00:27
Awesome!

**Comment by garethbowen** [comment] 2023-08-10 21:24
@jonathanbataire Thanks for this! Now that the PR is merged, is work complete, or is there more to do on this?

**Comment by jonathanbataire** [comment] 2023-08-11 05:06
> @jonathanbataire Thanks for this! Now that the PR is merged, is work complete, or is there more to do on this?

@garethbowen no, that should be it

**Comment by jonathanbataire** [comment] 2023-08-11 05:27
oh we'll need to add this for contacts so i guess still open @garethbowen

**Comment by garethbowen** [comment] 2023-08-13 18:47
@jonathanbataire So it's clear what was fixed in each release it would be better to have two issues. Would you mind creating a new issue for contact summary?

**Closed by garethbowen** 2023-08-13 18:47 UTC
Labels: Type: Improvement
