### ISSUE TITLE
Upgrade to latest  CouchDB (>=3.4.2)

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#9574] opened 2024-10-22 23:52 UTC
**Is your feature request related to a problem? Please describe.**
CHT Core is looking to [bifurcate online and offline search](https://github.com/medic/cht-core/issues/9542) which will leverage features in the latest version of couch.  We're [currently on](https://github.com/medic/cht-core/blob/e8e49181fb4f9b2f946452a245e2177680df1913/couchdb/Dockerfile#L1) couch `3.3.3` which doesn't have the latest features.

**Describe the solution you'd like**
As  CouchDB has released a [new version](https://docs.couchdb.org/en/latest/whatsnew/3.4.html#version-3.4.2) `3.4.2` which has improvements, including a stable version of Nouveau search, along with other features core would benefit from.  upgrading core ahead of the bifurcation would be great!

**Describe alternatives you've considered**
make tons of changes at once instead  of incrementally

**Comment by garethbowen** [comment] 2024-10-23 06:40
Duplicate of #9303 

Closing this one as that one has more info, but please feel free to add more specific details to that one!

**Closed by garethbowen** 2024-10-23 06:40 UTC
Labels: Type: Feature
