### ISSUE TITLE
Deleting primary contact from a place will retain that person as a contact when editing

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#6213] opened 2020-01-22 02:02 UTC
**Describe the bug**
After deleting the primary contact, the UI seems to look a little strange
**To Reproduce**

1. Create a new health center
2. Ensure there is a primary contact associated to the health center
3. Delete the person that is primary contact
4. Go back to the health center, click 'Edit'
5. a) there is a UUID in the dropdown 
   b) see the empty srting used as 'contact' in `Would you like to name the place after the primary contact: " 's Health Center"? `

![image](https://user-images.githubusercontent.com/6979995/72859113-9a4d5680-3d27-11ea-9f68-07c6ebddb395.png)

**Expected behavior**
The contact edit form should look like one created with no contact (skipped)
![image](https://user-images.githubusercontent.com/6979995/72859262-0b8d0980-3d28-11ea-8879-c598d2e1833b.png)

**Environment**
- Instance:  gamma.dev.medicmobile.org
- Browser:Firefox, Chrome
- Client platform: MacOS
- App: webapp
- Version: 3.8

**Comment by dianabarsan** [comment] 2020-01-22 06:37
@ngaruko can you please share which configuration you're using? Or which contact edit form you're using?

**Comment by ngaruko** [comment] 2020-01-22 06:54
@dianabarsan This happens on both `cht` (https://gamma-cht.dev.medicmobile.org/#/contacts/2cb01683-5ede-4aa7-8959-08382ccee74c/edit) and `standard` (https://gamma.dev.medicmobile.org/#/contacts/08aacf4d-711e-4fca-8237-1da212351b78/edit)

**Comment by dianabarsan** [comment] 2020-01-22 12:15
I think this has been a very long standing issue.

I found an instance running `3.5.0` (https://moh-zanzibar-testing.dev.medicmobile.org/#/contacts/5f075ed0-2d81-434f-bcae-403290a35bd9/edit) which displays the same behavior:
![image](https://user-images.githubusercontent.com/35681649/72891503-0b3b4100-3d1d-11ea-830d-315fbdffe300.png)
This instance uses the now-legacy generated xforms (https://github.com/medic/cht-core/blob/3.5.x/webapp/src/js/services/enketo-translation.js#L137) when editing this contact. 

Do we consider this a blocker for 3.8 ?

**Comment by ngaruko** [comment] 2020-01-23 02:45
@dianabarsan Definitely not a blocker and yes it has been that way for a while. Will move it to 3.9

**Comment by garethbowen** [comment] 2020-05-26 00:12
Moved to 3.12.0 to free up engineers to work on 3.11.0.

**Comment by mrsarm** [comment] 2021-06-21 12:04
Confirmed this continue to happen in `master` and in any kind of form, not just health center forms, and my assumption is that it also happens with any drop - down component that points to a reference that does not exist any more. E.g. here is a test with a _"Postnatal danger sign follow-up - baby"_ form, after create the report I deleted the patient, and going back to the report, when editing:

![Screenshot from 2021-06-21 08-58-11](https://user-images.githubusercontent.com/1608415/122758817-a1a3c700-d26f-11eb-8b11-b1b23157247d.png)

**Comment by mrsarm** [comment] 2021-06-29 20:06
This is not just a visual bug when the contact has been deleted but also when is not visible by the user, so discussing a PR with @dianabarsan about it , we think that leave the label empty why preserving the value may be confusing, so the proposal is to set a default label `[Deleted]` when we know the record was deleted, and `[Not available]` when the contact info is not available or may be deleted by other user but we cannot infer that the record was removed.

Deleted:

![Contact Deleted](https://user-images.githubusercontent.com/1608415/123860142-e5e03880-d8fb-11eb-92eb-c669a111974d.png)

Not available:

![Contact not available](https://user-images.githubusercontent.com/1608415/123860180-f2fd2780-d8fb-11eb-9b0d-8ce0eb5274d9.png)

Either way if the user change the value, the record value change, if not, the original value is preserved.

What you think @michaelkohn @garethbowen ?

**Comment by garethbowen** [comment] 2021-06-29 21:29
I like this solution.

I think the labels and styling needs to be workshopped a little to make it more obvious, for example, instead of "Not available" I think we'd need to say something like "Unknown contact". For styling I think it would be clearer if the text were greyed out a little rather than surrounded by square brackets.

Please also make sure the value looks the same in the Reports content pane. I'm not sure how it looks but I'm guessing it'll show the UUID there too!

Please work with @n-orlowski to come up with text and styles that communicate the concept correctly.

**Comment by mrsarm** [comment] 2021-06-30 13:45
> I think the labels and styling needs to be workshopped a little to make it more obvious, for example, instead of "Not available" I think we'd need to say something like "Unknown contact". For styling I think it would be clearer if the text were greyed out a little rather than surrounded by square brackets.

Thanks @garethbowen , yes I'm not sure what exact message to use when the contact info is not available, "Unknown contact" sounds like an error, but "Not available" may be also interpreted like that too. My first thought was "Contact info not available", but maybe is too long. About the styling, I agree to change the style a bit, @n-orlowski could you help us to define the changes please? let me know if you need more context.

**Comment by n-orlowski** [comment] 2021-06-30 20:46
Chatted a bit with @mrsarm on this!

We have a [disabled state](https://docs.communityhealthtoolkit.org/design/components/#dropdowns) we can use for the input field

Some options for messaging:
- Invalid contact
- Unknown contact
- Contact removed
- Contact doesn't exist

However thinking more on this, we might be overcomplicating.. If the contact has been removed it might be less confusing to the user to show the empty field as per Bede's initial comment (and clearer that the desired action is to choose a new contact)

**Comment by dianabarsan** [comment] 2021-07-01 00:22
> less confusing to show the empty state as per Bede's initial comment

For offline users that are seeing places that have primary contacts that they can't see (but still exist), having the empty field might prompt them to edit it.

**Comment by n-orlowski** [comment] 2021-07-01 20:03
> For offline users that are editing places that have primary contacts that they can't see (but still exist), having the empty field might prompt them to edit it.

Ahh, I see and realize I misunderstood the scenarios, thanks!

So I think for online users, where we know for sure that a contact has been deleted, it would make sense to show the empty state. 

For offline users, where we are unsure, we should show the disabled (greyed out) text in the input field.

Some options for copy:
Unidentified contact
Unnamed contact
Hidden contact

**Comment by michaelkohn** [comment] 2021-07-02 11:48
If I understand correctly, the `_id` of the `person` is retained on related documents even after the `person` is deleted. So if you have a `chw_area` and delete the contact, it doesn't actually update the `contact` property on the `chw_area` document.  Is my understanding correct? 

With that in mind, it feels like by putting a special message in the dropdown we are actually just hiding bad data instead of preventing it from happening (it's still going to cause issues in analytics too).

Do we have any options to prevent this bad data situation in the first place? If yes, that would also solve the "i don't have access to the person" situation because you would know why the lookup couldn't be completed and could clearly state why the user can't see more detail. 

<img width="945" alt="Screen Shot 2021-07-02 at 1 32 27 PM" src="https://user-images.githubusercontent.com/10096985/124270149-19110a80-db3c-11eb-85bf-c9f14b0b5d56.png">

**Comment by dianabarsan** [comment] 2021-07-02 12:14
> just hiding bad data

Why would it be bad data? Is it bad because we don't "cascade" a deletion? For example: if you deleted a contact from your phone, would you expect all the SMSs that you received from that contact to also be deleted? Or something along those lines?

**Comment by michaelkohn** [comment] 2021-07-02 12:56
No, I wouldn't expect it to delete all the SMS' to that person, but I would expect it to remove their birthday reminder from my calendar so I don't have a bunch of entries like: "Today is 23423-235asdga-235-235-235's birthday!".  

So yes, I would expect it to elegantly handle documents that refer to the deleted document.  

I recognize it might be a costly operation and not worth it, but if it's easy, my preference would be to make it so that if there is an ID in a field that is supposed to refer to another document, I can safely assume that the other document will exist. If not, blank out the field.

**Comment by dianabarsan** [comment] 2021-07-02 12:59
The problem appears when you can't be certain that the document exists or not, because users can't see all docs.

**Comment by michaelkohn** [comment] 2021-07-02 13:05
If we update references to deleted docs, we _would_ know, right? (ie if there's an ID in the field but you don't have that doc on your phone, you would be able to assume that it's because you don't have access to it).

**Comment by mrsarm** [comment] 2021-11-15 18:30
Back to this after a long time frozen. I'll rebase the changes in the [PR](https://github.com/medic/cht-core/pull/7158) to see if still works. Then I'll change the wording as suggested by @garethbowen and @n-orlowski , and graying out the text in the component instead of the brackets surrounding the text.

My understanding about the discussion around update the reference is that it's unpractical and costly, and if we decide to implement that, we should analyze it more carefully in another issue, assessing better the impact.

CC @michaelkohn @dianabarsan

**Comment by mrsarm** [comment] 2021-12-10 20:11
Removing myself from the ticket and assigning it to @dianabarsan that will continue the work from here.

Anyway The PR https://github.com/medic/cht-core/pull/7158 is ready for AT, so moving the ticket to AT, and :crossed_fingers: Diana won't need to make any change further.

CC @jonathanvq

**Comment by ngaruko** [comment] 2021-12-12 22:30
**_on master_**: ![image](https://user-images.githubusercontent.com/6979995/145731570-5386a573-852d-44ba-8229-85186bd0b085.png)

_**Branch:**_
![image](https://user-images.githubusercontent.com/6979995/145731939-dd7d9998-64c7-431b-947c-46d4b2543c70.png)

Should be good to merge @dianabarsan

**Closed** 2021-12-14 08:22 UTC
Labels: Type: Bug, Priority: 2 - Medium
