### ISSUE TITLE
Race condition in unloading contact content

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7603] opened 2022-04-27 10:53 UTC
**Describe the bug**
Some feedback docs report this error: 

```
Uncaught (in promise): TypeError: Cannot read properties of null (reading '_id')
TypeError: Cannot read properties of null (reading '_id')
    at t.<anonymous> (https://host/main.js?_sw-precache=hash:1:3077223)
    at https://host/main.js?_sw-precache=hash:1:2623240
    at Object.next (https://host/main.js?_sw-precache=hash:1:2623345)
    at l (https://host/main.js?_sw-precache=hash:1:2622075)
    at p.value (https://host/polyfills.js:1:10189)
    at Object.onInvoke (https://host/main.js?_sw-precache=hash:1:2174490)
    at p.value (https://host/polyfills.js:1:10128)
    at p.value (https://host/polyfills.js:1:4280)
    at https://host/polyfills.js:1:21025
    at p.value (https://host/polyfills.js:1:10880)
```

This points to:  https://github.com/medic/cht-core/blob/52605ac752bb40ab61ee1198fd7fe1bc0fbef982/webapp/src/ts/modules/contacts/contacts-content.component.ts#L256 where we don't nullcheck for validity of `selectedContact` before accessing the _id property.

The feedback doc was reported (unanimously) on `/#/contacts`, and almost half of the instances seemed to be triggered soon after the app was opened. 

**To Reproduce**
TBD

**Expected behavior**
No errors. We should gracefully handle not having a selected contact or the selected contact being unloaded. 

**Logs**
As above. 

**Environment**
- Instance: live instance
- Browser: Webview? 
- Client platform: Android
- App: webapp
- Version: 3.14.x

**Comment by kennsippell** [comment] 2022-09-12 21:29
There are about 100 feedback docs/month due to this bug for production PiH instance.

**Comment by garethbowen** [comment] 2023-02-13 01:55
I couldn't figure out how to reproduce this. The only path to the line that throws the error is already null checked so it shouldn't be possible. However it's clear from the error message what the fix is, so to be on the safe side I've just added a null check.

**Comment by garethbowen** [comment] 2023-02-14 04:26
Ready for AT in `7603-null-check-contact`

**Comment by tatilepizs** [comment] 2023-02-21 22:50
Hi @garethbowen, what will be the correct way to test this ticket?

**Comment by garethbowen** [comment] 2023-02-21 22:54
Sorry I should have been more clear... I didn't manage to reproduce it myself (even with breakpoints and so on). If you wouldn't mind just smoke testing:

- selecting a contact
- deselecting them (selecting another or moving to another tab)
- muting a contact

I think that'll be sufficient.

**Comment by tatilepizs** [comment] 2023-02-22 17:56
Thank you for the details Gareth.
I did a smoke test using the branch `7603-null-check-contact` and create contacts, edit them, muted them, and created death reports, it and everything worked as expected.
So I think that we are good and we can just merge it 🎉

**Comment by garethbowen** [comment] 2023-02-22 20:47
Merged!

**Closed by garethbowen** 2023-02-22 20:47 UTC
Labels: Type: Bug
