### ISSUE TITLE
Search by first name does not filter report

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#6424] opened 2020-05-13 01:22 UTC
**Describe the bug**
The report is one of the test/demo data loaded by `medic-conf csv-to-docs upload-docs`. In the search, if one type the surname/last name, the report shows in the search. However, if the first name is used, no result shows. It seems to happen only on this particular report.

**To Reproduce**
1 - Launch medic on local host
2 - upload test data (`csv-to-docs upload-docs`)
3 - one report will be loaded (Pregnancy registration for `Adelia Akiyama`)

**Expected behavior**
Report should show with either first name or last name 
**Logs**
No logs in the console
**Screenshots**
![image](https://user-images.githubusercontent.com/6979995/81760916-a64e6580-951c-11ea-85c0-6d5aeaa7b732.png)

https://github.com/medic/cht-core/files/4618314/adelia.mov.zip
**Environment**
- Instance: localhost
- Browser:  Firefox, Chrome
- Client platform: MacOS
- App: webapp
- Version: (3.8.0, 3.9)

**Additional context**
It doesn't seem to happen with new created reports and it is not on this particular branch, but I thought it might be worth looking into.

**Comment by garethbowen** [comment] 2020-05-13 01:39
I think this is because the report has a field with "Adriana Akiyama". That is what is used for the search terms. We don't search over the contact name. If you search for "adri" it works as expected. It's just a bit of weird data making it look wrong.

We could either change the data to not use the same names as much, or we make this a feature request for the freetext search to query the contact name as well as the report fields.

**Comment by garethbowen** [comment] 2020-06-30 23:49
Closing as not a bug. We can consider improvements to search as a separate issue.

**Closed by garethbowen** 2020-06-30 23:49 UTC
Labels: Type: Bug
