### ISSUE TITLE
Flakey test: Purging on login Logging in as a restricted user with configured purge rules should perform a purge

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#5214] opened 2019-01-08 22:44 UTC
```
2) Purging on login Logging in as a restricted user with configured purge rules should perform a purge
  Message:
[31m    Expected true to be falsy.[0m
  Stack:
    Error: Failed expectation
        at uuids.forEach.uuid (/home/travis/build/medic/medic-webapp/tests/page-objects/reports/reports.po.js:15:94)
        at Array.forEach (<anonymous>)
        at Object.expectReportsToNotExist (/home/travis/build/medic/medic-webapp/tests/page-objects/reports/reports.po.js:14:11)
        at UserContext.it (/home/travis/build/medic/medic-webapp/tests/e2e/login/purge.spec.js:178:13)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1077:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2505:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2974:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:668:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:189:7)
```

cc @SCdF

**Comment by SCdF** [comment] 2019-01-09 16:22
Works for me :-(

Unfortunately the previously linked log no longer had an error in it (presumably because it was restarted?)

**Comment by SCdF** [comment] 2020-05-27 12:30
I haven't seen this in a very long time, so I'm going to close it. If anyone reproduces it feel free to reopen

**Closed by SCdF** 2020-05-27 12:30 UTC
