### ISSUE TITLE
4.x: Version deployed still visible in App Management release list

### ISSUE THREAD

**Issue by Marina-Kenf** [medic/cht-core#7953] opened 2022-12-02 13:04 UTC
**Describe the bug**
When you upgrade your instance to 4.x, you can still see the deployed version on the release list.

**To Reproduce**
1. Upgrade your instance to cht 4.x
2. Go to 'App management'
3. Click on 'Upgrades'

**Expected behavior**
See only releases after the one deployed

**Screenshots**
<img width="728" alt="image" src="https://user-images.githubusercontent.com/63068738/205298381-1edf72c5-0262-4c4a-a8d8-6cf11e60ca9c.png">

**Comment by dianabarsan** [comment] 2022-12-02 14:23
I believe this goes hand in hand with https://github.com/medic/cht-core/issues/7902 and https://github.com/medic/cht-core/issues/7901

**Comment by latin-panda** [comment] 2022-12-20 03:25
Related [forum post](https://forum.communityhealthtoolkit.org/t/docker-helper-cht-version/2356)

**Comment by dianabarsan** [comment] 2023-01-09 15:56
This should already be fixed by https://github.com/medic/cht-core/issues/7902

The root cause for this was an incorrect version tag (like `4.0.1-4.0.1.123456789`) which didn't match our version regex: https://github.com/medic/cht-core/blob/8e96ab03d51cf0b5c64632137ff0b6c417f1ec38/admin/src/js/services/version.js#L21

This way, calculating the next release was not possible (https://github.com/medic/cht-core/blob/8e96ab03d51cf0b5c64632137ff0b6c417f1ec38/admin/src/js/services/version.js#L6), therefore all releases were displayed. 

I'm tempted to keep this open and move this to `4.3.0`, when we can check if this is still the case. 
We _can_ test this now, that would require to publish releases to an alternative staging server (can be a local one) and checking if only the correct next releases appear.

**Comment by dianabarsan** [comment] 2023-01-26 08:07
This is ready for testing, again :D 

I have a simple solution to test while running cht-core as a developer: you have to export the user env variables in order to simulate a release outcome:

- export the unique build identifier 

```export BUILD_NUMBER=123```

- export TAG or BRANCH

```
export TAG=4.2.0 // for a release 
export TAG=4.2.0.beta-1 // for a beta
export BRANCH=1234-branch-name // for a branch
```

For a local build, which should display ALL possible upgrade options, don't export neigher TAG nor BRANCH.

**Comment by mrjones-plip** [comment] 2023-01-26 14:47
@dianabarsan  - do we need to account for [FR](https://docs.communityhealthtoolkit.org/core/releases/feature_releases/#initial-fr-installation)s?

**Comment by dianabarsan** [comment] 2023-01-26 14:52
Yea, and it already should, I'll update the comment to include instructions of how to simulate FRs.

**Comment by lorerod** [comment] 2023-02-22 15:22
**Environment:** MacOS 13.1 (22C65); Docker desktop 4.15.0 (93002)l; Docker engine: 20.10.21
**Reproduced**
**CHT 4.1.0:**  Local using docker compose files [cht-core.yml ](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.1.0/docker-compose/cht-core.yml) and [cht-couchdb.yml ](https://staging.dev.medicmobile.org/_couch/builds_4/medic:medic:4.1.0/docker-compose/cht-couchdb.yml)
I can still see the deployed and previous versions on the release list.
![Captura de pantalla 2023-02-20 a la(s) 15 21 47](https://user-images.githubusercontent.com/21312057/220651280-63259453-dd84-4e97-8b3f-dbd4f77b10bd.png)

**Fixed on branch**
**cht-core:**  Local using branch `7953-fix-upgrade-branches` and setting up with [developer environment](https://docs.communityhealthtoolkit.org/contribute/code/core/dev-environment/)

1. Latest release
- `export BUILD_NUMBER=123`
- `export TAG=4.1.0`

Expected behavior:
- [X] See only releases after the one deployed:
![Captura de pantalla 2023-02-22 a la(s) 11 33 59](https://user-images.githubusercontent.com/21312057/220659497-4c3a18b8-ad28-4945-ade4-01a1cfd2ead5.png)


2. Release
- `export TAG=4.0.1`

Expected behavior:
- [X] See only releases after the one deployed:
![Captura de pantalla 2023-02-22 a la(s) 11 50 48](https://user-images.githubusercontent.com/21312057/220659606-db7f1b04-0d0e-477d-8101-3434d460066f.png)

3. Beta
- `export TAG=4.0.1-beta.1`

Expected behavior:
- [X] See only releases after the one deployed:
![Captura de pantalla 2023-02-22 a la(s) 12 09 32](https://user-images.githubusercontent.com/21312057/220664159-4f733956-4c9e-4c86-9afc-5dde997ccc82.png)

4. Branch
- `unset TAG`
- `export BRANCH=1234-branch-name`
Expected behavior:
- [X]Should display all possible upgrade options:
![Captura de pantalla 2023-02-22 a la(s) 12 19 45](https://user-images.githubusercontent.com/21312057/220667242-1b0fe930-3438-44c0-b9e2-e4e5c9ceef4a.png)

**Comment by dianabarsan** [comment] 2023-02-24 08:25
Merged to `master`

**Closed by dianabarsan** 2023-02-24 08:25 UTC
Labels: Type: Bug, Affects: 4.0.0, Affects 4.0.1, Affects: 4.1.0
