### ISSUE TITLE
Report API startup progress instead of 502

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#2967] opened 2016-11-30 19:20 UTC
As we don't start API until all the migrations have completed users are greeted with a 502 error after update which makes it unclear whether they should wait or try and work out what went wrong.

Find some way to server an "API is starting" page instead. Ideally this would have some indication of progress (eg: "currently running xyz migration").

**Comment by SCdF** [comment] 2016-12-01 07:58
So when I do this locally and I boot too fast I don't get a 502, I get a 404. Maybe my timing is just different though.

**Comment by garethbowen** [comment] 2016-12-01 08:51
It's probably different via nginx?

**Comment by nice-snek** [comment] 2017-03-15 09:40
hi frand @browndav, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment] 2017-07-03 01:50
I've spiked this to see if it would just work, and it does. Something like this...

```js
const status = {};
app.listen(apiPort);
app.get('/status', (req, res) => res.json(status));
migrationsAndChecksAndSoOn().then(err => {
  status.error = err;
  if (!err) {
    registerAllListeners();
  }
});
```

**Comment by garethbowen** [comment] 2017-07-03 01:55
Unassigning this so anyone can work on it.

**Comment by garethbowen** [comment] 2017-07-03 02:00
This would also be useful for horticulturist (#3582) in the updating UI.

**Comment by garethbowen** [comment] 2021-07-25 18:05
Working on this is a good chance to remove the `medic-api` branding from the `/setup/poll` API, just be sure to update it in a backwards compatible way so as not to break [cht-android AppUrlVerifier](https://github.com/medic/cht-android/blob/master/src/main/java/org/medicmobile/webapp/mobile/AppUrlVerifier.java#L25).

**Comment by garethbowen** [comment] 2022-03-22 00:34
Assigned to @dianabarsan as I think this is part of the archv3 she's done/doing.

**Comment by dianabarsan** [comment] 2022-04-04 15:03
Relevant express comment: https://github.com/expressjs/express/issues/2596#issuecomment-81353034

**Comment by dianabarsan** [comment] 2022-10-13 07:03
This was resolved by starting API server sooner, but with a temporary router that responds only in a couple of ways: 
- `/api/v1/startup-progress` returns startup progress
- any request that wants JSON will get a 503 status and a `{ error: 'Service unavailable' }` body
- every other request will be served with an HTML page that displays startup progress

Because we wanted to make the startup page translatable and brandable, and translations and branding are saved in the database, we decided to only start the startup router after the database is online and we have translations and branding available. To summarise, the router starts after: database checks, uploading default docs and merging translations files. 

After API bootstrapping steps are done, the startup router is hot swapped with the original API router, and everything should work as before. 

The startup page looks like this: 

![image](https://user-images.githubusercontent.com/35681649/195522700-bdb17635-18bd-4de8-8e88-fae07e773335.png)

**Comment by dianabarsan** [comment] 2022-10-13 07:04
The steps are pre-determined and are: 
1. Installation checks. 
2. Installing - this only happens when installation checks failed. More about this below.
3. View indexing - this only happens when installation checks failed. 
4. Prepping config. 
5. Running migrations. 
6. Prepping forms. 

Steps 2 and 3 only appear if step 1 determins that the CHT needs installing. 
The method is to compare the bundled ddoc definitions with the ones that exist in the database. Every ddoc has a `version` property, and the version of every ddoc that is bundled with API (it's saved within the image) is compared to the version of the same ddoc that exists in the database. 
There are a couple of cases: 
1. A ddoc is missing entirely
2. A ddoc has a different version and the correct version is not staged
3. A ddoc has a different version and the correct version is staged

In cases 1. and 2. , a full instalation is started. In case 3, a partial installation is started. 

In all cases, "Installing" and "View indexing" will be visible in the startup page.

**Comment by dianabarsan** [comment] 2022-10-13 07:12
For JSON vs non-json requests. 
Once logged in, all APIs that the Webapp client uses request a JSON response. This means that the startup page should only be visible for users that are not logged it, and it serves the purpose of not displaying an ugly 503 empty HTML page that nginx would send by default. 
So you would not expect to see this page if you were logged in and openend a page in the webapp. 
However, every request that webapp makes would fail, because the router sends a 503. 

So, for AT, please make sure you check that the app behavior is correct when: 
- requesting / or any other path from a browser where you are not logged in
- being logged in as an online user and navigate in the app while the api is starting up. 
- being logged in as an offline user and navigate in the app while the api is starting up.
Please also try refreshing for both users.

**Comment by dianabarsan** [comment] 2022-10-13 07:17
To keep the startup page running for longer, so you can actually assess what is happening, you need a database of some size, enough that some startup steps begin to be time consuming, This will depend on your testing computer so I can't give specific numbers. 
What you can do is: 
1. Invalidate your install to trigger view indexing

steps: 
- edit a view in one of the ddocs. it doesn't have to be correct or make sense. 
- change the `version` property of the same ddoc. 
- query your view to start view indexing - wait for indexing to finish. 
- run view_cleanup to delete the indexes from the old correct view. 
- restart API. 
(because you changed the version, installation is invalid, and because your view is different, couch will index the correct view). 

2. Invalidate your migrations
- delete the `migration-log` document. 
- restart API

**Comment by lorerod** [comment] 2022-10-15 18:56
> The steps are pre-determined and are:
> 
> 1. Installation checks.
> 2. Installing - this only happens when installation checks failed. More about this below.
> 3. View indexing - this only happens when installation checks failed.
> 4. Prepping config.
> 5. Running migrations.
> 6. Prepping forms.
> 
> Steps 2 and 3 only appear if step 1 determines that the CHT needs installing. The method is to compare the bundled ddoc definitions with the ones that exist in the database. Every ddoc has a `version` property, and the version of every ddoc that is bundled with API (it's saved within the image) is compared to the version of the same ddoc that exists in the database. There are a couple of cases:
> 
> 1. A ddoc is missing entirely
> 2. A ddoc has a different version and the correct version is not staged
> 3. A ddoc has a different version and the correct version is staged
> 
> In cases 1. and 2. , a full installation is started. In case 3, a partial installation is started.
> 
> In all cases, "Installing" and "View indexing" will be visible in the startup page.

@dianabarsan Thank you for the detailed explanation. 
I'm trying to replicate 1. 2. and 3. but I do not see differences in the step executed. It is always doing a full install.
I think I'm not getting right the steps to reproduce 3. How can I ensure that the version I change in the ddoc is staged?

**Comment by lorerod** [comment] 2022-10-15 19:05
> For JSON vs non-json requests. Once logged in, all APIs that the Webapp client uses request a JSON response. This means that the startup page should only be visible for users that are not logged it, and it serves the purpose of not displaying an ugly 503 empty HTML page that nginx would send by default. So you would not expect to see this page if you were logged in and opened a page in the webapp. However, every request that webapp makes would fail, because the router sends a 503.
> 
> So, for AT, please make sure you check that the app behavior is correct when:
> 
> * requesting / or any other path from a browser where you are not logged in
> * being logged in as an online user and navigate in the app while the api is starting up.
> * being logged in as an offline user and navigate in the app while the api is starting up.
>   Please also try refreshing for both users.

@dianabarsan I'm testing all these scenarios, and when refreshing with an online user logged in, I get a 403 error code int the url while the startup is running, and when it finally is done, the first thing I get is an access denied error shown in the web app. After waiting a while I can use the web app without problems.
<details>
<summary>Video:</summary>

https://user-images.githubusercontent.com/21312057/196003724-cd29781c-f352-4ff6-bc24-1037b00a6659.mov


</details>

**Comment by dianabarsan** [comment] 2022-10-16 04:26
> I'm trying to replicate 1. 2. and 3. but I do not see differences in the step executed. It is always doing a full install.

You wouldn't be able to tell the difference. What you would see is that view indexing resumes, for example, instead of starting over.

**Comment by dianabarsan** [comment] 2022-10-16 04:33
Thanks for the updated @lorerod 
I'm going to add an update so the 403 redirect won't happen and the online user would directly end up on the initial page.

**Comment by dianabarsan** [comment] 2022-10-19 15:34
Hi @lorerod 

I have the changes that remove the 403 redirect in webapp in this branch: `2967-webapp-json-session`
- https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A2967-webapp-json-session/docker-compose/cht-couchdb.yml
- https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A2967-webapp-json-session/docker-compose/cht-core.yml

**Comment by lorerod** [comment] 2022-10-20 14:19
**Environment**
Client platform: MacOS
Browser: Chrome
App: api
Version: 4.0.0-alpha
Instance: Local using [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-core.yml) and [cht-couchdb.yml ](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-couchdb.yml) and [cht-couchdb-clustered.yml ](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-couchdb-clustered.yml)

**Scenarios Single node:**
1. Invalidate my install to trigger view indexing 

Steps to **prepare the scenario**:
- Log in as an online user 
- Go to database /_utils
- Select medic database
- Select Design Documents
- Edit a view in one of the design docs.
- Change the version property of the same design doc.
- Query the view to start view indexing - wait for indexing to finish.
- Log out
- Run view_cleanup to delete the indexes from the old correct view.
command:
`curl -H "Content-Type: application/json" -X POST "http://192-168-0-103.my.local-ip.co:5984/medic/_view_cleanup" -u medic:password`
response:
`{
    "ok": true
}`
-  In terminal run a command to monitor the JSON response
`while true;do clear;curl -sk https://localhost/api/v1/startup-progress |jq; sleep 1;done`

Steps to **execute the scenario**:
- Restart API.
- While the api is starting up request a webb app path from a browser where you are not logged in
- The Webb app shows the startup page 
<details>
<summary>Video:</summary>

https://user-images.githubusercontent.com/21312057/196963612-34b27c82-a633-4b27-be71-7e112fef6f11.mov

</details>

- Prepare the scenario with an online user and log out
- Log in as an offline user
- Restart API
- While the api is starting up navigate, refresh in the app
- The offline user is able to navigate and refresh
<details>
<summary>Video:</summary>

https://user-images.githubusercontent.com/21312057/196965735-83291bd2-311b-4945-b862-6127eb9c8ea0.mov

</details>

- Prepare the scenario with an online user
- Restart API
- While the api is starting up navigate in the app
- The online user is able to do navigate
<details>
<summary>Video:</summary>

https://user-images.githubusercontent.com/21312057/196967325-1a960d1a-5bf3-4257-afdb-6fcfe283e4a8.mov

</details>

**Observations:** 
- I also tested the same scenarios in single node but with two different preparations. Instead of editing the design document:
1.  I deleted a design document 
2. I deleted the migration_log document 
- I also tested one scenario with offline user, online user and not logged in with clustered CouchDb
-  All worked as expected

**Comment by lorerod** [comment] 2022-10-20 14:54
> Hi @lorerod
> 
> I have the changes that remove the 403 redirect in webapp in this branch: `2967-webapp-json-session`
> 
> * https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A2967-webapp-json-session/docker-compose/cht-couchdb.yml
> * https://staging.dev.medicmobile.org/_couch/builds/medic%3Amedic%3A2967-webapp-json-session/docker-compose/cht-core.yml
> 
> I also made a small change about how offline users might handle changes requests errors, so if you would please smoke test that as well, it would be awesome. Thanks!

**Fixed on branch 2967-webapp-json-session**
**Environment**
Instance: Local using cht-core.yml and cht-couchdb.yml provided
Browser: Firefox
Client platform: MacOS
App: api
Version: 4.0.0-2967-webapp-json-session

**Scenarios:**
1. Invalidate my migrations 

Steps to **prepare the scenario**:
- Log in as an online user 
- Go to database /_utils
- Select medic database
- Select Documents search for migration-log 
- Delete migration-log doc
-  In terminal run a command to monitor the JSON response
`while true;do clear;curl -sk https://localhost/api/v1/startup-progress |jq; sleep 1;done`

Steps to **execute the scenario with online user**:
- Prepare the scenario with an online user
- Restart API
- While the api is starting up refresh in the app
- The app stays refreshing until api finish starting
- The online user is able to do refresh
<details>
<summary>Video:</summary>

https://user-images.githubusercontent.com/21312057/196981345-65612f56-2bab-4c44-a3aa-47ed70561790.mov

</details>
Steps to **execute the scenario with offline user**:
- Prepare the scenario with an online user and log out
- Log in as an offline user
- Restart API
- While the api is starting up navigate and refresh in the app
- The offline user is able to navigate and refresh

<details>
<summary>Video:</summary>

https://user-images.githubusercontent.com/21312057/196982621-29dad25e-83d1-43a6-a701-5ec24135ba57.mov

</details>

Steps to **execute the scenario with offline user**:
- Prepare the scenario with an online user and log out
- Log in as an offline user
- Restart API
- While the api is starting up reload, and try to sync in the app
- The offline user is able to reload without problems and try to sync with a expected error

<details>
<summary>Video:</summary>

https://user-images.githubusercontent.com/21312057/196982165-0c003a18-9e22-4eba-8d8c-d8f81ad8e242.mov

</details>

**Comment by lorerod** [comment] 2022-10-20 14:55
Ok @dianabarsan this looks really good. Please let me know if you would like me to test another scenario. Thanks you.

**Comment by dianabarsan** [comment] 2022-10-20 15:25
Thanks for the update @lorerod . If you're happy with the state, I think we can close this off. We can add further updates in separate issues, since this was already merged.

**Comment by lorerod** [comment] 2022-10-20 15:27
Perfect @dianabarsan!

**Comment by lorerod** [comment] 2022-10-20 15:44
@dianabarsan `2967-webapp-json-session` has to be merge?

**Closed** 2022-10-20 15:47 UTC
Labels: Type: Feature, UI/UX, API, Priority: 3 - Low
