### ISSUE TITLE
When re-assigning a report for follow-up to different users, the report remains visible to users who are no longer assigned

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6458] opened 2020-06-01 22:17 UTC
**Describe the bug**

Hierarchy
```
    A
  /   \
B1     B2
```

For the MoH-Niger project, we have a user with facility_id at level A responsible for creating a report and "assigning" that report to another user with facility_id at level B.  To "assign" the report to the user B1, the report is created with an appropriate patient_id such that it appears in B1's replication view. This bug occurs when user A attempts to "re-assign" the report from user B1 to another user B2. To "re-assign" the report to user B2, the report is edited and the patient_id is changed to B2.  When this happens, the report appears for both user B1 and B2.

**To Reproduce**

1. Deploy [Niger MoH configuration](https://github.com/medic/config-msf/tree/master/niger)
1. Create a SAMU, with a riposte, and two case investigators.
1. Login as SAMU user, create a new COVID case via reports tab.
1. Login as Riposte user, find the task created for this COVID case, click on it, assign Investigator 1 to follow-up.
1. Login as Investigator 1, sync, find the follow-up task for this case
1. Login as Ripsote user, find the report created by the task in step 4, edit it, assign Investigator 2 instead of Investigator 1
1. Login as Investigator 2, sync, find the follow-up task for this case
1. Login as Investigator 1, sync

**Expected behavior**
Currently, both Investigator 1 and Investigator 2 both see the report.  Just based on how replication works, investigator 1 sees `rev-1` of the report and investigator 2 sees `rev-2` of the report. 

How can App Builders make the follow-up task for Investigator 1 disappear to enable the re-assigning of cases?

**Environment**
- Instance: https://msf-niger.app.medicmobile.org
- Browser: Chrome
- Client platform: Ubuntu Bionic
- App: webapp
- Version: 3.8.1

**Additional context**
https://github.com/medic/config-msf/issues/84

**Comment by SCdF** [comment] 2020-06-02 08:27
Is this not the standard class of issue, similar to moving people, where we do not have any kind of support for intelligently deleting data off users devices that still exists on the server but would not longer qualify for being replicated to that use? If so this would be an improvement as opposed to a bug (core has not supported this or any similar issue in the past and has never claimed to).

Or is there something else going on here as well?

**Comment by kennsippell** [comment] 2020-06-02 17:04
I created the issue because I know plans are being created to fix a "class of issues" related our inability to delete data off user devices. I was just wanting to capture this additional scenario, since I believe it brings its own set of nuances.

MoH Niger also needs a workaround (medic/config-msf#84) and I was hoping this might stimulate discussion.

**Comment by SCdF** [comment] 2020-06-02 17:26
Ok so if the end result of solving this class of problem in core was:
 -  When any CouchDB write occurs where the resulting permissible hierarchy changes compared to the existing one on record, any users who were in the old but are not in the new get instructed, as part of their normal document sync process, to delete that document

Would that cover these cases?

**Comment by SCdF** [comment] 2020-06-02 17:29
> But MoH Niger needs a workaround (medic/config-msf#84) to allow re-assignment and I was hoping this might stimulate discussion.

Can you do this for now completely with task completion and creation? i.e. have a "reassign" action (form) that results in a new task being created for Investigator B and resolves the task for Investigator 1?

**Comment by garethbowen** [comment] 2020-07-16 23:37
@kennsippell Is this a duplicate of #5701 ?

**Comment by garethbowen** [comment] 2020-08-06 00:46
Closing as a duplicate of #6544

**Closed by garethbowen** 2020-08-06 00:46 UTC
Labels: Type: Bug
