### ISSUE TITLE
Telemetry records not logged for every day FCHVs are active

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-core#7616] opened 2022-05-03 07:31 UTC
**Describe your bug:**

From the [forum](https://forum.communityhealthtoolkit.org/t/is-it-okay-to-assume-that-if-users-dont-have-telemetry-entry-for-particular-day-they-didnt-open-or-use-the-app/1849), it was assumed that version 3.14.2 onwards, it's safe to assume that if there's no telemetry entry for a day, that means there was activity on that day by CHWs. 

However, in one of the instances with version 3.14.2 on live, we are not seeing telemetry docs created for days when users submitted forms. There could be some issues related to #7606 , but we are seeing telemetry docs not created for an interval of more than a month, however we can see that they've reports submitted frequently even during that period. 

**Web app Version:** 3.14.2 
**Device Hardware Detail**:
```json
  "device": "gta7lite",
        "model": "SM-T225",
        "manufacturer": "samsung",
        "hardware": "mt8768",
        "cpuInfo": {
          "cores": 8,
          "arch": "aarch64"
        }
```
**Device Software Detail:**
```json
"software": {
        "androidVersion": "11",
        "osApiLevel": 30,
        "osVersion": "4.19.127-23190912(T225XXU1AUL1)"
      },
```
**App version:** v0.11.0-webview

**Comment by dianabarsan** [comment] 2022-11-23 11:17
@yrimal 
Are there any updates on this?

**Comment by yrimal** [comment] 2023-06-20 11:04
Hi @dianabarsan , 
Currently, this CHT instance is on 3.17.1 and android v 1.0.4, yet the issue still exists. I checked for some users and while users were active for 19 days (Counting only days on which they created new contacts), telemetry record was recorded only for 13 days.

**Comment by latin-panda** [comment] 2023-09-06 17:11
@ngaruko FYI, I'm going to start working on this one. Please let me know if you have any idea how to reproduce this one 🤔

**Comment by ngaruko** [comment] 2023-09-07 04:13
@latin-panda Not sure if this is consistent across all users and all devices or if it is only happening for particular users/devices. If it is consistent, then we could easily reproduce by shifting system clocks multiple times. If it is not, one has to do a deeper investigation of particular users' environment to learn what's causing that.
@yrimal Are there any patterns you noticed about users who are experiencing this, that we could use as a starting point for investigation?

**Comment by michaelkohn** [comment] 2023-09-07 17:27
We _should_ be able to look at some data to see how often this is occurring and/or which users are being affected most often. 

I think we'd look at:
1. **_User_**
2. **_Date_**
3. _Has telemetry record?_
4. _Count of reports submitted_
5. _Count of contacts created_
6. _Count of docs replicated_ (`initial_replication_date`/`latest_replication_date` on an `info` doc)

If any of 4,5, or 6 are > 0 but there wasn't a telemetry record, then there's a problem.

This isn't fool-proof because shifting device clocks could create a discrepancy between times generated on device (3,4,5) and times generated server-side (6)... but I think just looking at 3,4, & 5 will be indicative.  (Some convo/SQL on [this forum post](https://forum.communityhealthtoolkit.org/t/some-helpful-sql-to-look-into-number-of-days-per-month-a-hw-opened-the-cht/2804)).

**Comment by michaelkohn** [comment] 2023-09-08 15:23
I was working on some queries for this and realized it _is_ possible to have a report submitted / contact created for a given day (and synced to the server), but no telemetry record for that day. This can happen if the user synced the same day they submitted those docs but hasn't used their app on a subsequent day (since telemetry records are only written the _next_ day the user opens their app). 

There are plenty of examples where there are data records for subsequent days so this is still definitely a problem, but it's important to realize that this scenario is possible/likely.

**Comment by latin-panda** [comment] 2023-09-13 15:23
**How it works**

1. The telemetry service creates a telemetry DB in the device (phone, browser) for tracking telemetry records. This DB name is  `[user name]-telemetry-[uuid]`
<img width="800" src="https://github.com/medic/cht-core/assets/66472237/81a3e106-8ad4-44fd-a01f-dbb5dda570af">
<br><br>


2. The CHT keeps a reference of the telemetry DB name in the browser's localStorage
<img width="800" src="https://github.com/medic/cht-core/assets/66472237/d465dca8-cf18-4dd5-9131-6985b42a1af9">
<br><br>


3. The telemetry service takes the telemetry DB name from the localStorage, gets the data from that DB, and aggregates all those records to a document that is uploaded into the user's meta database with the name `telemetry-[ yyyy-mm-dd ]-[ uuid ].` The document we want to ensure is always uploaded whenever the user does actions in the CHT. 
<img width="800" src="https://github.com/medic/cht-core/assets/66472237/d9dfd26a-ee69-4b6e-914f-bad34c66e223">
<br><br>

4. Once the telemetry service uploads that document, _it deletes the telemetry DB_ and creates a new one to start saving records for the day. So, if all is good, there should only be 1 telemetry DB for each user on their device.  

**The problem**
After debugging and testing, these are the problems I found where the telemetry document wasn't uploaded to CouchDB:

A. If the localStorage is gone for some reason, the telemetry service won't know the telemetry DB name and will create a new DB. Leaving the old DBs there because it doesn't know they exist; therefore it won't process the records, and the data is not uploaded to CouchDB. 
<img width="481" src="https://github.com/medic/cht-core/assets/66472237/efbe4b80-374b-4e5e-9689-071c1e5963c4">
<br><br>

B. If the localStorage is okay and the user was doing actions while offline for days, each day the telemetry service aggregates the records from the telemetry DB and creates the document locally (step 3 from top) but deletes the one from the day before. When the user is online and syncs, only 1 telemetry doc is sent to CouchDB; previous days' metrics weren't included in that document.
<img width="769" src="https://github.com/medic/cht-core/assets/66472237/bf797925-ffc2-4562-8712-c23c36ff2875">
<br><br>

This is because the change's seq matches the until seq ([code](https://github.com/medic/cht-core/blob/08ec4d72d2a0bc3c20de53b8fefbbf6d9e23168f/webapp/src/js/bootstrapper/purger.js#L78)) even though the user is offline and hasn't sync yet to CouchDB.
<img width="800" alt="Screenshot 2023-09-21 at 10 09 21 pm" src="https://github.com/medic/cht-core/assets/66472237/a2c63fbc-6b34-41cd-88f3-9f64929fceb8">

FYI @ngaruko and @michaelkohn 

**The possible solutions**
From the 2 problems I spotted, I think **problem b** is more likely to happen. @garethbowen is it okay if I make this rule from `change.seq <= untilSeq &&` to `change.seq < untilSeq &&` ([line of code](https://github.com/medic/cht-core/blob/master/webapp/src/js/bootstrapper/purger.js#L78))?

@garethbowen do we want to fix **problem a**? 
1. One way is to get all the local database names by using [indexedDB.databases()](https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/databases) and filter by `telemetry` + user name, then process those telemetry records. 
2. Another option is to create the local telemetry database using dates, similar to the doc name in Couchdb `telemetry-[ yyyy-mm-dd ]-[ uuid ].`, so it's one per day, and we know what day it corresponds. <-- I like this one

**Comment by garethbowen** [comment] 2023-09-13 17:39
> is it okay if I make this rule from change.seq <= untilSeq && to change.seq < untilSeq && ([line of code](https://github.com/medic/cht-core/blob/master/webapp/src/js/bootstrapper/purger.js#L78))?

It's complicated but I'm not 100% sure if that's the solution. The untilSeq comes from the purge log which is updated when a replication completes successfully in the dbsync code in webapp. My understanding is the seq _should_ be the latest change seq, but it _might_ be the next change seq, in which case you're right. Here's the documentation: https://pouchdb.com/api.html#database_information . I recommend playing around with the dbInfo and seeing if...

1. When you create an empty db it's 0
2. When you make a new doc it's 1
3. Then find the seq of the new doc. If it's 0 then you're right and we should update the code and check for other places we use it and probably update the pouchdb docs as well. If it's 1 then it should work as is and the bug is somewhere else.

> Another option is to create the local telemetry database using dates, similar to the doc name in Couchdb

I like this one too. It means we can drop the local storage of the db name which always felt fragile, and then change the aggregation code to iterate over all dbs that match a certain name, aggregating and dropping them one by one.

**Comment by latin-panda** [comment] 2023-09-14 08:05
> 1. When you create an empty db it's 0
> 2. When you make a new doc it's 1
> 3. Then find the seq of the new doc. If it's 0 then you're right and we should update the code and check for other places we use it and probably update the pouchdb docs as well. If it's 1 then it should work as is and the bug is somewhere else.

I did this test, and the doc seq is 1 then the issue is something else, I'm trying to find it

**Comment by latin-panda** [comment] 2023-09-14 10:28
Following up on the **problem b**, the `untilSeq` gets updated by [dbSync](https://github.com/medic/cht-core/blob/6e353653650caa2903278748e1760f6ca493a401/webapp/src/ts/services/db-sync.service.ts#L258) even if the sync failed. This is where we need to fix that weird behavior.

**Closed** 2023-10-23 14:04 UTC
Labels: Type: Bug
