### ISSUE TITLE
Default language doesn't seem to do anything. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6671] opened 2020-10-09 17:59 UTC
**Describe the bug**
Setting the default language, then navigating to the app incognito displays English. Log in and still set to English. 

**To Reproduce**
1. Go to admin page.
1. Navigate to display.
1. Set default language to spanish.
1. Navigate to the app incognito.
1. App is shown in english. 

**Expected behavior**
App should be shown in default language. 

**Environment**
- Instance: lcoal, gamma.dev
- Browser: Chrome
- Client platform: Windows
- App: admin, webapp
- Version: 3.10

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by garethbowen** [comment] 2020-10-11 21:45
@newtewt The app default language is overwritten by the user's configured language. When you say "navigate to the app incognito" is it the login page that is still in English?

**Comment by newtewt** [comment] 2020-10-12 12:33
The login page is still in English when you navigate after setting the default language to English.

**Comment by garethbowen** [comment] 2020-10-12 18:03
This may be caused by #6313 - if your browser is set up for English then that will be used in preference to the configured default locale. You can verify this by checking the `accept-language` header on the request.

Try changing the language in your browser and loading in incognito mode again.

**Comment by michaelkohn** [comment] 2021-02-24 17:20
@newtewt ...

**Comment by michaelkohn** [comment] 2021-02-24 17:22
@newtewt The locale should be resolved in this order... 

> 1. Use the `locale` cookie. This is set by the user on a previous login, or by the administrator during user setup so most likely to be correct.
> 2. If no `locale` cookie is set, use the browser default. This is passed in the request's accept-language header. This may not match with the two letter code that we use so make a best effort here. Furthermore it may not match one of the supported languages for this project.
> 3. If the browser default doesn't match any supported language, use the project "default application language" set in configuration.
> 4. If the "default application language" in the project config isn't set (very unlikely), default to English.

Are you seeing something different?

**Comment by mrsarm** [comment] 2021-02-24 17:44
We also store the language selection of the user in CouchDB, so if the user sign-in in a new device that does not have the cookie set, it should be taken into account.

Also, not sure if this could cause the error in the test, but after saving the preferences from the _"User settings" > "Edit user profile"_ window, if you are an offline user and you don't sync the new configuration going to the _"Sync now"_ menu, the new language setting is applied in the device but not synced with the DB, so opening a new incognito browser won't reflect the change because the new language preference was not sent yet.

**Comment by newtewt** [comment] 2021-02-24 18:16
I'm closing this. It was a change in 3.10 that I was not aware of. 3.9 would take the system default where now the app tries the `accept-language` header. 

https://github.com/medic/cht-core/issues/6313

**Closed** 2021-02-24 18:17 UTC
Labels: Type: Bug
