### ISSUE TITLE
Users API not responsive

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#8689] opened 2023-11-08 21:53 UTC
**Describe the bug**
When calling `/api/v1/users` or `/api/v2/users` it does not respond.

**To Reproduce**
1. make a call to download users: `curl https://USER:PASS@DOMAIN/api/v2/users > ~/Documents/users.json`

**Expected behavior**
API call completes

**Logs**

```
curl https://medic:PASSWORD-HERE@CHT_URL_HERE/api/v2/users > ~/Documents/users.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   160    0   160    0     0      0      0 --:--:--  1:00:01 --:--:--    40

cat ~/Documents/users.json         
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Screenshots**
NA

**Environment**
- Instance: National deployment
- Browser: NA
- Client platform: NA
- App: NA
- Version: 4.3.1

**Additional context**
In testing, this API seems to work fine with 100s of users.  The instanced that we found the problem with has over ~8400 documents in the `_users` database  and 4,624,973 documents in the the `medic` database.  

A work around was used instead: 
1.  get sets 100 users (`limit=100`) and start at the 1st (`skip=0`) and then start at the 100th  (`skip=100`) .  You would do this in a loop until you got all users : `/_users/_all_docs?limit=100&skip=100 `
2.  Then to get the contact their linked to, query the `/medic/org.couchdb.user:USERNAME` endpoint

**Comment by garethbowen** [comment] 2023-11-08 21:59
@mrjones-plip Did you reproduce that? Is the "Time Spent" 1 hour or 1 minute? It looks like an hour I just can't imagine anyone sitting around for that long...

**Comment by mrjones-plip** [comment] 2023-11-08 22:27
Yups - I reproduced that on the production instance.  It's 1hr 00mi and 01sec.  Presumably the TTL for a session in API kicked it out.

**Comment by garethbowen** [comment] 2023-11-08 22:42
Right. Obviously it should complete in less than 1 hour and we probably need to implement streaming which is better on memory but also will keep the connection alive...

**Comment by mrjones-plip** [comment] 2023-11-08 22:43
And possibly pagination?

**Comment by garethbowen** [comment] 2023-11-08 22:46
Pagination is annoying in APIs but might have to in this case.

**Comment by 1yuv** [comment] 2023-11-30 00:11
>In testing, this API seems to work fine with 100s of users. The instanced that we found the problem with has over ~8400 documents in the _users database and 4,624,973 documents in the the medic database.

I've seen this issue in an instance with ~50 uses, 72 records on `_users` database and 730,000 records on` medic` database.

**Comment by 1yuv** [comment] 2023-11-30 00:14
Is this issue caused by output being too large or process taking too long to calculate output?

**Comment by garethbowen** [comment] 2023-11-30 00:32
I've had a quick look and at one point the code gets _all_ the facilities in the database, so they can be matched up later. We should definitely only get facilities that are referenced by the users. That's likely to solve your case with only 72 entries in the _users db.

**Comment by garethbowen** [comment] 2023-11-30 20:57
Assigning to @dianabarsan to finish off while I'm on leave.

**Comment by dianabarsan** [comment] 2023-12-13 08:49
@mrjones-plip 
I just merged a commit that improves performance of the users API endpoint for instances with large numbers of facilities. This is not a complete solution, though. Could you please try current master and assess whether we want to close this with the fix and create an additional issue to add pagination or another chosen solution.

**Comment by mrjones-plip** [comment] 2023-12-16 00:51
@dianabarsan - thanks for the ping!  I'll take a look at this when I get back from holiday - early Jan 2024!

**Comment by mrjones-plip** [comment] 2024-01-05 21:31
@dianabarsan - hrm - I don't have an easy way to test this.  i found no difference in my tests of creating one place, creating 1000 users for that place, creating 100 docs per user and running `time curl -so /dev/null https://USER:PASSWORD@CHT-URL/api/v2/users` (both took <300ms).  I tested in both a `4.5.0` and  `master` instances.

I suspect this is because my data is too hierarchically flat and the documents don't affect the slow query to get all the facilities.  Likely the best way would be to use the [test data generator](https://github.com/latin-panda/test-data-generator/) and have it create a tall hierarchy, populate it with 1000s of users and 10s of 1000s of documents.  Have it create the test data in both a `4.5.0` instance and an instance running `master`.  Then test each a few times with `time curl -so /dev/null https://USER:PASSWORD@CHT-URL/api/v2/users`.   

No doubt the ability to easily set up such a data rich test environment would be great in other use cases too!

**Comment by garethbowen** [comment] 2024-01-08 05:09
@mrjones-plip Yes that data won't cause an issue. The fix is specifically around retrieving every place in the database so if you only have one place it'll always be fast.

It would be interesting to test this by manually making the new request to the server that you initially found this issue on. That would probably be sufficient to measure an improvement. But to decide if we can close this or not we'd obviously have to run the whole process.

@mrjones-plip @1yuv Can you both share in Slack which servers you've seen this on? We should be able to close the db and upgrade to this branch to test.

**Comment by mrjones-plip** [comment] 2024-01-09 20:40
@garethbowen - I've shared the info in [slack](https://medic.slack.com/archives/C024KTGRW/p1704832355710659).

**Comment by garethbowen** [comment] 2024-01-25 06:19
Removed the "affects" labels as the bug isn't a regression.

**Comment by mrjones-plip** [comment] 2024-01-25 23:35
@jkuester  - with some of the testing you're doing for #8462, do you think this ticket is now within reach to test with out too much difficulty? I think the big difference is that we'd need users created in `_users` which don't in #8462.

Thanks!

**Comment by jkuester** [comment] 2024-01-26 20:33
We can easily create very large deeply nested hierarchies via the test-data-generator.  Additionally I have just confirmed that we have everything we need in place to inject actual users into the DB also (associated with contacts at any point in the hierarchy)!  Let me know if there is a specific test plan in mind that I could run!

**Comment by mrjones-plip** [comment] 2024-01-26 21:11
@jkuester  this is EXCELLENT news - thank you!

@garethbowen or @dianabarsan - can you confirm my test plan?

1. spin up a 4.5 instance with docker helper or on EKS
2. use [TDG](https://github.com/latin-panda/test-data-generator/) go generate 10k users with their own contact and own place 
3. generate 10m docs associated to the 10k contacts, evenly distributed.  what ever is easiest here - simple reports I'm guessing?
4. run `curl https://medic:PASSWORD-HERE@CHT_URL_HERE/api/v2/users > ~/Documents/users.json` verify it times out (or just doesn't work)
5. upgrade or redeploy to ~`master` instance
6. load identical data if new instance
7. run `curl https://medic:PASSWORD-HERE@CHT_URL_HERE/api/v2/users > ~/Documents/users.json` verify it now works

**Comment by jkuester** [comment] 2024-01-26 22:46
@mrjones-plip does the contact hierarchy matter here?  (I can create 10k `chw` users all in their own `health_area`s all under the same `district_hospital`.  Or we can make it deeper if needed.)  For the 10m docs, does it matter which contact they are associated with (so long as each user has access to 1000 docs?  (I can associate them with the user's person contact, the user's health_area or I could create additional contacts within the user's area.)

**Comment by mrjones-plip** [comment] 2024-01-26 23:08
Thanks for the question @jkuester !  We'll have to wait for Gareth or Diana per above, but I note [here where I tried and failed](https://github.com/medic/cht-core/issues/8689#issuecomment-1879280024) with 1 place and 1k users.

**Comment by garethbowen** [comment] 2024-01-29 06:55
@mrjones-plip The test plan looks good to me. Because the change is literally just the obvious bug and not a full fix, my gut feeling is it still won't work (or won't work fast enough) and will need more work so let's keep the DB around for round two.

@jkuester The hierarchy does matter here - the old code was getting every place at every level out of the database. 10m health areas will probably be enough to reproduce the issue.

**Comment by garethbowen** [comment] 2024-01-29 07:37
@jkuester Alternatively I'm happy to test it myself if you give me a few tips on how to generate the data?

**Comment by jkuester** [comment] 2024-02-01 17:08
@garethbowen sorry for the delay here.  I just got everything cleaned up and put into [a PR](https://github.com/latin-panda/test-data-generator/pull/16).

Data generation with TDG is pretty straightforward (though still working on the rough edges).  Basically if you have a look at default export down at the bottom of the [the default design from the PR](https://github.com/latin-panda/test-data-generator/blob/08e8bd1fb3a4dbd7dd5bbbd139ddd147a3aef291/sample-designs/default.js#L104), you can see the structure of what will be generated.  To generate the data:

- Check out my `user-telemetry` branch
- Run `npm ci`
- Run `npm run generate sample-designs/default.js` (optionally set the `COUCH_URL` envar when running this command if you want to specify where to write data)

Running the `sample-designs/default.js` will generate location hierarchy that contains 2 CHW Supervisors and 4 CHWs.  A user will be generated for each of these (with the default password of `password`).  Just edit that `default.js` to change what gets generated.  

The main challenge currently with using TDG for writing performance testing data is that its request batching/parallelism is not very sophisticated (https://github.com/latin-panda/test-data-generator/issues/17).  It can write a lot of data without erroring, but it might take a long time....  (Thoughts on easy ways to improve performance are very welcome!  :sweat_smile: )

**Comment by jkuester** [comment] 2024-02-02 14:22
:point_up: Aforementioned PR has been merged to `main`, so no need to check out the `user-telemetry` branch.

**Comment by garethbowen** [comment] 2024-02-07 06:02
I haven't had time to set up the testing, but I don't think this should hold up 4.6.0. Firstly it's a bug that's been around since the code was written, and secondly while the PR is a step in the right direction more is going to be required to get this API to work on large deployments, either pagination or streaming.

I'll move it to 4.7.0 but if this is blocking anyone please speak up!

**Comment by garethbowen** [comment] 2024-02-08 09:46
I found time to set it up today.

I used the TDG tool to generate around 5k users and around 50k places. Then I compared the `/api/v2/users` request from `4.5.x` (before the code change) to `master` (with the code change).

`4.5.x`:
```
gareth@gx:~$ curl http://a:b@localhost:5988/api/v2/users > output.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7453k  100 7453k    0     0   478k      0  0:00:15  0:00:15 --:--:-- 1702k
```

`master`:
```
gareth@gx:~$ curl http://a:b@localhost:5988/api/v2/users > output.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7453k  100 7453k    0     0  5306k      0  0:00:01  0:00:01 --:--:-- 5304k
```

This shows the change reduced the request duration from 15s to 1s.

Your results may vary: different configurations will produce different results based on the hierarchy.

However I'm now confident enough to say this is a significant improvement and suggest we close this issue as fixed, and raise a subsequent issue if further improvements are required for specific configurations.

@mrjones-plip Does this sound reasonable to you?

**Closed** 2024-02-08 13:14 UTC
Labels: Type: Bug
