### ISSUE TITLE
Adding a new language does not show on the login page until cache is cleared. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6477] opened 2020-06-09 14:29 UTC
**Describe the bug**
When adding a new language through the admin UI. The log in pages do not reflect this change until cache is cleared. 

**To Reproduce**
Steps to reproduce the behavior: Have two browsers open. Chrome and Firefox or chrome and incognito. 

1. Log in as admin on chrome. 
2. Navigate to log in page on firefox.  
3. Add a new lang on the chrome browser.
4. Refresh the log in page.
5. The new lang is not shown. Clearing cache will show the new lang. 

**Expected behavior**
New languages should be available when refreshing the page. 

**Environment**
- Instance: gamma-b
- Browser: FF and Chrome
- Client platform: linux
- App: webapp
- Version: 3.9

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by garethbowen** [comment] 2020-06-09 22:37
Closing as a duplicate of #6338

**Closed by garethbowen** 2020-06-09 22:37 UTC
Labels: Type: Bug
