### ISSUE TITLE
Validate env variables, better handling of CouchDB down when starting API / Sentinel

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#6376] opened 2020-04-27 10:46 UTC
**What feature do you want to improve?**
Server checks validation that checks you're setup correctly.

**Describe the improvement you'd like**
We currently check if you have set env vars but not if they are valid for all cases.  This causes confusion and is hard to trace down later. As well, there's uncaught errors when CouchDB can't be reached. We should work out what we can truly validate and do that here, so we error as quickly and cleanly as possible:

* We don't validate that your couch node name environment variable (`COUCH_NODE_NAME`) is set right such that it matches what's in CouchDB itself (eg `localhost:5988/_membership`). 
* If CouchDB isn't reachable we throw an uncaught error (`ERROR: uncaughtException`). We should catch it and show a nice to read error.

**Acceptance Testing**
All tests should be run twice.  The first test is to start the API  and the second is to start sentinel. Both are started in the dev environment by changing into their respective directories (`cd`) and then running  `node server.js`. The tests below have you override your environment variable by prefacing the call with a new, intentionally bad value:
* start both the API and sentinel with an invalid node name using: `COUCH_NODE_NAME=mrjones@is_great node server.js` Confirm you immediately get a fatal error, that neither can start and that there's a helpful error message displayed on the CLI. The last two lines illustrate this:
   ```
   COUCH_NODE_NAME=mrjones@is_really_great node server.js
   2020-09-01 14:20:02 INFO: Running server checks… 
   Node Environment Options: 'undefined'
   Node Version: 12.18.3 in development mode
   COUCH_URL http://localhost:5984/medic
   COUCH_NODE_NAME mrjones@is_really_great
   2020-09-01 14:20:02 ERROR: Fatal error initialising medic-api 
   2020-09-01 14:20:02 ERROR: `Environment variable 'COUCH_NODE_NAME' set to "mrjones@is_really_great" but doesn't match what's on CouchDB Membership endpoint at "http://localhost:5984/_membership". See https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md#required-environment-variables`
   ```
* start both the API and sentinel with an invalid URL for Couch using: `COUCH_URL=http://admin:pass@mrjones-is-great:5984/medic node server.js` Confirm you immediately get a fatal error, that neither can start and that there's a helpful error message displayed on the CLI. The last three lines illustrate this:
   ```
   COUCH_URL http://mrjones-is-great:5984/medic
   COUCH_NODE_NAME nonode@nohost
   [SNIP- some-stack-trace-info-here -SNIP]
   2020-08-28 15:57:55 ERROR: Fatal error initialising medic-api
   2020-08-28 15:57:55 ERROR: "CouchDB doesn't seem to be running on http://mrjones-is-great:5984/medic. Tried to connect but got an error:\n" +
     ' Error: getaddrinfo ENOTFOUND mrjones-is-great\n' +
     '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)' 
   ```
* additional tests may be optionally run by stopping CouchDB instance and trying to start both the API and sentinel, but this should result in the same errors.
* Ensure your `COUCH_NODE_NAME` is correct and that CouchDB is running. Then make sure you see the happy path affirmation that starts with "Environment variable" when you start both the API and sentinel:
   ```
   Node Version: 12.18.3 in development mode
   COUCH_URL http://localhost:5984/medic
   COUCH_NODE_NAME nonode@nohost
   Environment variable "COUCH_NODE_NAME" matches server "nonode@nohost"
   CouchDB Version: 2.3.1
   ```
* additional happy path tests may be run, such as setting up outbound messaging and ensuring the CouchDB server can be reached. This was one of the original issues that was caused before this PR - good outbound config broke because of bad CouchDB node name environment variable.

**Comment by garethbowen** [comment] 2020-04-27 23:41
This helps our users so it should not be on the Core Engineers backlog.

**Comment by mrjones-plip** [comment] 2020-08-26 00:31
Hey all!  Can I get a little more direction on this?  It looks like in both api and sentinal when we call `node server.js`, that [`check(serverUrl)`](https://github.com/medic/cht-core/blob/de43c6b777d78aa395159de52162a7f2ae9fed51/shared-libs/server-checks/src/checks.js#L82) is called. This includes two active checks to CouchDB:
* Verify that it's not in "admin party mode" via `couchDbNoAdminPartyModeCheck()` which does a half check that we got a 401 from couch db URL when doing `GET` without credentials.
* A full round-trip call to ensure that we can connect and get a valid couch version back from the DB server via `couchDbVersionCheck(serverUrl)`

That said, it's somewhere deeper in our code (it looks like in one of the copies of `net.js`) that we don't handle when the CouchDB isn't started very nicely (The two environment variables aren already checked in `envVarsCheck()`):

```
Node Environment Options: 'undefined'
Node Version: 12.18.3 in development mode
COUCH_URL http://localhost:5984/medic
COUCH_NODE_NAME nonode@nohost
2020-08-25 17:20:14 ERROR: uncaughtException: connect ECONNREFUSED 127.0.0.1:5984
Error: connect ECONNREFUSED 127.0.0.1:5984
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) Error: connect ECONNREFUSED 127.0.0.1:5984
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
2020-08-25 17:20:14 ERROR: UNCAUGHT EXCEPTION!
2020-08-25 17:20:14 ERROR:   Error: Error: connect ECONNREFUSED 127.0.0.1:5984
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  [stack]: 'Error: connect ECONNREFUSED 127.0.0.1:5984\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)',
  [message]: 'connect ECONNREFUSED 127.0.0.1:5984',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5984,
  [Symbol(kEnhanceStackBeforeInspector)]: [Function: bound enhanceStackTrace] {
    [length]: 0,
    [name]: 'bound enhanceStackTrace'
  }
}
```

So, is the goal of this ticket to more gracefully handle it when couchdb is down instead of this uncaught exception? Help Me Obi Wan Kenobi, you're my only hope!

**Comment by garethbowen** [comment] 2020-08-26 00:54
Catching that error and failing with a more descriptive error is a great idea, so yes, do that!

The specific example that Stefan was talking about is to do with the `COUCH_NODE_NAME` environment variable. We had a situation a while back where someone had their environment variable set to `x` but CouchDB was configured with the NODE_NAME of `y`. This is infrequently used but it is used in [settings.getCredentials](https://github.com/medic/cht-core/blob/master/shared-libs/settings/src/index.js#L31) for example. You can find documentation about the credentials management on the [docs site](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/outbound/#credentials).

The node name is used for clustered setups but even single node CouchDB installs need this set. More about [CouchDB nodes](https://docs.couchdb.org/en/stable/cluster/nodes.html).

So this issue is to ensure that whatever node name environment variable is set actually exists so we can fail early with a useful error message rather than randomly down the line. Consider using the `_membership` API to check this.

An alternative approach is to remove all use of the environment variable either but auto detecting the node name on startup, or refactoring the way we store credentials ( ie: https://github.com/medic/cht-core/issues/5904 ) and the few other uses so we don't need the variable at all. This is probably outside the scope of this issue.

**Comment by mrjones-plip** [comment] 2020-08-26 03:50
Awesome, thanks @garethbowen. I'll start enumerating the specific fixes in the body of the ticket, including catching the that error I cited.  

Tomorrow I'll look into reproducing that "environment variable set to x but CouchDB was configured with the node name of y." that Stefan was talking about - thanks for all the background notes!

**Comment by mrjones-plip** [comment] 2020-08-29 05:00
oh - this is neat! we [have tests](https://github.com/medic/cht-core/blob/master/shared-libs/server-checks/test/checks.js) that now don't pass the checks because they're passing in `something` as the `COUCH_NODE_NAME`, and also the new `getNodeNameFromJson()` function can't derive the server's node name.  

getNodeNameFromJson() is now very defensive and is correctly returning false when getting this JSON response from the mock `_membership` couch endpiont:
```javascript
{ version: '2' }
```

Which in turn causes the `check()` function to barf when called in [`test/check.js`](https://github.com/medic/cht-core/blob/master/shared-libs/server-checks/test/checks.js):

```
Node Environment Options: 'undefined'
Node Version: 9.11.1 in development mode
COUCH_URL http://localhost:5984/
COUCH_NODE_NAME something

Error: the string "Environment variable 'COUCH_NODE_NAME' set to \"something\" but doesn't match what's on CouchDB Membership endpoint \"false\". See https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md#required-environment-variables" was thrown, throw an Error :)
Node Environment Options: 'undefined'
Node Version: 9.11.1 in development mode
COUCH_URL http://localhost:5984/
COUCH_NODE_NAME something

AssertionError: expected 'Environment variable \'COUCH_NODE_NAME\' set to "something" but doesn\'t match what\'s on CouchDB Membership endpoint "false". See https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md#required-environment-variables' to equal 'error'
Expected :error
Actual   :Environment variable 'COUCH_NODE_NAME' set to "something" but doesn't match what's on CouchDB Membership endpoint "false". See https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md#required-environment-variables
<Click to see difference>

    at /home/mrjones/Documents/MedicMobile/cht-core/shared-libs/server-checks/test/checks.js:169:29
```

I'm gonna stop for now and pick this up Monday, but might have to ping Gareth or Diana for the best approach

**Comment by ngaruko** [comment] 2020-09-09 23:56
Tested on ` 6376-earlier-checks-on-boot`, by starting both the API and Sentinel with invalid `COUCH_NODE_NAME` and `COUCH_URL`. 
```
(base) Macs-MBP:api bede$ echo $COUCH_NODE_NAME
couchdb@localhost
(base) Macs-MBP:api bede$ COUCH_NODE_NAME=different_name node server.js
2020-09-10 11:32:14 INFO: Running server checks… 
Node Environment Options: 'undefined'
Node Version: 13.7.0 in development mode
COUCH_URL http://localhost:5984/medic
COUCH_NODE_NAME different_name
2020-09-10 11:32:14 ERROR: Fatal error initialising medic-api 
2020-09-10 11:32:14 ERROR: `Environment variable 'COUCH_NODE_NAME' set to "different_name" but doesn't match what's on CouchDB Membership endpoint at "http://localhost:5984/_membership". See https://github.com/medic/cht-core/blob/master/DEVELOPMENT.md#required-environment-variables` 
```
Invalid couch url
```
(base) Macs-MBP:sentinel bede$ COUCH_URL=http://admin:pass@fakehost:5984/medic node server.js 
2020-09-10 11:39:04 INFO: Running server checks… 
Node Environment Options: 'undefined'
Node Version: 13.7.0 in development mode
COUCH_URL http://fakehost:5984/medic
COUCH_NODE_NAME couchdb@localhost
2020-09-10 11:39:04 ERROR: Fatal error intialising medic-sentinel 
2020-09-10 11:39:04 ERROR: "CouchDB doesn't seem to be running on http://fakehost:5984/medic. Tried to connect but got an error:\n" +
  ' Error: getaddrinfo ENOTFOUND fakehost\n' +
  '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)' 
```
Also tested with couchdown -> error handled more gracefully:
```
Node Environment Options: 'undefined'
Node Version: 13.7.0 in development mode
COUCH_URL http://localhost:5984/medic
COUCH_NODE_NAME couchdb@localhost
2020-09-10 11:46:22 ERROR: Fatal error intialising medic-sentinel 
2020-09-10 11:46:22 ERROR: "CouchDB doesn't seem to be running on http://localhost:5984/medic. Tried to connect but got an error:\n" +
  ' Error: connect ECONNREFUSED 127.0.0.1:5984\n' +
  '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)' 
```
Feel free to merge and close @mrjones-plip

**Comment by mrjones-plip** [comment] 2020-09-09 23:58
ah - sweet as - thanks @ngaruko !

**Closed** 2020-09-10 22:51 UTC
Labels: Type: Improvement
