### ISSUE TITLE
Supervisor CHW Create

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7753] opened 2022-08-30 21:46 UTC
**What feature do you want to improve?**
Right now there is no way to for an offline user, like a supervisor, to create another user, like a CHW.  Instead they need to reach out to an CHT admin, an online user, to create the account for them.  This can often take a while and leaves the supervisor with a device and a CHW that are prevented from giving care to the area's patients. 

**Describe the improvement you'd like**
It would be great if supervisors, using an authentication code, were allowed to create a CHW user in an area.  This would cut out a lot of the delay in the current flow. 

**Describe alternatives you've considered**
NA

**Additional context**
This is similar to the offline replace feature #7703, but differs in that the supervisor would use their own device and the new CHW would get a new device provisioned for them.

Private docs:
* [Figma](https://www.figma.com/proto/igJBl04RYEsHiUMEehNyUy/User-management?node-id=1095%3A1876&scaling=scale-down&page-id=1026%3A961&starting-point-node-id=1031%3A1938)
* [Story Map](https://docs.google.com/presentation/d/1SsfNbuqPEVJhN-HGDEWOpA90yTPjYVA62q7vbVxr8MI/edit#slide=id.g1451dc5f7a9_0_0)
* [Discussion](https://docs.google.com/document/d/18l9175kuNlFsCiIhg2Rz7AMHrixfs6SBZWxkTut-ZGE/edit)

## Usage

Enabling this feature is similar to the existing [user-replace](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/transitions/#create_user_for_contacts) functionality.  

- Load the updated code by either:
  - Checking out the [`7753-supervisor-chw-create`](https://github.com/medic/cht-core/tree/7753-supervisor-chw-create) branch and building it locally
  - Upgrading your instance to the latest feature release  `4.1.0-4.1.0-FR-supervisor-chw-create-beta.4` ([see below](https://github.com/medic/cht-core/issues/7753#issuecomment-1373024792))
- Update app_settings:
  - Enable token login:   `"token_login": {  "enabled": true }`
  - Set app url to your host (`192.168.1.249` in this case): `"app_url": "https://192-168-1-249.my.local-ip.co/",`
  - Enable create user for contacts transition: `"transitions": { "create_user_for_contacts": true }`
- Upload `default` config forms from the [`7753-supervisor-chw-create`](https://github.com/medic/cht-core/tree/7753-supervisor-chw-create) branch 
- Open the webapp and add a new person contact
  - Set a valid phone number
  - Choose `CHW` or `CHW Supervisor` as the "Role"
- Save the contact and sync
- Sentinel should process the new contact and automatically create a new user
  - From the "App Management" console you should be able to see the new user in the `Users` tab
  - The login link for the new user should be visible on the `Outgoing messages` tab

### default config

- Update contact forms that support adding persons to set the `user_for_contact.create.add = true` on the new contact doc when the user has selected `chw` or `chw_supervisor` as the role 
- [X] Should we support triggering a new user for a person from the edit contact form (or from app forms)?
    - We are only going to support adding users for new contacts.  However, we should support adding a new users for all the different ways that we can add a new person contact (e.g. any contact/app form can add a new person).  As described below, our Sentinel logic should not be dependent on which form was used to add the contact, but should work in all cases.
  - For the `default` config specifically, we should update the following forms to set `user_for_contact.create.add = true` for new persons when `chw` or `chw_supervisor` is selected for the role:
    - `district_hospital-create`
    - `health_center-create`
    - `clinic-create`
    - `person-create`

### ~~webapp~~

- ~~Add support for running client-side transitions for offline users~~
  - ~~Add boolean function (`isEnabled`) to each transition where the transition can determine if it should run for online/offline users~~  ~~After looking at this some more, I think we might be able to avoid adding a whole new function and instead just return `false` from the existing `init` function when we do not want to run the transition....~~
    - ~~The `muting.transition` should return `false` when the user is online~~
    - ~~The `create-user-for-contact.transition` should always return `true`~~
  - ~~The `transitions.service` will check `isEnabled` when loading transitions~~
- ~~Update `create-user-for-contact.transition` client-side transition to mark contacts for adding a new user~~
  - ~~When the transition sees a contact added/edited with `create_user_for_contact = true`:~~
    - ~~Set `user_for_contact.create = { status: 'READY' }` on the contact doc~~
      - ~~Can use the `create-user-for-contacts.service` to do this~~
    - ~~Delete the `create_user_for_contact` flag from the contact doc (so it doesn't run again the next time the contact is edited)~~
      -  [X] ~~should we support adding users when editing persons (or just when adding)?~~
          - ~~We are only going to support adding users for new persons~~

### transitions shared-lib

- Update `create-user-for-contacts` transition to support adding new users
  - When the transition sees a person contact with ~~`user_for_contact.create.status = 'READY'`~~ `user_for_contact.create.add = true` and the contact does not have an existing infodoc in `medic-sentinel` (meaning it is a new contact):
    - Create a new user with the contact's phone number and role
      - Load the role data from the contact doc's `roles` or `role` field. 
    - ~~Set `user_for_contact.create.status = 'DONE'` on the contact doc~~ Delete the `user_for_contact.create.add` field
    -  [X] Should we support adding and replacing users on the same contact at the same time?  Seems possible to run into this case when syncing data for an offline user.
        -  It should not be possible to hit this case since we do not support adding users on existing contacts (and so the contact should not have any existing users to replace...)
- As with the user-replace logic, the `create-user-for-contacts` transition can only be enabled when token login is also enabled. The new users will have a generated username and a login link will be sent to the contact's phone number.

## To do
- [ ] Clean up backup branch `7753-supervisor-chw-create-backup` once this feature gets merged to `master`

**Comment by mrjones-plip** [comment] 2022-08-30 21:50
@m5r  and @jkuester  (and @tatilepizs ) - here's the story map we reviewed today inline ([and original](https://docs.google.com/presentation/d/1SsfNbuqPEVJhN-HGDEWOpA90yTPjYVA62q7vbVxr8MI/edit#slide=id.g143d3a1a318_1_31) - private to Medic):

![image](https://user-images.githubusercontent.com/8253488/187549899-7bd158a9-50b1-4aa6-8aa2-10c34e9d646f.png)

**Comment by jkuester** [comment] 2022-12-20 23:59
After considerable discussion with @m5r and rolling this over a bunch in my mind today here are some scattered design thoughts that I have:

For creating a user for a contact, I think we should (as discussed) use a trigger field that the form can set on the contact that will trigger the creation of the user. I recommend we use: `create_user_for_contact = true`. When the webapp sees this field on a contact, it can use the `create-user-for-contacts` service to add a new object to the array on the contact: `user_for_contact.create = [{ status: 'READY' }]`.  (This should work when adding _or editing_ a person.  AND it should support adding multiple users for the same contact.)  Then the webapp should remove the `create_user_for_contact` field from the contact doc so no additional users are triggered the next time the contact is edited.

I see two options for where to put the code to handle this trigger:

1.  Put it in the `contact-save` service.  Pro is that it should be pretty simple to add here. 

2. Put it in the create-user-for-contacts client-side transition. Pros: It is consistent with where we put the `replace` logic. It will only get run when the create-user-for-contacts transition is enabled. It should support adding users for contacts created/edited via contact forms and also contacts created by app forms (the `contact-save` service approach would not work with app forms)!  The con is that we currently do not support running client-side transitions for online users, but that is something we want to add support for anyway....

One final question I want to raise is if we need any kind of constraints around this functionality.  For `replace` you can only trigger it for the currently logged-in user and it only works with a new contact that is in the same place as the current user's contact.  However, for this new `create` functionality, we don't have any constraints built in yet.  So, if the user has permissions to add/edit a person contact and the form let them set the `create_user_for_contact = true` it can automatically trigger a new user to be created with whatever roles the contact has (and a login link will be sent to whatever phone number is configured for the contact.....).  Are we making it too easy to create users?  :)

**Comment by jkuester** [comment] 2023-01-05 22:57
# e2e Test cases to add

## `create-user-for-contacts.wdio-spec`

- user replace:
  - [ ] Update `does not create a new user when the replace_user form is submitted for online user` to assert the user is replaced for an online user
  - for an offline user:
    - [ ] Move the following tests out of the `for an offline user` block since they do not depend on the user actually being offline: 
      - `does not assign new person as primary contact of parent place if original person was not primary`
      - `creates new user when replace_user form is submitted for contact associated with multiple users`
      - `does not create a new user or re-parent reports when the transition is disabled`
- user create:
  - add person: 
    - [ ] `creates a new user when adding a CHW as an offline user`
    - [ ] `creates a new user when adding a CHW Supervisor as an online user`
    - [ ] `creates a new user when adding a person while adding a place`
    - [ ] `does not create a new user when the transition is disabled`
    - [ ] `does not create a new user when the transition fails`
    - 
  - edit person:
    - TODO need to decide if we want to support this
    - [ ] `creates additional user for person already associated with an existing user`
    - [ ] `only creates one user for the first version of a contact to sync and additional conflicting requests to add are ignored`

**Comment by mrjones-plip** [comment] 2023-01-05 23:21
@jkuester  - thanks so much for the write up!

> I see two options for where to put the code to handle this trigger

My vote is "Put it in the create-user-for-contacts client-side transition".  Let's get it out in a FR as quick as can be so partners can assess it. 

> Are we making it too easy to create users? 

Nope! Deployments can:
1. Not enable the feature (default)
2. Put a field that requires a PIN to submit it
3. Train end users on how to use it

We can be sure to add these three points to the docs!

> e2e Test cases to add

These should not blog the FR - I don't think they are, but just being explicit ;)

**Comment by jkuester** [comment] 2023-01-06 00:08
FR is out!  `4.1.0-FR-supervisor-chw-create-beta.2` has been published (the only catch is that I am not sure exactly how to install a FR on `4.x`)  Regardless, you can still install the same code on a 4.x instance by just upgrading to the `4.1.0-FR-supervisor-chw-create` branch build (which has also been published).  

@tatilepizs this should be ready for some testing now!  You can follow the `Usage` steps that I put in the issue description to trigger the desired behavior.  Also, I added a comment earlier with some initial thoughts on the e2e tests that we need.  Feel free to add/modify that list as you see fit.  I think we are good to branch off of [`7753-online-client-side-transitions`](https://github.com/medic/cht-core/tree/7753-online-client-side-transitions) as the current "stable" branch which we can target with test changes.  Feel free to add your name next to some of the e2e test changes and start working on those when you get the chance!  I will do the same as I have time.

**Comment by jkuester** [comment] 2023-01-06 00:13
FR is out!  `4.1.0-FR-supervisor-chw-create-beta.2` has been published (the only catch is that I am not sure exactly how to install a FR on `4.x`)  Regardless, you can still install the same code on a 4.x instance by just upgrading to the `4.1.0-FR-supervisor-chw-create` branch build (which has also been published).  

@tatilepizs this should be ready for some testing now!  You can follow the `Usage` steps that I put in the issue description to trigger the desired behavior.  Also, I added a comment earlier with some initial thoughts on the e2e tests that we need.  Feel free to add/modify that list as you see fit.  I think we are good to branch off of [`7753-supervisor-chw-create`](https://github.com/medic/cht-core/tree/7753-supervisor-chw-create) as the current "stable" branch which we can target with test changes.  Feel free to add your name next to some of the e2e test changes and start working on those when you get the chance!  I will do the same as I have time.

**Comment by mrjones-plip** [comment] 2023-01-06 01:38
@Tatiana et al. - As a stop gap solution, you can totally just use Docker Helper and change your compose file by editing the 5 instances of string: `public.ecr.aws/s5s3h4s7` in  `~/.medic/cht-docker/PROJECT_NAME/compose/cht-core.yml` .  You need to replace the last section after the `:` to have the new tag of `4.1.0-FR-supervisor-chw-create-beta.2-4.1.0-FR-supervisor-chw-create` .

so the `healthcheck:` service, for example, would look like this:

```
  healthcheck:
    image: public.ecr.aws/s5s3h4s7/cht-haproxy-healthcheck:4.1.0-FR-supervisor-chw-create-beta.2-4.1.0-FR-supervisor-chw-create
    restart: always
```

After that - Do  a `stop` and then start it and away you go!

```
$ ./cht-docker-compose.sh another_one.env stop
Stopping project "another_one"... done 

$ ./cht-docker-compose.sh another_one.env     

[+] Running 1/1
 ⠿ Container another_one-dir-cht-upgrade-service-1  Started                                                                                                                                   0.4s
Starting project "another_one". First run takes a while. Will try for up to five minutes.......

  Success! "another_one" is set up:
```

Anything is easier than running the full dev stack :upside_down_face:

**Comment by jkuester** [comment] 2023-01-06 16:30
@n-orlowski @tatilepizs I would appreciate your thoughts on whether we should support adding a user _to an existing contact_ (or if we should limit the functionality to just support adding a user when adding a new contact)?  Both are possible and not too hard to implement from a technical perspective.  

The main consideration I have if we want to support adding a user while editing a contact is how the UX should look for that.  Should it be a question in the edit-person `contact` form ("Do you want to add a user?")?  That seems a little confusing.  Should we support triggering the add-user functionality from an `app` form so that projects could create an "Add User" form where they pick an existing contact to add a user for?  Other ideas?

If we choose to just support adding a user for a new contact, I do not think we are going to end up coding into a corner where it would be really hard to expand the functionality in the future.  We could release an MVP of this functionality that only supports adding a user for new contacts, but then later we could come back and expand the functionality to support adding users to an existing contact if that is requested.....

**Comment by mrjones-plip** [comment] 2023-01-07 00:18
> whether we should support adding a user to _an existing contact_ (or if we should limit the functionality to just support adding a user when adding a new contact)? Both are possible and not too hard to implement from a technical perspective.

Great questions - Let's think on this next week!  

As it stands, current functionality is that it both creates a user when creating a contact and create a user when editing  a contact. In testing, I ended up with 2 contacts and 7 users (see below ;)  I think i'm leaning toward an explicit "create new user when saving" or something and just let the user decide. Amazing nice to have would be showing how many users are associated to that contact, but that's out of scope!

I'd love to hear what UX and QA folks have to say (great idea to ask) and am happy to share my instance (or revive our demo instance :thinking: ).  Let's figure this early next week.

![image](https://user-images.githubusercontent.com/8253488/211121090-2a235042-c9cc-4ef4-a071-333d8b7c3a12.png)

**Comment by tatilepizs** [comment] 2023-01-07 02:27
I think that it will be better to just add users for new contacts or add something specific and that the user can decide, for now. It is a little confusing to add a user when an existing contact is edited, especially if the edited information is not relevant. 

I have always had questions about the roles of the contacts and users and their functionality, and maybe now is the right time to ask 🙂 .
I am not sure if it is important that the role of the contact and the user are the same, because what would happen if a contact is created with the `CHW` role and a user is created with the same role at that moment, and then the role of the contact is changed to `facility manager` for example, will the user still be valid? should we also update the role for the user? should we create a new user with that new role?
I don't know if this is something that could really happen, or if once a contact is created it is really difficult to change their role.

Let me know if I am completely wrong, but I think that all the permissions about creating reports, for example, are based on the user role and not on the contact role, I don't know what is the usage of the contact role in the code, and if it is really important at some point.

**Comment by jkuester** [comment] 2023-01-09 13:49
> As it stands, current functionality is that it both creates a user when creating a contact and create a user when editing a contact. In testing

@mrjones-plip Just to be clear, this behavior is due to a bug in the current branch implementation of the `person:edit` form.  It is not the intended behavior.  But, yes, your point still stands that creating users while editing the contact can be confusing.

**Comment by jkuester** [comment] 2023-01-09 14:17
@tatilepizs good questions.  Thanks for helping round out the conversation here!  Here are my thoughts:

> I think that all the permissions about creating reports, for example, are based on the user role and not on the contact role, I don't know what is the usage of the contact role in the code

Yeah, so IMHO the current CHT behavior here is pretty nasty.  AFIK all the Couch/CHT build-in permissions checking is done via the roles stored on the _user doc_ from the `_users` DB.  _However_, for projects that want to add custom role-based logic into their forms (or want to base form accessibility in the form properties context expression) on the role of the current user they do not have access to the doc from the `_users` DB in these places.  Instead, the user's _contact doc_ (from the `medic` DB) is available. So, the typical practice (illustrated by our default config) is to duplicate the user's role data into the contact doc as well.

> what would happen if a contact is created with the CHW role and a user is created with the same role at that moment, and then the role of the contact is changed to facility manager for example, will the user still be valid? 

I think we would consider the user configuration to be "inconsistent" (kind of "invalid" but not completely broken).  The data in the `_users` doc will be considered the source of truth for all the Couch/CHT logic, but custom logic in the forms might not work as intended if the contact doc has a different role.

> should we also update the role for the user?

I think this would be good functionality to consider adding in the future, but is out of the scope of this current project.  (It is also worth noting that this issue of the `_user` and contact docs getting out of sync is an existing problem and not something being introduced by these changes.)

> should we create a new user with that new role?

No, I doubt this is what we would want to do.  If we want to support "automatically" adding a new user for an existing contact, it seems like it needs to happen only in a very specific set of circumstances which would not be surprising to the user.....

**Comment by tatilepizs** [comment] 2023-01-09 14:36
Perfect @jkuester, thank you for all the details, it is so much clearer now 🙂

**Comment by mrjones-plip** [comment] 2023-01-09 16:19
@tatilepizs  - yes - excellent questions to ask - I second @jkuester thanks for adding them.

@jkuester  - speaking of seconding, I second all of your positions you suggested above.  Excellent responses to excellent questions!

**Comment by jkuester** [comment] 2023-01-10 16:56
For the record, in a discussion during the Allies Sync, today, we decided to move forwards with only supporting adding users to _new contacts_.  

It is worth noting that this will simplify UX logic in the webapp (and dramatically reduce the number of e2e test cases). However, counter-intuitively, the Sentinel logic will still have to allow for adding users to existing contacts can be created offline and edited several times before being synced to the server.

**Comment by jkuester** [comment] 2023-01-11 17:50
My takeaways from the design discussion today with @mrjones-plip @dianabarsan @m5r:

- We don't want to make client-side transitions available to _online users_:
  - Online users have a live connection to the server database and so will pick up change from Sentinels transitions in real time as they happen.
  - Most potential applications of client-side transitions (e.g. creating users for contacts) for _online users_ can be completely replaced by Sentinel transitions (without requiring any pre-processing in client-side transitions).  
  - Reducing additional logic in webapp is good from a performance perspective. Better to push our logic flows (especially for online users) towards async non-blocking processing on the server side instead of online users trying to run a bunch of logic locally in the client.
  - Avoiding magical changes to documents that happen when trying to save them in the webapp is a good thing.  There is more visibility/traceability to the work that Sentinel does.
- We will not be adding support for _replacing_ online users at this time
  - It is still technically feasible to do this (by adding more code to the Sentinel transition that will listen and react to `replace_forms` that get submitted).
  - It should not be excessively complex to implement, but will require dedicated development effort (we will not get it for free... :disappointed:). So, this will have to wait for its own project.
- This project's goal is to update the `create_user_for_contact` Sentinel transition to add new users for _newly added contacts_:
  - The transition should listen for new person contacts with `user_for_contact.add = true`
  - A contact is considered to be "new" if there is no existing infodoc for it in `medic-sentinel`
  - No changes to webapp should be required. The create contact forms will be responsible for populating `user_for_contact.add`.  

I will update the design in the issue description with these changes....

**Comment by jkuester** [comment] 2023-01-11 19:04
@n-orlowski @tatilepizs et. al. What do you think about updating the `default` config forms to limit the `Roles` available to select based on the type of place that will be the parent for the new person contact?  Currently when creating a person, you can select any role, regardless of where in the hierarchy the person is being created.

However, we are going to be using this selected role when creating a new user for the contact. So, whenever a contact is created with the `chw` role, we are going to create a new `chw` user.  Does it make sense to limit the role choices available in the form so that the user can only select the `chw` role when adding a person to a `health_center`, etc?

I think it comes down to how opinionated the `default` config should be.  Actual production config would never let just any user create a new `chw_supervisor` person at any level of the hierarchy, but that is currently how the `default` config works.  We can either leave it like it is and let new users get added anywhere in the hierarchy or we can update the config to be more opinionated...
---

If we want to make the config more opinionated (by limiting the possible roles available based on the level in the hierarchy) then the next question is what the role visibility should be. 

However, before determining visibility, we need some mapping between the roles available when creating a new person contact and the actual roles for users in the `default` config.

### Current `contact` level roles (set on the contact doc):

- chw
- chw_supervisor
- nurse
- manager
- patient
- other (freetext)

### Current `user` level roles (set on the `_users` doc):
- data_entry
- analytics
- gateway
- program_officer
- crfo
- chw_supervisor
- chw

The `chw` and `chw_supervisor` roles are pretty easy, but do we want to create users for any of the other `contact` roles?  

Thoughts?

**Comment by mrjones-plip** [comment] 2023-01-11 19:55
> I think it comes down to how opinionated the default config should be.

Great question!  I think it's more important to get the feature A) well documented and B) demo-able in the simplest manor. We're still in MVP land, so it means we don't focus on the perfect implementation, especially when it comes to `default` config.

To this end, I think we should make no changes to the `default` config and leave it as is.  It's blunt right now and will create all kinds of extra users, and that's OK!  It's clear that this is meant to be changed.  

I could see that while we're doing up the docs we might want to add a supervisor form with limited roles that slots into the existing `default` hierarchy to demonstrate how a more realistic deployment would use it.  If this is the case, we may opt to remove the feature from the generic edit contact form, but that's a decision to be made at the time we're authoring the docs.

**Comment by jkuester** [comment] 2023-02-16 22:56
@mrjones-plip @n-orlowski @tatilepizs how committed are we to only allowing users to be added for _new_ contacts?  It turns out [it is basically impossible](https://github.com/medic/cht-core/pull/7988#discussion_r1109102202) to know in Sentinel if a doc is new or not.  So, we would either need to build that functionality into Sentinel or just commit to supporting adding users for existing contacts.

I don't think the new functionality in Sentinel would be very hard, but it is a whole new batch of work/tests/etc.  Supporting adding users for existing contacts would involve minimal changes to the implementation code, but would require a number of new tests to be added to cover the new edit scenarios....  (And we might want to consider what a form for adding a user to an existing contact would look like... This question was one of the main reasons we decided not to go this way in the first place.)

**Comment by mrjones-plip** [comment] 2023-02-17 00:02
thanks for the heads up @jkuester !

Per our call just now,  we decided since the amount work to add new tests to cover the scenario of user creation upon both new and existing contacts  is within an order of magnitude of the same amount of work to bend sentinel to our will, we'll update sentinel to be aware if it has seen a contact before.

This means functionality will be as we intended and users are only created when contacts are created, not when they're edited.

**Comment by dianabarsan** [comment] 2023-03-03 13:31
The CHT has historically had issues with misconfigured users, that had many tens of thousands of documents, and impacted server performance significantly. 

We got better at communicating limits: 
- when admins create users from the admin app, a warning is displayed when computed number of docs exceeds 10k
- when cht conf creates users, before any of the accounts are actually created - the cht-conf user must confirm creation for accounts that exceed 10k docs
- last line of defence, when users first log in 

We wish to get better at handling users with large numbers of docs, but I'm not sure we're quite there yet. 

My question is: are there any plans of making this feature aware of doc count limits and possibly decline user creation if limits are exceeded?

**Comment by jkuester** [comment] 2023-03-03 13:59
@dianabarsan this is a good question!  I guess there is nothing from a technical perspective that would prevent us from checking the doc count in the transition before creating the user.  My main concern is that with both `admin` and `cht-conf`, the server administrator is actively involved and is prompted to figure out what to do.  In the case of this feature, the feedback loop to the administrator is a lot longer. As things are, we would write the error to the `errors` object on the contact doc, but it would require some manual debugging to figure out why the expected user was not automatically created....  

(Also, just wanted to note that I would think the user-replace workflow would be excluded from this check since we can assume if they already have a user with a ton of docs, and are trying to replace them, we should not prevent the replacement....)

@dianabarsan @mrjones-plip should I maybe at least long an issue for this and we can address it in the future?  (Or is this something we need as part of this MVP?)

**Comment by jkuester** [comment] 2023-03-03 14:19
@tatilepizs this feature is ready for AT (just a formality for this issue, I think)!  (Assuming the preceding comment does not generate any new changes here....)

Only one thing has recently changed in the workflow here and that is around the edge-case behavior of what happens when a contact is marked both to `create` and to `replace` users at the same time.  In that case, we should ignore the `create`, and just perform the `replace`.  To recreate:

- Stop Sentinel
- Create a new `chw` contact (contact `A`) with a valid phone number (using the person-create form).  
	- This will set the `create` flag on the new contact, but a new users will not be created since Sentinel is down.
- Using the Admin app, manually create a new user for the contact
- Login as the new user and submit the `replace_user` form to create contact `B`.
- Restart Sentinel
	- Once Sentinel finishes processing the changes, it should have:
		- Deactivated the existing user associated with `A`
		- Created a new replacement user associated with `B`
		- NOT created any additional users associated with `A` (since the `create` action is ignored)

**Comment by tatilepizs** [comment] 2023-03-03 17:23
Great news @jkuester! 🎉 

I will test this scenario that you mentioned in the previous comment, I am really curious. But as you said all the AT was already done during the process, this is in fact just a formality. 😄 thank you!

**Comment by tatilepizs** [comment] 2023-03-04 01:24
### Test details

**Config:** Default
**Environment:** Local, branch `7753-supervisor-chw-create`
**Platform:** WebApp
**Browser:** Chrome

---

This feature is working perfectly 🎉 

For the edge-case that is mentioned in a [previous comment](https://github.com/medic/cht-core/issues/7753#issuecomment-1453601394), here is the test:

<details>
<summary>Contact created while sentinel was stopped. </summary>

![image](https://user-images.githubusercontent.com/94494491/222864248-d8e36528-42d1-422f-ba14-d9e14071832e.png)
![image](https://user-images.githubusercontent.com/94494491/222864319-997e1a52-33dc-4c2c-88bf-ef672bfc8623.png)

</details>

<details>
<summary>User created manually.</summary>

![image](https://user-images.githubusercontent.com/94494491/222864452-c4312cec-cf59-49d1-b908-fbc9f1a2c703.png)
![image](https://user-images.githubusercontent.com/94494491/222864493-1b789a0b-1ca2-4528-9081-8912017baac3.png)

</details>

<details>
<summary>Logged in as the new user and replace_user form submitted</summary>

![image](https://user-images.githubusercontent.com/94494491/222864791-fddc2b72-20a5-4aaf-b904-119af933bb27.png)
![image](https://user-images.githubusercontent.com/94494491/222865039-9978a331-65fd-40b4-9975-03f81be517a1.png)

</details>

<details>
<summary>Sentinel was restarted. The old user was deactivated and a new user associated with the replacement user was created. No additional users.</summary>

![image](https://user-images.githubusercontent.com/94494491/222865967-48b67678-2ae7-4d84-9e91-145d34e4c5f6.png)
![image](https://user-images.githubusercontent.com/94494491/222865840-c536c3e3-52c9-470a-a7a2-ed26c0a41ad9.png)

</details>


<details>
<summary>The outgoing message was generated and the login link worked as expected.</summary>

![image](https://user-images.githubusercontent.com/94494491/222866546-c0e468e0-b3ea-40b0-b56c-e772293a7033.png)
![image](https://user-images.githubusercontent.com/94494491/222866711-a4e1f61a-6909-47c9-b767-1f4501f6acc8.png)

</details>

**Closed** 2023-03-07 22:52 UTC
Labels: Type: Improvement
