### ISSUE TITLE
Triggering a stage for a package that doesn't exist causes the upgrade page to freeze

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6602] opened 2020-08-19 14:50 UTC
**Describe the bug**
Trigger a stage through the API for a branch that doesn't have a package anymore. The upgrade page will try to stage and when it gets to the Download section it fails to do anything. The page has no buttons and without the API you are stuck. 

**To Reproduce**
1. ` curl https://user:pass@localhost/api/v1/upgrade/stage -k -X POST -H "Content-Type: application/json" -d '{"build":{"namespace":"medic","application":"medic","version":"'1232-enketo-bundling'"}}'`
2. Watch the upgrades page in the admin app. Eventually gets stuck on downloading and staging install. No further logs or actions. 

**Expected behavior**
The upgrade process should return to listing available updates and discard anything for this attempt to update. 

**Logs**
```
[2020-08-19 14:48:44] Starting Horticulturalist 0.13.1 daemon in Medic OS mode
2020-08-19T14:48:44.589Z horti:debug Running pre-boot checks
2020-08-19T14:48:44.647Z horti:debug Pre-boot checks OK
[2020-08-19 14:48:44] Staging new build: medic:medic:refs/heads/scalability-automation
2020-08-19T14:48:44.652Z horti:stage Horticulturalist deployment of 'medic:medic:refs/heads/scalability-automation' initialising
2020-08-19T14:48:44.652Z horti:stage Skipping: Pre-deploy cleanup
2020-08-19T14:48:44.652Z horti:stage Downloading and staging install
2020-08-19T14:48:44.652Z horti:debug Downloading medic:medic:refs/heads/scalability-automation, this may take some time…
********FATAL********
{ error: 'not_found',
  reason: 'missing',
  status: 404,
  name: 'not_found',
  message: 'missing',
  docId: 'medic%3Amedic%3Arefs%2Fheads%2Fscalability-automation' }
[2020-08-19 14:48:47] Starting Horticulturalist 0.13.1 daemon in Medic OS mode
2020-08-19T14:48:47.503Z horti:debug Running pre-boot checks
2020-08-19T14:48:47.561Z horti:debug Pre-boot checks OK
[2020-08-19 14:48:47] Staging new build: medic:medic:refs/heads/scalability-automation
2020-08-19T14:48:47.565Z horti:stage Horticulturalist deployment of 'medic:medic:refs/heads/scalability-automation' initialising
2020-08-19T14:48:47.565Z horti:stage Skipping: Pre-deploy cleanup
2020-08-19T14:48:47.566Z horti:stage Downloading and staging install
2020-08-19T14:48:47.566Z horti:debug Downloading medic:medic:refs/heads/scalability-automation, this may take some time…
```

**Screenshots**
![image](https://user-images.githubusercontent.com/10531066/90650264-ad66cd00-e209-11ea-84ab-cfa6eaa77976.png)

**Environment**
- Instance: localhost
- Browser: chrome
- Client platform: windows
- App: admin
- Version: 3.10

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by garethbowen** [comment] 2020-08-19 21:27
@newtewt Is this recoverable? Can you use the API to push a version that does exist, or is the instance now bricked?

**Comment by newtewt** [comment] 2020-08-20 13:46
@garethbowen  trying to push master after applying an old branch. Error `Document update conflict.` is returned by API and app is still in broken state.

**Comment by garethbowen** [comment] 2020-08-20 22:05
Right, so this isn't recoverable without manually editing docs in the database. Prioritising...

**Comment by jkuester** [comment] 2021-06-28 14:20
This is ready for AT on https://github.com/medic/horticulturalist/tree/6602-handle-missing-package

To summarize some of the conversation in the PR, the changes in the `6602-handle-missing-package` branch should make it so that if someone tries to upgrade to a package that does not exist, the upgrade will fail and Horticulturalist will exit. BUT, the `horti-upgrade` doc in the database should also be marked as deleted. So, when Horticulturalist restarts it will not try to continue again with the invalid upgrade, but will just start with the last known good version.

**Comment by ngaruko** [comment] 2021-06-29 22:41
Tested with local horti (`node src --dev`). 
When passing a package that does not exit, the upgrade page hangs as reported on this ticket,
![image](https://user-images.githubusercontent.com/6979995/123876006-b9c1c780-d98e-11eb-97fc-301c6a053623.png)

 with following errors:
```
Failed to download build for [medic:medic:non-existing-package]. Aborting install.
  horti:debug Delete deploy ddoc +2s
********FATAL********
{
  error: 'not_found',
  reason: 'missing',
  status: 404,
  name: 'not_found',
  message: 'missing',
  docId: 'medic%3Amedic%3Anon-existing-package'
}
+ app=medic-api
+ echo '[bin/svc-stop] Stopping medic-api...'
[bin/svc-stop] Stopping medic-api...
+ pgrep -f HORTICULTURALIST_APP=medic-api
+ xargs kill
+ app=medic-sentinel
+ echo '[bin/svc-stop] Stopping medic-sentinel...'
[bin/svc-stop] Stopping medic-sentinel...
+ pgrep -f HORTICULTURALIST_APP=medic-sentinel
+ xargs kill
2021-06-30 10:32:24 DEBUG: change event on doc horti-upgrade seq 656-g1AAAAIjeJyV0TEOwjAMAMCIIsECX4AfkCZVCQt04QmwQpK6qqqSDLDDT-An8BP4BHNJ3E4gpHaxJcs-yXZJCBnmQUpGxhqbQmJsbo-n0pV7kqhJVVVFHsjlwRUGMpQ8YuK7-c-4mrqoVo1AUdApVYJBWyHxwq4RxijwUGuWybbC3gvnRtigABBp4HFLwfRdJBeXHHL1yhqViM_DmNFOyq1W7l6ZocJ4DJJ3Ux618vTKFhWRiQXT3TZ61Qre5Y0KFYqC-Plu8QESPqoI 
RES e92913ae-a9f2-46b7-8854-ff712a4a0d3a ::ffff:127.0.0.1 - GET /medic/_changes?feed=longpoll&heartbeat=10000&since=655-g1AAAAIjeJyV0TEOwjAMAMCIIsECX4AfkCZVCQt04QmwQpK6qqqSDLDDT-An8BN4BHtJ3E4gpHaxJcs-yXZJCBnmQUpGxhqbQmJsbo-n0pV7kqhJVVVFHsjlwRUGMpQ8YuK7-c-4mrqoVo1AUdApVYJBWyHxwq4RxijwUGuWybbC3gvnRtigABBp4HFLwfRdJBeXHHL1yhqViM_DmNFOyq1W7l6ZocJ4DJJ3Ux618vTKFhWRiQXT3TZ61Qre5Y0KFYqC-Plu8QESIKoH&limit=25 HTTP/1.1 200 - 1458.172 ms
+ echo '[bin/svc-stop] medic-api stopped.'
[bin/svc-stop] medic-api stopped.
+ echo '[bin/svc-stop] medic-sentinel stopped.'
[bin/svc-stop] medic-sentinel stopped.
bin/svc-start: line 9: 84545 Terminated: 15          node server.js HORTICULTURALIST_APP="$app"
bin/svc-start: line 9: 84542 Terminated: 15          node server.js HORTICULTURALIST_APP="$app"
```

Rerun `node src --dev`
The admin portal seems to suggest that the upgrade was successful 
![image](https://user-images.githubusercontent.com/6979995/123876053-cfcf8800-d98e-11eb-9c00-bfee73fe301d.png)

Reload application: 
No change of branch (as expected)
![image](https://user-images.githubusercontent.com/6979995/123876152-fab9dc00-d98e-11eb-89fb-7bbe68ace7d4.png)

Two issues I see here, one of which might have been considered but maybe hard to implement from a tech perspective,  and that is, is there a way to rather check the package and return an error message, without crashing the app/horti? That would be ideal.
The second issue as seen on the second screenshot, one would expect an 'aborted` message rather than a `successful upgrade`.
Your thoughts @jkuester @mrjones-plip

**Comment by jkuester** [comment] 2021-06-30 14:53
I had discussed this issue a bit with @garethbowen [on the PR](https://github.com/medic/horticulturalist/pull/61#pullrequestreview-689000217) and his thought was:

> One issue with this solution is it won't be obvious in the Upgrade UI or the API response that this failed. However I think this is a good patch to at least make the system recoverable, so I think it's worth committing. We're likely to make significant changes here with CHT v4.0 when we deploy containers rather than ddocs, so I think this'll do for now.

Actually returning an error code on the API response would be a fair bit of new code to add to cht-core (since at this point we don't even check to see if the package exists until we get to the Horti daemon). On the other hand, I don't think it would be too hard to keep Horti from exiting in the case of an invalid package.  Also, I don't think it would be too hard to push a message to the deploy log (displayed on the admin portal) to note that the upgrade was aborted.  We just need to decide if it is worth making any of these updates ahead of the CHT v4.0 changs.

**Comment by garethbowen** [comment] 2021-06-30 16:04
I think we're better off keeping it safe and simple for this release, as @jkuester says, this may all change significantly with the 4.0 release.

**Comment by jkuester** [comment] 2021-07-01 20:52
To summarize, this issue was addressed by updating Horticulturalist to detect when an upgrade has been initiated to a package that does not exist. When that happens, Horticulturalist will mark the `horti-upgrade` doc in the database as deleted (so that it does not continue to try and upgrade to the same missing package).

The resulting UX is still not ideal:

- Horti still exits with an error (but at least now when Horti is restarted, it will not attempt the same upgrade again)
- The admin portal status does not get updated with anything to indicate the upgrade failed. Instead it says `Deployment complete` until Horti restarts everything and the version info gets set back to the original values.
 - The HTTP response to the `api/v1/upgrade` request that cause the issue is still going to be 200 (since we don't know that the package is invalid until the Horti daemon asynchronously tries to download the package. 

At this point, though, we are not prioritizing addressing any of these issues since this upgrade workflow is likely to change substantially with the 4.0 refactoring.

**Closed by jkuester** 2021-07-01 20:52 UTC
Labels: Help wanted, Type: Bug, Upgrading
