### ISSUE TITLE
80% of BRAC feedback documents have cause "Possibly unhandled rejection: {"status":404,"name":"not_found","message":"missing","error":true}"

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6626] opened 2020-08-31 23:45 UTC
**Describe the bug**
Looking at the feedback documents generated for ~1200 BRAC users (30% of total) running v3.9.1 from Aug 23, 2020 to Aug 31, 2020 I'm seeing 4251 total feedback documents 3450 of those (>80%) is a "healthy" part of PouchDB replication
![Screenshot from 2020-08-31 16-40-29](https://user-images.githubusercontent.com/9014751/91778877-c0ce4c80-eba8-11ea-9c27-4915e59f4c53.png)

**To Reproduce**
1. Login to any application as an offline user
1. Sync
1. Look at feedback documents for that user

**Expected behavior**
Feedback documents should not be generated for routine healthy actions. This generates unnecessary network traffic for the end user, adds noise into analysis and makes it more difficult to action on meaningful client-side feedback. 

Can we patch Pouch to void the error? Or can we label the error as safe and skip it? Can we deduplicate redundant feedback docs? etc.

**Logs**
https://brac-ug.app.medicmobile.org/_utils/#database/medic-users-meta/feedback-2010-01-01T00%3A06%3A11.802Z-2daeec41-7c14-4b42-a5e0-9ce1c00daef7

```
{
  "_id": "feedback-2010-01-01T00:06:11.802Z-2daeec41-7c14-4b42-a5e0-9ce1c00daef7",
  "_rev": "1-f6ba633cfa2c184bf40af4eb3399ec13",
  "meta": {
    "time": "2010-01-01T00:06:11.802Z",
    "user": {
      "name": "kawumasu",
      "roles": [
        "district-manager",
        "kujua_user",
        "data_entry",
        "district_admin"
      ]
    },
    "url": "https://brac-ug.app.medicmobile.org/#/about",
    "version": "3.9.1",
    "source": "automatic"
  },
  "info": {
    "message": "missing",
    "cause": "Possibly unhandled rejection: {\"status\":404,\"name\":\"not_found\",\"message\":\"missing\",\"error\":true,\"reason\":\"missing\",\"docId\":\"partners\"}"
  },
  "log": [
    {
      "level": "warn",
      "arguments": "{\"0\":\"db.type() is deprecated and will be removed in a future version of PouchDB\"}"
    }
  ],
  "type": "feedback"
}
```

**Environment**
- Instance: brac-ug.app.medicmobile.org
- App: webapp + medic-couch2pg
- Version: v3.9.1

**Comment by garethbowen** [comment] 2020-09-11 00:43
An untested workaround for this is to create an empty `partners` document.

**Comment by MaxDiz** [comment] 2020-11-18 14:49
bumping to 3.12 to speed up 3.11 progress

**Comment by garethbowen** [comment] 2020-11-30 05:21
Upstream issue raised in pouchdb: https://github.com/pouchdb/pouchdb/issues/8242

**Comment by garethbowen** [comment] 2020-11-30 17:34
In addition to the reproduction steps above, note that it has to be a first time login so clear your local pouchdb first.

As well as confirming there are no new feedback docs on startup, ensure there are no errors in the browser console about "possibly unhandled rejection". There will be some other errors.

**Comment by garethbowen** [comment] 2020-12-03 19:27
This has been merged upstream. I'll keep this issue around so we can AT it when it lands, but no further dev work should be required.

**Comment by garethbowen** [comment] 2020-12-03 22:21
The pouch release won't be included in 3.11 so I've delayed this to 3.12.0.

**Comment by garethbowen** [comment] 2021-05-13 01:56
It's waiting for a PouchDB release. I'll investigate creating a build time patch for this in the meantime...

**Comment by garethbowen** [comment] 2021-05-18 04:05
Ready for AT on `6626-patch-pouch-unhandled-rejection`. Make sure you reproduce this on 3.11.0 or master first, because I found it a little tricky to convince myself it works. Particularly because you have to wait 30 minutes for the meta db to replicate before you see if the error doc exists or not.

**Comment by ngaruko** [comment] 2021-05-25 04:47
Reproducible on `master`
![image](https://user-images.githubusercontent.com/6979995/119439522-a2cbfc00-bd76-11eb-9672-fa3dc33d4fa4.png)

**Closed** 2021-05-30 18:12 UTC
Labels: Priority: 2 - Medium, Type: Bug
