### ISSUE TITLE
Notes get rendered as disabled inputs

### ISSUE THREAD

**Issue by freddieptf** [medic/cht-core#8301] opened 2023-06-06 12:41 UTC
**Describe the bug**
Some notes inside a repeat group that's in the form's summary page are getting rendered as disabled inputs

**To Reproduce**
Form i used to reproduce [note_bug.xlsx](https://github.com/medic/cht-core/files/11664608/note_bug.xlsx)
1. Fill one child's details and check the summary page, notes are rendered okay
2. Before submitting go back and increment the number of children
3. Fill the children details again. 
4. Check summary page and observe some notes for the new children get rendered as disabled inputs

**Expected behavior**
All notes get rendered as notes/simple text

**Screenshots**
![Screenshot from 2023-05-31 19-44-05](https://github.com/medic/cht-core/assets/10602047/96bb2348-8741-4147-b0bc-5f5279e6cc8e)

**Environment**
- Instance: Local development instance, reproduced on v4.1.1 and v4.2.0
- Browser: Firefox 113.0.2 (64-bit)
- Client platform: Ubuntu 18.04.6
- App: cht-conf 3.18.3
- Version: 4.1.1, 4.2.0

**Comment by freddieptf** [comment] 2023-06-06 18:15
The behavior was first reported while testing a PNC form in eCHIS staging instance which runs on v4.1.1 and could be a potential V4 upgrade blocker for [production](https://echis.health.go.ke) which is still on 3.17.0

**Comment by jkuester** [comment] 2023-06-08 22:35
Investigation for this issue is ongoing, but here is an update.  We have been able to re-create the issue. As far as I have been able to figure out so far, it is produced by combining the following circumstances:

- Nested repeats
- Dynamic `repeat_count` values that are evaluated as the form is filled out
- A `calculate` (or perhaps any expression?) in the _inner repeat_ that is dependent on a value produced in another repeat
- Adding a new entry to the _outer repeat_ when an entry already exists that contains an _inner repeat_ with multiple entries

When all of these things come together, it produces [an error in Enekto](https://github.com/enketo/enketo-core/blob/b83271e8cc88fb79ddeb4f79fb1194d2aac9f421/src/js/form-model.js#L1239).  I am still trying to figure out the root cause of this behavior. It seems to be that the logic is getting confused when trying to calculate the value for the new inner repeat group...

I have not been able to recreate this error out on https://getodk.org/xlsform/, but it is not clear yet if this is a bug in the CHT code or an Enketo bug.

**Comment by derickl** [comment] 2023-06-09 08:16
I tested this on the enketo uplift branch and the bug wasn't reproducible.

**Comment by jkuester** [comment] 2023-06-09 16:41
Hmm, here is the minimum form that I have found so far that can produce the bug: [note_bug.xlsx](https://github.com/medic/cht-core/files/11708431/note_bug.xlsx).  I deployed it on a 3.x instance that I [upgraded to the `3.17.0-FR-enketo-upgrade-beta.1` feature release](https://docs.communityhealthtoolkit.org/apps/guides/updates/preparing-for-4/#manual-testing) and I could reproduce the issue on that instance.  :thinking:

**Comment by jkuester** [comment] 2023-06-09 18:13
Okay, I have finally been able to confirm that this issue does NOT happen when running the CHT with enketo-core `7.2.3` (latest).  This also explains why I could not reproduce it out on https://getodk.org/xlsform/.  My guess is that it was fixed as a part of one of these issues (not I am not positive):

- https://github.com/enketo/enketo-core/issues/934
- https://github.com/enketo/enketo-core/issues/818

This means that ultimately this issue will be resolved in https://github.com/medic/cht-core/issues/7599.  That being said, in my investigation I did notice a potential quick hack that seems to mitigate the troublesome behavior here.  We could update the [enketo-repeat-name-collision.patch](https://github.com/medic/cht-core/blob/master/webapp/patches/enketo-repeat-name-collision.patch) to null-check `dataNode` before calling `updateCalc` and this would prevent the Enketo error that ultimately leads to the weird rendering of the notes.  

This is not at all a proper fix and could very possibly have unintended side affects.

**Comment by jkuester** [comment] 2023-06-09 18:37
Also, in the case of this particular form, one workaround would be to eliminate the `r_newborn_danger_signs` inner group and replace it with a series of notes (one for each possible `newborn_danger_signs` value that have their visibility toggled by relevant statements that evaluate if a specific `newborn_danger_signs` value was selected for that patient.  This should avoid triggering the rendering issues seen above.

**Comment by mrjones-plip** [comment] 2023-12-06 18:13
Enketo has been uplifted and I [noted that](https://github.com/medic/cht-core/issues/7599#issuecomment-1717932650):

> confirm the upgrade fixes the bugs mentioned in cht-core#8301

Closing!

**Closed by mrjones-plip** 2023-12-06 18:13 UTC
Labels: Type: Bug, Enketo, Affects: 4.0.0, Affects: 4.1.0, Affects: 4.1.1, Affects: 4.2.0, Affects: 4.0.1, Affects: 4.1.2, Affects: 4.2.1, Affects: 4.2.2, Affects: 4.3.0, Affects: 4.4.0, Affects: 4.2.4, Affects: 4.3.2, Affects: 4.4.1, Affects: 4.2.3, Affects: 4.3.1, Affects: 4.5.0
