### ISSUE TITLE
Ability to view UHC "home visits" in contact summary

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6919] opened 2021-02-11 00:27 UTC
**What feature do you want to improve?**
Contact Summaries.  Muso project team has requested to include "household visit metrics" when viewing households. https://github.com/medic/config-muso/issues/157. They would like to see 1) the number of a days a home visit was made, and 2) the most recent home visit. 

**Describe the improvement you'd like**
Calculating "house visits" requires scanning through all reports at both the household-level and the patient-level reports for all patients in the household.  We currently show these metrics on Muso's contact summaries, but the calculations are inaccurate since only the household reports OR the patient-level reports are available to the contact-summary code. 

**Describe alternatives you've considered**

* Expose more data to the contact-summary code?
* Make this a first-class citizen of the UHC feature-set?
* If the target emissions for the hh visit target were exposed, the contact summary would be able to present an accurate count. In vein with the [targetDoc](https://docs.communityhealthtoolkit.org/apps/reference/contact-page/) parameter, but probably too raw to be friendly.

**Comment by dianabarsan** [comment] 2021-02-11 10:41
> Make this a first-class citizen of the UHC feature-set?

I like this.

**Comment by latin-panda** [comment] 2021-04-12 11:53
Hi @maremegaye @newtewt 

Do you think this feature should be turned off for DB Admins?

Asking because I'm currently working on restricting the feature based on a new permission (can_see_uhc_stats), but when  checking the contact list where we display the visit counts, we're not showing the last visited and visit count [if the user is DB Admin](https://github.com/medic/cht-core/blob/e9e305d2eefed68c3602b2ad69c98e5e0649442d/webapp/src/ts/modules/contacts/contacts.component.ts#L215)

For this feature, we calculate the visits based on 1 contact, not on many contacts, so the process is less heavy.
What do you think?

**Comment by newtewt** [comment] 2021-04-12 13:48
@latin-panda the `_admin` role is pretty reserved to only a few users that we create and you can't assign it via the webapp. I don't know in prod deployments if we have anyone using it but I'd say it would make sense to leave the check.

**Comment by kennsippell** [comment] 2021-04-13 02:00
@latin-panda Did you consider to control this as a new contact-summary field filter. Or as a new type of contact-summary card instead of gating this via the user role?

**Comment by latin-panda** [comment] 2021-04-13 02:44
Hi @kennsippell 

We're passing this information in the same way as we pass `reports`, `contact` objects, it's going to be a new object accessible everywhere in the contact summary script.  Example: `const count = uhcStats.homeVisits.count;`

I'll provide detail information regarding usage once it passes the review, however is this sounding good? :)

**Comment by kennsippell** [comment] 2021-04-13 05:00
@latin-panda At first glance that seems alright. It is rather consistent with the current way of passing data into the contact summaries. But in general, new globals like that increase the mocking required to unit test the contact summary and need to be added into eslint rules etc. Globals are a bit hard to "discover" - only via documentation and not through debugging (if only contact summaries were a function that received inputs instead of a module that has magic globals). 

I'm interested to see what else is in `uhcStats` - it's a fairly specific namespace given that it isn't convenient to have a ton of global inputs. You might consider something more generic like `contactStats` or `contact.uhcStats` or whatever. Gut reaction - I'm also a bit unsure why the `can_see_uhc_stats` permission is necessary - can this just be on whenever uhc is on? One less "trick" to remember - but maybe you have a performance reason or something.

**Comment by dianabarsan** [comment] 2021-04-13 06:25
> If the user can see the stats on the contacts LHS, why shouldn't they see them in the contacts RHS

It was my suggestion to add a separate permission. The point was when someone wants UHC on RHS and doesn't want UHC on LHS (because loading contacts with UHC is significantly slower than without UHC) and not the other way around. 
If you think they'll always be coupled, then we can use the same permissions.

**Comment by latin-panda** [comment] 2021-04-13 09:53
Thank you @kennsippell, I agree there's room for improvements in the usage experience of contact summary, I'm going to bring this topic for further discussions and assessments due to the many projects using the features, let's see the brainstorm. I'll inform back if any news :)
..............
> I'm interested to see what else is in uhcStats

For this ticket, we've added these:

```
{
    lastVisitedDate: number; // Timestamp
    count: number;
    countGoal: number;
}
```

**Comment by latin-panda** [comment] 2021-04-19 04:42
Ready for AT. PRs in order for merging:

- PR @ cht-core: https://github.com/medic/cht-core/pull/7053
- PR @ medic-conf: https://github.com/medic/medic-conf/pull/394
- PR @ cht-docs: https://github.com/medic/cht-docs/pull/472 

Please refer to the [PR @ cht-docs ](https://github.com/medic/cht-docs/pull/472 ) for information regarding usage. 

Note: The issue about calculations being inaccurate in Muso Project couldn't be reproduced by using their current configuration (master branch) and I think it was resolved in [this ticket](https://github.com/medic/config-muso/issues/157), however this new feature facilitates the information access. 
If you would like to use Muso configuration for testing and need help on setting up the user profiles, please refer to [this ticket](https://github.com/medic/config-muso/issues/246). 

Additionally, I've created [a ticket](https://github.com/medic/config-muso/issues/265) in Muso Project for continuity, which can be picked up after this ticket is released.

**Comment by ngaruko** [comment] 2021-05-12 02:00
Tested on local .
The feature requires a little bit of setting to be done. So I will elaborate here for posterity- feel free to pitch in @latin-panda if I missed anything and go ahead and merge away!

1.  Make sure the settings have the `can_view_uhc_stats` permission 
2. Make sure the user has that permission either in settings or via the UI : ``` "can_view_uhc_stats": [
      "chw_supervisor",
      "chw"
    ],```
3. Make sure there a 'uhc" field in the app-settings.json : ```"uhc": {
    "visit_count": {
      "month_start_date": 1,
      "visit_count_goal": 6
    }```
4. Make sure to have `"count_visits": true`  for clinic in `contact_types`: ```"contact_types": [
   ...
    {
      "id": "clinic",
      "name_key": "contact.type.clinic",
      "group_key": "contact.type.clinic.plural",
      "create_key": "contact.type.clinic.new",
      "edit_key": "contact.type.place.edit",
      "parents": [
        "health_center"
      ],
      "icon": "medic-clinic",
      "create_form": "form:contact:clinic:create",
      "edit_form": "form:contact:clinic:edit",
      "count_visits": true
    },```
5. Add `home_visit` form either in the UI or in app/forms (sample [here](https://github.com/medic/config-muso/blob/master/forms/app/home_visit.xml))
6. In the config folder (`cht/config/default` for local testing), add the following or a variation there off , to the fields array in `contact-summary.templated.js` : ```const fields = [

  { appliesToType: 'clinic', label: 'home visits count', value: uhcStats.homeVisits.count || 'none', width: 4 },
  { appliesToType: 'clinic', label: 'home visits Goal', value: uhcStats.homeVisits.countGoal || 'none', width: 4 },
  { appliesToType: 'clinic', label: 'Last Visited date', value: moment(uhcStats.homeVisits.lastVisitedDate).format('dddd MMMM Do YYYY, h:mm:ss a') || 'none', width: 4 },
  { appliesToType: 'clinic', label: 'From: ', value: moment(uhcStats.uhcInterval.start).format(' MMMM Do YYYY')|| 'none', width: 4 },
  { appliesToType: 'clinic', label: 'To: ', value: moment(uhcStats.uhcInterval.end).format(' MMMM Do YYYY')|| 'none', width: 4 },...```
7. upload settings `compile-app-settings  --url= <url> backup-app-settings upload-app-settings`
8. Login as an offine user 
9. Submit a `home_visit` a report for an existing or created household
10. Navigate to the household
11. Observe `home visit` data added to the contact summary

![image](https://user-images.githubusercontent.com/6979995/117907078-42769c80-b32a-11eb-8f73-e3f504e238a7.png)

**Closed** 2021-05-18 02:55 UTC
Labels: Type: Feature
