### ISSUE TITLE
Improve target doc data fidelity - Close gap between last write and end of the reporting interval

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6209] opened 2020-01-20 03:18 UTC
**What feature do you want to improve?**
Webapp v3.8 included a Rules Engine v2 which resulted in documents with type `target` to be written to PouchDB. This document updates a maximum of once per day. An update for the current reporting interval's target document is triggered by the user viewing the tasks/analytics tab, or by a timer which triggers a minute after the app loads. This was a "best-effort" approach to reporting which conservatively prevents writes to the document.

A few scenarios may lead to the target document of a reporting interval to not include a fully accurate summary of the user's target data. For example, if the user navigates to the task/target tab on the day prior to the end of a reporting interval, then creates/edits reports, then views the task/target tab again that day. The document only updates once per day, so it will not recieve the latest updates. The next day is the next reporting period, so the out of date target doc won't be updated. Other scenarios are possible if the user doesn't view the tasks/targets page for several days prior to the end of the reporting period.

**Describe the improvement you'd like**
I'd like to update the target document for the `n`th reporting interval once in the `n+1`th reporting interval.

**Additional context**
This is an existing problem in 3.8 that will impact the fidelity of our impact metrics. I'm scheduling this in 3.9, because Target documents will also be used to drive our DHIS2 workflows. #6002

**Comment by kennsippell** [comment] 2020-03-04 20:43
I attempted a fix for this measurement gap using the method suggested above.

> I'd like to update the target document for the nth reporting interval once in the n+1th reporting interval.

However, this approach is perhaps not viable since it isn't currently safe to aggregate targets for a time interval which is not the current interval. This works fine for target emissions which expicitly set their date attribute, but doesn't work with target emissions which leave the date undefined or which set it to Date.now() (which is the default for declarative configuration).

While investigating, I've discovered that this same issue actually presents in a critical scenario. See #6267. Check out the PR which illustrates the problem a bit more clearly (see the failing test). The resolution for this may be possible depending on how we handle #6267.

**Comment by dianabarsan** [comment] 2020-04-28 09:54
Ready for AT on `6209-recalculate-targets`. 
Recalculation of the old target doc should happen when the reporting interval changes, either if it's while you're logged out or while you're using the app. In order to trigger the target recalculation, you can visit either target or tasks pages.

**Comment by newtewt** [comment] 2020-05-07 17:38
@dianabarsan  I've found an issue with using a function for the Date. I'm using the default config and the target `births-this-month`. If the `date_of_birth` is the first of the month. The target never seems to show. Whether I set my date to last month or later this month. If it's not the first of the month it seems to work.

**Comment by dianabarsan** [comment] 2020-05-07 17:58
@newtewt that sounds like a different issue but I'll look into it. 
Can you please share your exact config for the target?

**Comment by newtewt** [comment] 2020-05-07 17:59
``` 
{
    id: 'births-this-month',
    type: 'count',
    icon: 'icon-infant',
    goal: -1,
    translation_key: 'targets.births.title',
    subtitle_translation_key: 'targets.this_month.subtitle',
    appliesTo: 'contacts',
    appliesToType: ['person'],
    appliesIf: function (contact) {
      return !!contact;
    },
    date: (contact) => contact.contact.date_of_birth,
    dhis: {
      dataElement: 'kB0ZBFisE0e',
    }
  }
```

**Comment by dianabarsan** [comment] 2020-05-08 07:22
@newtewt This is happening on `master` as well, so might be considered a separate issue, as it's affecting targets calculation in general, not just when reporting intervals turn over. 

I can fix it on the same branch and up to you if you want to submit a separate issue or keep it within this.

**Comment by dianabarsan** [comment] 2020-05-08 09:32
@newtewt I pushed a change on `6209-recalculate-targets` that fixes this bug - it was caused by our date comparison not being inclusive. 
The birth date was calculated on 1st at midnight, which was also the start of the reporting interval.

**Comment by newtewt** [comment] 2020-05-08 17:00
I'm seeing this work as expected. On the interval change the previous doc is getting updated. Also the fix for the 1st of the month date report is there as well.  Feel free to close and merge @dianabarsan

**Comment by dianabarsan** [comment] 2020-05-11 10:14
Merged.

**Closed by dianabarsan** 2020-05-11 10:14 UTC
Labels: Analytics, DHIS2, Priority: 2 - Medium, Type: Improvement
