### ISSUE TITLE
Upgrading instance through webapp fails for the first time.

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-core#8502] opened 2023-08-30 16:27 UTC
**Describe the bug**
When upgrade is staged and installed from webapp interface, first installation fails with following message:
```
Error triggering udpate
```

**To Reproduce**
1. Have 4.3.0 instance
2. From webapp, upgrades, select to upgrade instance to 4.3.1. 
3. Once staging is completed, hit `Install` button. 
4. Error is thrown.

**Expected behavior**
Installation should be successful in first attempt. 

**Screen recording**

https://github.com/medic/cht-core/assets/6102813/57eb425f-8745-4cab-9998-37337bb1a990

**Comment by henokgetachew** [comment] 2023-08-30 16:29
Does this mean second attempt works or is it just broken?

**Comment by yrimal** [comment] 2023-08-30 16:33
>Does this mean second attempt works or is it just broken?

Second attempt just works fine without error.

**Comment by henokgetachew** [comment] 2023-08-30 16:35
It's weird that second attempt works but not the first one. I will have a look at this.

**Comment by mrjones-plip** [comment] 2023-08-30 17:55
cc @nydr and @garethbowen - I'm seeing a lot of HTML being returned when JSON is expected in the video above.  Suspect that #8179 will help a lot here, but not sure if addresses the root cause.

**Comment by garethbowen** [comment] 2023-08-30 18:40
There's also a curious http2 error which doesn't make sense to me. The http2 change doesn't exist in the tag so I'm assuming it's something spurious. We need to dig deeper into the actual logs to see what happened.

**Comment by dianabarsan** [comment] 2023-09-05 14:24
Hah, I think there's a bit of a race condition here where, for a brief moment, some of the old containers are still running while others are down and unexpected errors happen. 
When an upgrade is triggered, we just do a `docker-compose up` on updated docker-compose files. This means that docker will recreate the containers concurrently, and there are no rules as to which containers come up or down first. This means that there can be a short moment where the old API is up, while CouchDb is down and throwing that json error (or some other combination). 

I think that the incoming change that updates how haproxy and nginx respond when services are down will maybe fix this.

**Comment by yrimal** [comment] 2023-09-11 08:17
>incoming change that updates how haproxy and nginx respond when services are down will maybe fix this.

Hi @dianabarsan , is there a PR or issue for this? Can you link that here ?

**Comment by dianabarsan** [comment] 2023-09-11 08:19
https://github.com/medic/cht-core/issues/8179

**Comment by garethbowen** [comment] 2023-10-10 16:28
Confirming that this still happens with 4.4.0 -> 4.4.1 so it's not fixed by the issue Diana cited.

**Comment by dianabarsan** [comment] 2023-10-11 07:48
A nice solution would be to check the health of the containers somehow, and validate we are indeed on the right versions, but right now I don't have a solution for this, especially since deployments are either in docker or k8s, we'd need to add an endpoint to some external service that API can reach.

**Comment by garethbowen** [comment] 2023-10-11 18:36
@dianabarsan I see the warning immediately, not after 1 minute, just like in @1yuv 's video. It's displayed behind the dialog but if you close the dialog it's there.

**Comment by mrjones-plip** [comment] 2023-10-11 18:54
> A nice solution would be to check the health of the containers somehow, and validate we are indeed on the right versions, but right now I don't have a solution for this, especially since deployments are either in docker or k8s, we'd need to add an endpoint to some external service that API can reach.

For docker compose deployment, we do [have access to the docker Unix socket](https://github.com/medic/cht-upgrade-service/blob/2beb87895d4f93eec331a0fbc39d60eed3b6081f/docker-compose.yml#L8), so we could tell container state as well as new version image download progress. But yeah, as you already said, - it'd only be for docker compose and not k*s. Since we're trying to migrate away from docker compose hosting - likely not worth pursuing.

**Comment by dianabarsan** [comment] 2023-10-12 06:23
Yea, after further testing I think I know what is happening:
- we update docker-compose files
- we run docker-compose up
- this makes docker download and restart containers in parallel
- haproxy (or other db container) is updated (downloaded and restarted) before API. API restarts because API rage quits when it doesn't have a DB. API believes momentarily that the upgrade has gone wrong somehow. Upgrade continues and old API is eventually killed, new API comes up and everything is fine.

**Closed** 2023-10-14 18:24 UTC
Labels: Type: Bug, Affects: 4.3.0, Affects: 4.4.0, Affects: 4.3.2, Affects: 4.4.1, Affects: 4.3.1
