### ISSUE TITLE
Clicking on contact name in report does not open contact details

### ISSUE THREAD

**Issue by ngaruko** [medic/cht-core#6206] opened 2020-01-17 03:11 UTC
**To Reproduce**
1. Go to 'report.'
2. Click on 'any report'
3. Click name associated with report
4. App goes to main contact page/screen

**Expected behavior**
App should open the actual contact

**Environment**
- Instance: gamma.dev.medicmobile.org
- Browser: Firefox, Chrome, android
- Client platform:  MacOS
- App: webapp, mobile app
- Version: 3.8

**Comment by dianabarsan** [comment] 2020-01-20 08:36
@ngaruko I believe this is a duplicate of https://github.com/medic/cht-core/issues/6149 (which is scheduled in 3.9). Could you please check if it's indeed the case?

**Comment by ngaruko** [comment] 2020-01-20 20:18
Definitely, thanks @dianabarsan

**Closed** 2020-01-20 20:22 UTC
Labels: Type: Bug, Won't fix: Duplicate

**Comment by dianabarsan** [comment] 2020-01-21 05:51
Removed from 3.8, so it won't show up in the release notes as a bug we fixed.
