### ISSUE TITLE
Admin Upgrade Releases section empty when there are no betas

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7320] opened 2021-09-17 10:30 UTC
**Describe the bug**
Initially reported here: https://github.com/medic/medic-projects/issues/8044

If there are no betas to upgrade to, the releases section will be empty, even if there are valid releases to upgrade to. 

**To Reproduce**
1. Deploy 3.12. 
2. Go to admin upgrade page. 
3. Notice that the releases section is empty, even if there is a 3.12.1 release.

![Screenshot_20210917_132753](https://user-images.githubusercontent.com/35681649/133768331-274e1b4e-e8cf-4cac-a36e-f0374e329c3f.png)

**Expected behavior**

3.12.1 should appear under Releases: 

![Screenshot_20210917_132846](https://user-images.githubusercontent.com/35681649/133768443-a4d843a5-0865-4f2d-9362-4796d7ba4809.png)

**Logs**
No errors. 

**Environment**
- Instance: local
- App: admin
- Version: `master`

**Additional context**
It looks like this is a bug in the admin upgrade template, where the condition to show releases incorrectly checks for betas instead of releases: 
https://github.com/medic/cht-core/blob/master/admin/src/templates/upgrade.html#L71-L72

**Comment by latin-panda** [comment] 2021-12-08 16:58
Ready for AT in this [PR](https://github.com/medic/cht-core/pull/7436)

**Comment by ngaruko** [comment] 2021-12-13 01:39
This one is quite tricky to reproduce since there are already a couple of beta releases. But I looking at the [bug and related fix](https://github.com/medic/cht-core/pull/7436/files#diff-85461ad9b22351d4f3c2979575384539c900f5e258ad7037bc3d2e9633c1f823L72), I am confident it is OK. @dianabarsan -
![image](https://user-images.githubusercontent.com/6979995/145739537-fc1689ed-ae46-4dd2-99d9-aa5fb63facf0.png)

**Comment by latin-panda** [comment] 2021-12-13 05:54
Work merged into main branch

**Closed by latin-panda** 2021-12-13 05:54 UTC
Labels: Type: Bug, Configuration, Upgrading, Priority: 2 - Medium
