### ISSUE TITLE
Deleting primary contact from a place will retain that person as a contact when editing. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-core#6478] opened 2020-06-09 15:15 UTC
**Describe the bug**
If a primary contact is deleted from a District Hospital/health center/ etc the contact is deleted. However, when editing that place the primary contact will still show the uuid. Looking at the json doc there is a contact property still associated with the id of the person who was originally the contact. 

**To Reproduce**
1. Create a place with a primary contact.
2. Delete the contact.
3. Edit the place.
4. The primary contact will display a UUID of the delete person. 

**Expected behavior**
The contact should be cleared since the doc is deleted. 

**Environment**
- Instance: gamma.dev
- Browser: Chrome Firefox
- Client platform: Linux
- App: webapp
- Version: 3.9

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by garethbowen** [comment] 2020-08-06 02:28
I think this is a duplicate of #6213 - please reopen otherwise.

**Closed by garethbowen** 2020-08-06 02:28 UTC
Labels: Type: Bug
