### ISSUE TITLE
User stuck on spinner on app load on a poor connection

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#7492] opened 2022-01-28 04:31 UTC
**Describe the bug**
Reported on the forum: https://forum.communityhealthtoolkit.org/t/spinner-loading-forever-without-text-core-v3-11-0/1680
We suspect the cause to be a poor connection to the server, but this was not confirmed. 

**To Reproduce**
1. Create an offline user. 
2. Login with this offline user in a Chrome browser (desktop). 
3. Create a custom network throttling profile so you simulate fantastically high latencies. Enable this throttling profile.
![image](https://user-images.githubusercontent.com/35681649/151487119-d063d233-37b8-41e3-957e-484d0cd724fb.png)
4. Refresh the offline user app. 
5. You're just seeing a spinner for as long as your throttling latency dictates (there are a couple of bootstrap requests). 

**Expected behavior**
A couple of options: 
1. Add a timeout to all "blocking" network requests
2. Always inform the user about what is going on (needs design?). 

**Logs**
No errors. 

**Environment**
- Browser: any
- App: webapp
- Version: *

**Additional context**
I wasn't sure what tag to set, so I'm tagging it as a bug for now, in case someone investigates and finds something that is bugged, outside of connection issues. 
Feel free to adjust as this progresses.

**Why Now?**
Reason(s): Users are unable to access the app during this time and do not know what is going on. This causes a loss in confidence in the app, unnecessary support calls, people are uninstalling the app and unable to reinstall, and consider themselves locked out of the app.

**Comment by mrjones-plip** [comment] 2022-01-28 17:03
> Always inform the user about what is going on (needs design?).

Not sure if it's plausible, but if we are actually connected, but just moving slowly, a progress bar would nice.  If a CHW really needs to connect and can see that it will take 9min to sync, then it will likely be great to know that vs a timeout with no recourse.

Also - will defer to @n-orlowski and @leah-ngaari on what the best UX practice would be in this case!

**Comment by n-orlowski** [comment] 2022-01-28 17:45
[Is this related?](https://github.com/medic/cht-core/issues/4480)

**Comment by mrjones-plip** [comment] 2022-01-28 17:50
Seems related from a UX perspective, most def!  Dunno if it's technically the same thing.  

FYI @michaelkohn - pinging you as the care teams curator \o/

**Comment by garethbowen** [comment] 2022-01-30 22:39
Is this first run only, or can it happen with subsequent loads? The forum post mentions downloading `main.js` which implies the former, but the reproduction steps above just say "refresh" which implies the latter.

If it's first run only then UX improvements are appropriate. If it's second run then we will need to investigate remove the blocking server requests altogether so we're offline-first.

**Comment by dianabarsan** [comment] 2022-01-31 04:15
It does happen with subsequent loads. 
We make some blocking calls to the server during bootstrap and Angular bootstrap.

**Comment by dianabarsan** [comment] 2022-01-31 04:22
> If it's second run then we will need to investigate remove the blocking server requests altogether so we're offline-first.

One example of a blocking startup request is [polling the purging endpoint](https://github.com/medic/cht-core/blob/15ef2b63f07bd9d91989444bbc8fb0acae0e72ae/webapp/src/js/bootstrapper/purger.js#L38). Since we need to do purging on bootstrap, I'm not sure how to avoid this. 

The second example is [calling session](https://github.com/medic/cht-core/blob/15ef2b63f07bd9d91989444bbc8fb0acae0e72ae/webapp/src/ts/services/session.service.ts#L77) [at startup](https://github.com/medic/cht-core/blob/15ef2b63f07bd9d91989444bbc8fb0acae0e72ae/webapp/src/ts/app.component.ts#L268)

**Comment by garethbowen** [comment] 2022-02-14 03:54
I think there are multiple issues being bundled together into one here.

1. I agree that the UX could be better in the ways that @latin-panda mentioned which will greatly improve the first run experience.
2. In addition to those I have particular concerns about the initial replication stage which I suspect could be causing significant issues in production when the connection is dropped before the first batch of docs is returned. If that happens I think the initial replication will start again from 0 because the replication API for Pouch and Couch doesn't store checkpointers for partial batches - you need to fill up the entire batch of 100 docs before Pouch will record progress. Particularly with new users to servers with a lot of historical changes this may take some time.
3. The most concerning this for me in this issue is the subsequent load, rather than the initial load. Not only do subsequent loads happen much more often, they also are more likely to be done where the connection is worse, and where the user is remote and without direct support. To fix this we need to guarantee offline-first capability by fixing the two calls mentioned in [Diana's comment](https://github.com/medic/cht-core/issues/7492#issuecomment-1025366448).

My proposal is that 1 and 2 (and others?) are separated out into separate issues that can be prioritised and shipped independently of this one. This issue can stay representing my number 3 item above.

So, how do we fix item 3?

Firstly I think we can just remove the session check. What that means is we assume a user that has logged in before has a session when the app starts (they almost always do) and just open the app. When the next server request fires (eg: replication) we listen for authentication errors on the response and then redirect the user to the login page. Last time I checked we already to this so, it's an easy fix, just remove the call from bootstrap!

Secondly, the purging is a more complex solution. We don't want to purge in the background because deleting files triggers Angular to update the site which is a performance hit, but also unexpected if the user is about to click on something and it disappears. The change I think we need to make is to modify purging to be two step. The first step is working out what needs to be purged by querying the server and storing the results on the device. The second step is next time the app is started during bootstrap check the docs on the device and purge anything that needs to be purged. To make the first step seamless the docs to purge could be stored in a CouchDB doc in the user's db, so it can be replicated down during normal replication, and the purging API can be deprecated altogether.

This fixes the regression to our offline-first behaviour and means there's nothing blocking in bootstrapping.

@dianabarsan @latin-panda Please let me know what you think!

**Comment by dianabarsan** [comment] 2022-02-14 07:08
Agree with @garethbowen's comment about changing how purging works, and we should spin that up as a different Issue, shipped separately. 
We already have something similar done for purging meta databases, where we determine which docs to delete at runtime, and delete them on next boot.

**Comment by latin-panda** [comment] 2022-02-18 04:37
Ticket addressing # 1 -> The UX: https://github.com/medic/cht-core/issues/7527
Ticket addressing # 2 -> The initial replication: https://github.com/medic/cht-core/issues/7528

This ticket will be just about # 3 -> The improvement of how purging works:

> For me the most concerning part of this issue is the subsequent load, rather than the initial load. Not only do subsequent loads happen much more often, they also are more likely to be done where the connection is worse, and where the user is remote and without direct support. To fix this we need to guarantee offline-first capability by fixing the two calls mentioned in [Diana's comment](https://github.com/medic/cht-core/issues/7492#issuecomment-1025366448).

_Taken form [here](https://github.com/medic/cht-core/issues/7492#issuecomment-1038607050)._

@mrjones-plip is this work about _purging_ allies or care team? 🤔

**Comment by mrjones-plip** [comment] 2022-03-02 22:19
gonna go with care teams!  cc @michaelkohn

**Comment by mrjones-plip** [comment] 2022-03-02 22:20
oh - oop - sorry! I realize it'd already been tagged for care teams...[by me](https://github.com/medic/cht-core/issues/7492#issuecomment-1024463960) :sweat_smile:

**Comment by latin-panda** [comment] 2022-03-07 03:08
Thanks @mrjones-plip! Yes I noticed before it was tagged for care teams, just double checking since we defined the scope of the ticket to improving purging.

**Comment by garethbowen** [comment] 2022-03-09 22:25
Prioritising for 3.15.0 - this is being reported by users.

**Comment by garethbowen** [comment] 2022-03-29 20:36
@latin-panda Online/admin users cannot load the app without the server running by design. We _could_ cache enough so the app would run but because they don't have patient data they wouldn't see any info anyway, so it's not something we've worried too much about. We could make this experience a little nicer by showing a "server unavailable" message or something, but I think it's unrelated to this issue.

> I get the same with offline users if I stop the instance right just after login and I'm redirected to webapp.

I expect that's a timing issue where the service worker cache or initial replication or similar hasn't quite finished before you pull the plug on the server. Does the offline user recover gracefully (either automatically or with a restart) when you start the server up again?

**Comment by latin-panda** [comment] 2022-03-30 03:07
> Does the offline user recover gracefully (either automatically or with a restart) when you start the server up again?

If I have internet and reopen the app then yes, it's maybe an edge case. 

> We could make this experience a little nicer by showing a "server unavailable" message or something

Yes agree, it should stop the spinner and show an error message with some instructions for the user, like "verify the connection" or "try again later".

**Comment by garethbowen** [comment] 2022-03-31 03:41
Ready for AT on `7492-dont-block-on-load`

Follow the reproduction steps in the issue description. The two main changes are:

1. Instead of checking for docs to purge when starting the app up, it now checks in the background when syncing (eg: manually triggering sync through the hamburger menu). If the sync completes the list of items to purge are stored, and the next time you start the app they are deleted from the local database. To test this fully you'll need purging set up.
2. When starting up we used to wait for the server to tell us whether we're online or not. If it didn't connect nothing happened but if the request stalled then the app would wait patiently for a response. Now we still check but we do it in the background (non blocking) so the user can start working. This may mean they get redirected to the login page when the request finally responds which is inconvenient, but we know our users don't get logged out often so it's better to assume they are logged in and have a bad connection and let them do their job.

**Comment by tatilepizs** [comment] 2022-04-06 22:22
**Config:** Default
**Environment:** Local
**Platform:** WebApp 
**Browser:** Chrome

**Test scenario:** I am using for the test the network throttling profile that was suggested in the description.

![image](https://user-images.githubusercontent.com/94494491/162080717-b919c837-f0d3-4773-a09b-c143620e8a91.png)

**Reproducible on** `Master`
When I reloaded the offline user app the spinner was in shown without any message for 2 minutes and 10 seconds

![image](https://user-images.githubusercontent.com/94494491/162081420-f8daf901-b2a6-441a-81e7-242686e72688.png)

**Fixed on** `7492-dont-block-on-load`
When I reloaded the offline user app it took less than a second to actually the into the app again.

**Comment by garethbowen** [comment] 2022-04-07 23:14
Merged!

**Closed by garethbowen** 2022-04-07 23:14 UTC
Labels: Type: Bug, Priority: 1 - High
