### ISSUE TITLE
New users might be prompted to accept the privacy policy twice or shown the tour modal twice

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6960] opened 2021-02-22 19:14 UTC
**Describe the bug**
When a new user logs in (one that is not "known") on an instance that has a privacy policy enabled for the user's language, the user could be prompted to accept the privacy policy twice or be shown the tour twice - in the first 2 consecutive loads (this is a half truth, as things change with different network connection qualities, and the user might see the tour multiple times, but that's not necessarily part of the problem here). 

**To Reproduce**
This is pretty tricky to reproduce reliably, as it requires a race condition to trigger and quick user actions / slow network. 
1. Add a privacy policy for your chosen language.
2. Create a new offline user.
3. Login with this offline user, choosing the language with the privacy policy. 
4. Replicate and accept the privacy policy.
5. Immediately close the tour and all other startup modals (being quick to click is hard!)
6. Reload. 

**Expected behavior**
On next reload, you should see neither the privacy policy nor any of the startup modals (including the tour). 
**If you see either, the bug has happened.**

**Environment**
- Browser: Chrome
- App: webapp
- Version: 3.10, 3.11

**Additional context**
This is caused by a race condition where two actions update the same document, causing a conflict: 
1. Accepting the privacy policy. This edits the user-settings document locally, and relies on replication to upload to the server. '
2. Closing the startup modals. This also edits the user-settings document (setting the `known` property as true), but hits the API endpoint directly, editing the doc directly on the server. 

A local doc edit will trigger upwards replication imemdiately, so it depends on whether this completes before the user closes the tours. 

On next load, the user will perform the required action again (either accepting the policy or closing the tour modal, depending on which rev won) and never have this problem again. 

To repeat testing using the same user, after each try, open the user-settings document (`medic/org.couchdb.user:<username>`) and delete `privacy_policy_acceptance_log` and `known` fields, sync and reload.

**Comment by dianabarsan** [comment] 2021-02-22 19:34
I think the simplest solution would be to change the tour acceptance to edit the local document, instead of calling the server API.

**Comment by garethbowen** [comment] 2021-02-22 19:44
It's strange that it goes straight to the API rather than being offline first...

The UpdateUser service used to be used much more widely because it was shared with the admin app. When we cloned the service into the admin webapp for the angular upgrade the service became only used for changing password and marking as known. Only the change password service needs to go directly to the server, so the webapp version of the UpdateUser service could be simplified a lot so it just handles changing password and nothing else.

**Comment by garethbowen** [comment] 2022-02-15 20:58
Ready for AT in `6960-make-edit-user-settings-offline-first`. Areas to test:

1. First load (and subsequent load) as described in the issue description
2. Hamburger > User settings > Update password - requires internet connection and updates the password directly in CouchDB before updating the session and reloading.
3. Hamburger > User settings > Edit user profile - should update the user offline first so can be done without an internet connection, and updates the CouchDB information on next sync.

**Comment by lorerod** [comment] 2022-02-17 23:33
**Config:** Default
**Environment:** Local with docker helper script
**Platform:** WebApp
**Browser:** Chrome

**Reproducible on Master**
- Initial load. New user is shown the tour modal twice:
https://user-images.githubusercontent.com/21312057/154588150-fe71bce1-791c-4527-b475-25aa1c8617b5.mov

- Initial load. A new user is prompted to accept the privacy policy twice:
https://user-images.githubusercontent.com/21312057/154588510-2f94f6bf-5c4f-4634-a161-3d2dc32d05af.mov

- Edit user profile. Error trying to update user profile offline.
https://user-images.githubusercontent.com/21312057/154588654-e99fd545-b020-4e45-99a4-cd082f1a247f.mov

**Fixed on branch**
- Initial load. On reload, neither the privacy policy nor any of the startup modals (including the tour) are shown:
https://user-images.githubusercontent.com/21312057/154588789-05faf2ae-bbe4-4402-8372-0ce634e7dee8.mov

- Edit user profile successful when been offline:
https://user-images.githubusercontent.com/21312057/154588881-83f8709c-f14a-4704-bc99-ae26f308f3b7.mov

- Update password offline fails as expected:
<img width="604" alt="Update password offline error as expected" src="https://user-images.githubusercontent.com/21312057/154589003-8b6af546-7958-43c1-92ff-ab9a9a1b96c3.png">

- Update password online is successful:
<img width="1142" alt="update password online succesfull " src="https://user-images.githubusercontent.com/21312057/154589078-16aa5895-e0bb-47c0-a990-efb5be2596e2.png">

**Comment by garethbowen** [comment] 2022-02-17 23:39
Merged!

**Closed by garethbowen** 2022-02-17 23:39 UTC
Labels: Type: Bug, Priority: 3 - Low
