### ISSUE TITLE
Two person documents were created when only one should have been

### ISSUE THREAD

**Issue by SCdF** [medic/cht-core#3356] opened 2017-04-07 08:38 UTC
Transplanted from: https://github.com/medic/medic-webapp/issues/3000#issuecomment-292258336

---

The very first time I tested this two people were created:
- [doc 1](https://clone-barefoot.app.medicmobile.org/_couch/_utils/document.html?medic/4e8b44624f528af64152afa72128ebb8)
- [doc 2](https://clone-barefoot.app.medicmobile.org/_couch/_utils/document.html?medic/4e8b44624f528af64152afa72128dbde)

The docs are practically identical, even the `reported_date` is the same down to the ms. The only differences are `patient_id`, and naturally the couch fields (`_id`, `_rev`). The [New Person SMS report](https://clone-barefoot.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/4e8b44624f528af64152afa72128d03f) that created the person has only one `patient_id` attached to it. That form uses the `add_patient` trigger.

I have not been able to reproduce this. Reopening, but we could open a new issue if preferred.

**Comment by SCdF** [comment] 2017-04-07 08:38
@abbyad as I instructed on the other ticket, can you add reproduction steps please.

**Comment by abbyad** [comment] 2017-04-11 15:03
The only steps to reproduce are: 
- submit a form that creates a person (eg `N Marc`)
- hope it reproduces it for the sake of investigating the issue

I'll share the instance privately so that you can see the config.

**Comment by abbyad** [comment] 2017-04-11 15:08
Thought I'd add that you will only know if it is reproduced from the People tab, not the Reports tab. Test with a unique name then search the People to see if you have two with that name.

**Comment by SCdF** [comment] 2017-04-18 14:33
NB: the `reported_date` being the same is not interesting: that value is taken from the registration documentation's date, so it would be the same even if both contacts were created minutes apart

**Comment by SCdF** [comment] 2017-04-18 16:32
Here is the audit log from this fateful day:

---

#### 2017-04-06T17:43:32.002Z "gardener" (aka api) creates report
 - `_rev` is `3` already.
 - Has the contact attached, as run default_responses and update_clinics transitions already, and so has the contact attached
 - This exposes a bug IMO, because we are clearly storing documents against the DB without running it through audit. This makes this timeline reconstruction stuff more challenging.

#### 2017-04-06T17:43:34.918Z gardener creates 97020

#### 2017-04-06T17:43:35.419Z (+3s) marc edits report
 - updates the doc with his read status (thanks!)
 - confusingly, the same `_rev`
 - *and* a `_revisions` field, which should only be returned when you specifically ask for that information.
 - I'm guessing this probably means a conflict, though there is no information *missing*, only the read status added

#### 2017-04-06T17:43:38.602Z gardener creates 25173

#### 2017-04-06T17:43:38.944Z (+3s) gardener edits report
 - updates it again, as a result of being read by sentinel
 - new `_rev` (yay!)
 - Here the registrations transition is being run, which generates tasks (sms), and has attached the `25173` `patient_id` to this document

---

It's a bit hard to tell what's going on because the first two revisions of the document are not in the audit log.

My best guess is that this is because of a conflict:
 - Document gets created and some transitions run: `registration` is not a valid transition until `update_clinics` has attached the contact so it's not run yet
 - Now `registration` is valid it runs, does everything it should do including creating a contact.
 - At the same time Marc views the document, causing a conflict
 - In this instance Marc's read won as the correct version
 - Sentinel runs over Marc's read version, and then `registration` is run again, which causes another contact to be created.

**Comment by SCdF** [comment] 2017-04-18 16:39
Here are some ideas for solving this:
 - Add a `created_from` field in contacts that point to the report that created them. Add a view for this field. When determining if you need to create a patient contact also check this view, and re-attach if it was lost due to a conflict
 - Pull out read statuses from the main document so they don't generate conflicts
 - Actively manage conflicts: notice conflicts and resolve them correctly using rules that we create, flagging ones we couldn't actively manage as bugs in the system (worst case throw things to console, best case automatically raise tickets somewhere)

**Comment by SCdF** [comment] 2017-04-19 10:21
@abbyad what are your thoughts here? I see that managing conflicts properly is a in the Q2 goals document. Should we just leave it at that?

**Comment by abbyad** [comment] 2017-04-21 00:18
Thanks for the detailed analysis! Seems as though option 1 could be useful regardless, so if that is a "quick" solution it may be worthwhile in case conflict management isn't done until much later. We can see with @sglangevin how this fits with Q2 priorities.

**Comment by abbyad** [comment] 2017-04-27 01:41
Just noting that had this occur again on a 2.11.0 instance:
- [doc 1](https://clone-barefoot.app.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/2403111f9f4bdee781b8dcf37116fe62)
- [doc 2](https://clone-barefoot.app.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/2403111f9f4bdee781b8dcf37116f548) - _which I have since moved to another place because it looked bad in my demo_

**Comment by SCdF** [comment] 2017-05-05 12:37
@abbyad thinking about it again, I actually think the second idea is a pretty bad idea. Views are expensive, and we're creating an entirely new view, so support a hack to fix an edge case we should be solving through good software development.

I really think pulling read status out is the right move here. We should be doing it regardless, it's crazy to replicate an entire document just to mark someone as read.

Another right move would be to see how feasible it would be to refactor sentinel's transition processing so it operates as a "transaction", i.e. instead of storing an additional document and then potentially failing to store the main one, save them all together in the same call to CouchDB, and roll the others back and restart if any conflict.

**Comment by sglangevin** [comment] 2017-05-11 18:10
After talking with @abbyad we decided to deprioritize this for now to see if work on some other bugs might resolved this. Moving out of the iteration for now and continuing to track alongside other bugs.

**Comment by sglangevin** [comment] 2017-07-06 19:00
@SCdF this issue has resurfaced: https://github.com/medic/medic-projects/issues/2427

Since read status will be removed from the doc in v2.13.0, I'm guessing we should test this again in v2.13.0 and see if the problem goes away? We can't reliably reproduce it so it's probably to do with Sentinel and conflicts if I had to guess.

**Comment by garethbowen** [comment] 2023-08-22 23:26
Closing as ancient.

**Closed by garethbowen** 2023-08-22 23:26 UTC
Labels: Type: Bug
