### ISSUE TITLE
Contacts moved by "medic-conf move-contacts" do not disappear from user's device and synchronization of any changes fail silently 

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#5701] opened 2019-05-30 22:16 UTC
**Describe the bug**
Medic-conf 2.0.5 supports moving contacts within the hierarchy via the action "move-contacts".  When an offline user has downloaded the details for some contacts which are then removed from that position of the hierarchy, the contacts do not disappear. The contact remains on the user's device, but any updates made to the contact (or any reports created for that contact) will silently fail to sync. This can result in silent data loss. 

Known fix is for the offline user to clear cache and perform a clean synchronization. However, it is not straightforward to drive all contacts to complete this task. 

**To Reproduce**
1. Given offline user with `facility_id='health_center_1'` which has child `clinic_1`. 
1. Log in as user 
1. Edit contact under `clinic_1` and resync 
1. `medic-conf move-contacts upload-docs parent=health_center_2 clinic_1` 
1. Synchronize as user 
1. Edit contact again under `clinic_1` and resync 

**Expected behavior**
The edits made by this user should sync or an error should appear so the user knows the data did not sync. Ideally, these documents should be removed from the client's device. 

Observed: Documents remain. Synchronization of data fails silently.

**Comment by kennsippell** [comment] 2019-05-30 22:22
Some ideas about how to approach this problem from @garethbowen at https://github.com/medic/medic-conf/issues/172#issuecomment-496422612

**Comment by garethbowen** [comment] 2019-11-25 22:14
This is a different take on a long standing issue so I'm comfortable to push this to 3.9.0

**Comment by kennsippell** [comment] 2020-01-09 08:49
This is a very hard issue to fix.

I suspect the conversation for this issue should resolve around:

1. a resolution of `won't fix`
1. how to communicate this limitation to admins
1. how to communicate to users when their device's state should be cleared and re-synced

I'm unclear how to specificaly action on this bug in 3.9. It is perhaps a good topic over beers for the product team meetup...

**Comment by SCdF** [comment] 2020-01-09 12:44
As this was a known complication before this script was written (and was one of the reasons the script was seen as a large challenge, resulting in it not being written up until now), I think by creating this script we have legitimised this as a bug that needs to be fixed.

**Comment by garethbowen** [comment] 2020-02-13 22:58
I'm blocking this issue because we're not sure if the purging solution is desirable. I think this needs to be looked at by a Product Owner.

**Comment by MaxDiz** [comment] 2020-02-20 04:46
de-prioritizing from 3.9 until we have team resources to review. Added to the the App Builders backlog for prioritization

**Comment by garethbowen** [comment] 2020-08-06 00:46
Closing as a duplicate of #6544

**Closed by garethbowen** 2020-08-06 00:46 UTC
Labels: Blocked: waiting for design, Priority: 2 - Medium, Type: Bug
