### ISSUE TITLE
Xform rendering hides choices when relevance condition and choice filter are applied to a secondary question

### ISSUE THREAD

**Issue by kitsao** [medic/cht-core#5636] opened 2019-05-03 13:21 UTC
**Describe the bug**
Choices for a secondary `select_one/select_multiple` field do not show when both relevance condition and choice filter are applied. Consider the following design xls immunization section:

| Question/Note/Label  | Type | Required | Choices | Condition (Relevance/Show only if + Constraints/Validation) |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Select the vaccines that were given on {{date}} *Tick every condition/symptom that applies*  | select_multiple  | yes  | BCG, Birth Polio (OPV 0), OPV, PCV, DPT-HepB-Hib, IPV, Rota, Vitamin A, Measles  | Don't show vaccines already reported. Birth Polio(OPV 0) if age <= 2weeks, OPV, PCV, Rota and DPT-HepB-Hib  if age >= 6 weeks, Vit A if age >= 6 months, Measles if age >= 9 months  |
| Select which dose of OPV was given on {{date}}  | select_one  | yes  | OPV 1/2/3  | If OPV is selected. Show OPV 2 if age >= 10 weeks, OPV 3 if age >= 14 weeks. Don't show doses already reported.  |
| Select which dose of PCV was given on {{date}}  | select_one  | yes  | PCV 1/2/3  | If PCV is selected. Show PCV 2 if age >= 10 weeks, PCV 3 if age >= 14 weeks. Don't show doses already reported.  |
| Select which dose of DPT-HepB-Hib was given on {{date}}  | select_one  | yes  | DPT-HepB-Hib 1/2/3  | If DPT-HepB-Hib is selected. Show DPT-HepB-Hib 2 if age >= 10 weeks, DPT-HepB-Hib 3 if age >= 14 weeks. Don't show doses already reported.  |
| Select which dose of Rota was given on {{date}}  | select_one  | yes  | Rota 1/2  | If Rota is selected. Show Rota 2 if age >= 10 weeks. Don't show doses already reported.  |
| Select which dose of Measles was given on {{date}}  | select_one  | yes  | Measles 1/2  | If Rota is selected. Show Measles 2 if age >= 18 months. Don't show doses already reported.  |

**To Reproduce**
1. Configure the above, a sample can be found [here](https://docs.google.com/spreadsheets/d/1rMD49QfSO-xHSjt3MZ5vBZqy-RggU_deVh6kMZ0fCKc/edit#gid=1042357020)
2. Convert and upload the form and pick a client profile to complete it
3. The behavior in the image below is observed, doses do not show
![image](https://user-images.githubusercontent.com/3928714/57144422-b9870b00-6dc9-11e9-9c96-a8a8a9e4fd44.png)

**Expected behavior**
The expected behavior is to have the doses (choices) showing appropriately, as shown below. This happens when I either remove the relevance condition or the choice filter.
![image](https://user-images.githubusercontent.com/3928714/57144766-75483a80-6dca-11e9-9a4c-5833dc8e5ad6.png)

**Logs**
No logs on browser console.

**Screenshots**
See captures above.

**Environment**
- Instance: _pih-malawi.dev.medicmobile.org_
- Browser: _Chrome_
- Client platform: _Linux_
- App: _webapp_
- Version: _3.4.0_

**Additional context**
This was experienced in _3.3.0_ too. The workaround applied is merging vaccines and doses, i.e. instead of asking to select dose say for OPV, have vaccines as OPV 1, OPV 2 and OPV 3 ...

cc @derickl @smbuthia 

**Why Now?**
Partner(s): Internal
Reason(s): A partner will have CHWs/Supervisors with a detrimental experience, thus providing bad care

**Comment by SCdF** [comment] 2019-05-07 08:20
Worked in 2.14 / 2.x. We should work out which version of Enketo broke this, and if it's been subsequently fixed in a later version.

**Comment by wtekeu** [comment] 2019-08-05 20:06
@kitsao Thanks for sharing the sample but it fails to load .. 
<img width="1105" alt="Screen Shot 2019-08-05 at 4 03 15 PM" src="https://user-images.githubusercontent.com/1445164/62491763-d7825400-b79a-11e9-8ff8-8b0f73a3a2ff.png">

has the form been updated?
(`pih-malawi.dev.medicmobile.org` produces `502`)

**Comment by garethbowen** [comment] 2019-08-05 22:51
Possibly related: #4249

**Comment by Hareet** [comment] 2019-08-06 05:25
@wtekeu 
`pih-malawi.dev.medicmobile.org` is back up. Please check again.

**Comment by wtekeu** [comment] 2019-08-20 00:11
@kitsao After doing some research, it looks like this is due to the use of the following skip logic:
`<bind nodeset="/under_5_screening/vaccines_given/visit_details" relevant="../visits_reported != 0"/>`
When you remove this line it does work. Can you think of an alternative way to build the skip logic?

**Comment by abbyad** [comment] 2019-09-03 16:06
@wtekeu does it work with different relevant conditions, such as `relevant=true()`?

**Comment by wtekeu** [comment] 2019-09-09 18:36
@abbyad it does work but if you select `Zero` immunization to report then click on `Next` then back with `Prev` then select `One` immunization to report it does not work.

**Comment by wtekeu** [comment] 2019-09-09 18:38
But when you remove the line, it works in both cases. The only drawback is that if you select `Zero` you get a blank page with just the title of the form and the buttons `Prev', `Next` and the link `Cancel`

**Comment by abbyad** [comment] 2019-09-09 20:57
Are you confirming that a valid `relevant` statement doesn't work as expected? Is this related to our version of Enketo, or Enketo proper? It would be good for us to handle this rather than not using relevant statements.

**Comment by garethbowen** [comment] 2019-10-01 02:34
Bumped to 3.8.0 so it doesn't hold up the release.

**Comment by garethbowen** [comment] 2019-12-10 23:56
No update for some time. Bumping.

**Comment by garethbowen** [comment] 2020-05-26 00:12
Moved to 3.12.0 to free up engineers to work on 3.11.0.

**Comment by mrjones-plip** [comment] 2022-02-02 21:09
@jkuester - can you tell if the enketo uplift in 4.0 will fix this? If yes, I'll move it there. Thanks!

**Comment by jkuester** [comment] 2022-03-16 16:48
@garethbowen shoot! This fell off my radar somehow.

@kitsao, sorry to resurrect this ancient history, but I am having some trouble recreating this and was wondering if you could give me access to the Google xlsx form that you linked in the original issue (if it still exists).  I have requested access via the link already.  I tried cobbling together a form based on a combination of the PIH `under_5_screening` and `immunization` forms, but even the earliest versions of those forms in the medic repos appear to have already been refactored to fix the issue....

**Comment by jkuester** [comment] 2022-03-16 18:46
Okay, spoke too soon!  I realized that my test form did not have anything set for the `choice_filter`.  I am now able to recreate this behavior.  TLDR is that this issue appears to have been fixed by the Enketo uplift!

Here is the most basic config that I have come up with that demonstrates the issue:

type | name | label::en | relevant | appearance | choice_filter | repeat_count
-- | -- | -- | -- | -- | -- | --
begin group | my_group | NO_LABEL |   | field-list |   |  
integer | question_count | Repeat Count |   |   |   |  
begin repeat | my_repeat | NO_LABEL | ${question_count} != 0 |   |   | ${question_count}
select_one yes_no | my_question | You should be able to see the choices | true() |   | true() |  
end repeat |   |   |   |   |   |  
end group |   |   |   |   |   |  

The best I can tell, what seems to be happening in the old version of Enketo is that the order of evaluations gets confused so the `choice_filter` value is not properly evaluated for questions inside a `repeat` when the repeat's `relevant` and `repeat_count` logic are both calculated (yeah the chain of dependencies here is mind-numbing).

This is what I see when running the above form on `3.4`:
![image](https://user-images.githubusercontent.com/8441903/158664399-4cb4bc48-7ccc-47c2-a248-3cfc18297997.png)

And this is what I see on [`6345-enketo-uplift`](https://github.com/medic/cht-core/tree/6345-enketo-uplift):
![image](https://user-images.githubusercontent.com/8441903/158664578-faa5464c-b824-4b47-b790-e910ec6f8a22.png)

**Comment by jkuester** [comment] 2022-07-25 22:42
@medic/quality-assurance this issue is ready for AT on https://github.com/medic/cht-core/pull/7256

**Comment by jkuester** [comment] 2022-08-16 15:47
@tatilepizs here is the xml for a sample for that you can use to test this behavior:

```.xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms">
  <h:head>
    <h:title>Enketo Widgets</h:title>
    <model>
      <itext>
        <translation lang="en">
          <text id="/enketo_widgets/my_group/my_repeat/my_question:label">
            <value>You should be able to see the choices</value>
          </text>
          <text id="/enketo_widgets/my_group/question_count:label">
            <value>Repeat Count</value>
          </text>
          <text id="static_instance-yes_no-0">
            <value>Yes</value>
          </text>
          <text id="static_instance-yes_no-1">
            <value>No</value>
          </text>
          <text id="static_instance-yes_no-2">
            <value>Don't Know</value>
          </text>
          <text id="static_instance-yes_no-3">
            <value>Not Applicable</value>
          </text>
        </translation>
      </itext>
      <instance>
        <enketo_widgets id="enketo_widgets" prefix="J1!enketo_widgets!" delimiter="#" version="2022-08-16 00:00:00">
          <my_group>
            <question_count/>
            <my_repeat_count/>
            <my_repeat jr:template="">
              <my_question/>
            </my_repeat>
          </my_group>
          <meta tag="hidden">
            <instanceID/>
          </meta>
        </enketo_widgets>
      </instance>
      <instance id="contact-summary"/>
      <instance id="yes_no">
        <root>
          <item>
            <itextId>static_instance-yes_no-0</itextId>
            <name>yes</name>
          </item>
          <item>
            <itextId>static_instance-yes_no-1</itextId>
            <name>no</name>
          </item>
          <item>
            <itextId>static_instance-yes_no-2</itextId>
            <name>dk</name>
          </item>
          <item>
            <itextId>static_instance-yes_no-3</itextId>
            <name>na</name>
          </item>
        </root>
      </instance>
      <bind nodeset="/enketo_widgets/my_group/question_count" type="int"/>
      <bind nodeset="/enketo_widgets/my_group/my_repeat_count" type="string" readonly="true()" calculate=" /enketo_widgets/my_group/question_count "/>
      <bind nodeset="/enketo_widgets/my_group/my_repeat" relevant=" /enketo_widgets/my_group/question_count  != 0"/>
      <bind nodeset="/enketo_widgets/my_group/my_repeat/my_question" type="select1" relevant="true()"/>
      <bind nodeset="/enketo_widgets/meta/instanceID" type="string" readonly="true()" calculate="concat('uuid:', uuid())"/>
    </model>
  </h:head>
  <h:body class="pages">
    <group appearance="field-list" ref="/enketo_widgets/my_group">
      <input ref="/enketo_widgets/my_group/question_count">
        <label ref="jr:itext('/enketo_widgets/my_group/question_count:label')"/>
      </input>
      <group ref="/enketo_widgets/my_group/my_repeat">
        <label ref="jr:itext('/enketo_widgets/my_group/my_repeat:label')"/>
        <repeat nodeset="/enketo_widgets/my_group/my_repeat" jr:count=" /enketo_widgets/my_group/my_repeat_count ">
          <select1 ref="/enketo_widgets/my_group/my_repeat/my_question">
            <label ref="jr:itext('/enketo_widgets/my_group/my_repeat/my_question:label')"/>
            <itemset nodeset="instance('yes_no')/root/item[true()]">
              <value ref="name"/>
              <label ref="jr:itext(itextId)"/>
            </itemset>
          </select1>
        </repeat>
      </group>
    </group>
  </h:body>
</h:html>
```

**Comment by tatilepizs** [comment] 2022-08-16 16:58
**Config:** Default
**Environment:** Local with docker helper script
**Platform:** WebApp
**Browser:** Chrome

---

The file used to test was provided by @jkuester in [this comment](https://github.com/medic/cht-core/issues/5636#issuecomment-1216820378)

### Reproducible on `Master`
Options are not shown.

<details>
<summary>Desktop</summary>

![image](https://user-images.githubusercontent.com/94494491/184934575-c8ae467f-f16d-42c6-a279-86dd70c6b9a8.png)

</details>

<details>
<summary>Mobile</summary>

![image](https://user-images.githubusercontent.com/94494491/184935952-69b679d1-f2c0-4db0-b9b8-4be2f8ccccea.png)

</details>

### Fixed on `6345-enketo-uplift`
Options are shown successfully.

<details>
<summary>Desktop</summary>

![image](https://user-images.githubusercontent.com/94494491/184934647-03371b4b-8ea2-42ca-903e-9e5024285540.png)

</details>

<details>
<summary>Mobile</summary>

![image](https://user-images.githubusercontent.com/94494491/184936284-e980abbd-2112-469c-a568-78fdf8707314.png)

</details>

**Closed** 2022-08-16 19:02 UTC
Labels: Type: Bug, Enketo, Priority: 2 - Medium
