### ISSUE TITLE
If multiple task documents are created with the same emission._id, only one of them is ever updated

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-core#6389] opened 2020-05-01 17:21 UTC
**Describe the bug**
In the MSF-Niger [production](https://alerte-covid19-ne.net/) instance, two task documents have been created from the same report and share the same `emission._id` attribute. It is unknown what circumstances lead up to this exactly -- but it is possible for this to result if multiple sessions login on different devices.

1. This "same task" appears multiple times in the task list
1. When the user completes the steps to resolve the task -- only one of the multiple tasks disappears

**To Reproduce**
I'm not sure of the steps that lead to multiple task documents being created in this case. 

* `task~org.couchdb.user:riposte1~665c19fe-3c27-4209-950e-a070a4e5bf36~0~samu_yields_ripostefollowup_red~1588242822845`
* `task~org.couchdb.user:riposte1~665c19fe-3c27-4209-950e-a070a4e5bf36~0~samu_yields_ripostefollowup_red~1588242869125`

**Expected behavior**
* The same task emission should never result in multiple tasks in the UI
* Either duplicate task documents need to be deduplicated via cancellation, or all task documents should recieve updates when emission details change.

**Environment**
- Instance: Production MSF-Niger https://alerte-covid19-ne.net/
- Browser: All
- Client platform: All
- App: core
- Version: custom. Confirmed repo on 3.8.1

**Comment by kennsippell** [comment] 2020-05-01 17:21
When multiple task documents exist, one is updated and the others are left dangling in their initial state and receives no updates. I believe this is happening [here](https://github.com/medic/cht-core/blob/master/shared-libs/rules-engine/src/refresh-rules-emissions.js#L42) where the task emission is mapped to a single task document for updates. This does not account for the scenario where multiple task documents have been created for the same emission.

**Comment by kennsippell** [comment] 2020-05-01 20:39
We have worked around this issue for MSF-Niger by issuing guidance to not login to the same account on multiple devices, and by creating new user accounts for affected users.

**Comment by senseibara** [comment] 2020-05-01 21:27
To reproduce this bug, pick any user and connect with the same credentials on 2 separate devices ( potentially separate browser should be okay but not tested). 

We assume that the user will replicate the source doc from the server ( submitted by another user) 

1. On Device 1 Sync one time, and check in the task tab that a task was triggered 
2. On Device 2 Sync one time, and check in the task tab that a task was triggered 

It's important to do 1 & 2 at the same time, after both are done we suppose that a task document has been created on pouch in both Device 1 and Device 2 but none of these task documents have synced to the server yet. 

3. Sync on Device 1
4. Sync on Device 2

do 3&4 in the same time and go check in medic db by using the task id, you will notice that 2 different documents have been created for the same task with different `authoredOn` timestamp. 

5. Submit one of the task , it will not disappear and you will see in couch that one of the document was updated with the completed status, and the other one will be not.

**Comment by garethbowen** [comment] 2020-05-03 22:06
I think this is worth fixing in 3.9.0 as it'll frustrate the users and presumably lead to duplicate reporting as they try and clear the task.

**Comment by dianabarsan** [comment] 2020-05-05 12:43
> The same task emission should never result in multiple tasks in the UI
> Either duplicate task documents need to be deduplicated via cancellation, or all task documents should recieve updates when emission details change.

As I understood it, we're appending a timestamp (representing the date the task was calculated at) at the end of the task document _id _because_ we were not sure whether some configurations emit unique emission ids. 
If we choose now to dedupe or cancel these duplicated tasks, are we not essentially undoing what the _id timestamp suffix was trying to achieve?

**Comment by garethbowen** [comment] 2020-05-11 22:48
Read for AT in `6389-dedupe-tasks`. Test #6417 at the same time.

**Comment by dianabarsan** [comment] 2020-05-12 06:29
This is going to be a lot harder to replicate because we now sync immediately when local changes happen.

**Comment by newtewt** [comment] 2020-05-19 15:45
I can no longer reproduce the issue described above. Disabling the network and try also to no avail. I'm seeing tasks cleared when the sync occurs on both browsers. Tasks are clearing appropriately as well. I don't see duplicates in the couchdb either. I think we can close and merge both related tasks @dianabarsan

**Comment by dianabarsan** [comment] 2020-05-19 16:24
@newtewt I can prepare 2 custom builds for you, a `master` version that removes the instant sync and the my proposed version that removes the instant sync, if you'd like to compare the two.

**Comment by newtewt** [comment] 2020-05-19 16:27
I think disabling the network in your branch is enough to disable instant sync right?  By not being able to reproduce the issue. I was able to before applying your branch and after I could no longer(fixed). My initial comment wasn't very clear.

**Comment by dianabarsan** [comment] 2020-05-19 16:27
I just thought of another way of simulating. Change your users so they can't edit (set the `can_edit` permission to false, to stop the upwards sync), create the report on the server, sync down on 2 clients. they will both generate tasks, just not upload them. Change permission so they `can_edit` and have them both sync u twice. Maybe that will get both of them to upload and generate tasks and then the duplicate "clear" should be visible.

**Comment by dianabarsan** [comment] 2020-05-19 16:28
Ah cool! :D I completely misunderstood. If the tasks got duplicated. there should be duplicates in CouchDB though.

**Comment by dianabarsan** [comment] 2020-05-19 16:54
Merged.

**Closed by dianabarsan** 2020-05-19 16:54 UTC
Labels: COVID-19, Priority: 1 - High, Type: Bug
