### ISSUE TITLE
Update default/standard config forms so they pass validation

### ISSUE THREAD

**Issue by jkuester** [medic/cht-core#7738] opened 2022-08-19 19:41 UTC
After the [recent updates](https://github.com/medic/cht-conf/issues/462) to cht-conf to validate forms, some of the sample forms provided with cht-core are now failing validation. They should be updated to conform to the latest standards.

**Comment by jkuester** [comment] 2022-08-29 14:51
This is ready for AT on [7738_fix_sample_form_validate](https://github.com/medic/cht-core/tree/7738_fix_sample_form_validate). There were no changes to the actual production code (just to the sample forms), so I am not sure exactly how much AT we actually do for this scenario.  That being said, these are the forms that were changed:

### Default config

- app
    - death_report
    - delivery
    - pnc_danger_sign_follow_up_baby
    - pregnancy
    - pregnancy_danger_sign_follow_up
    - pregnancy_home_visit
    - undo_death_report
- contact
    - clinic-create
    - clinic-edit
    - district_hospital-create
    - district_hospital-edit
    - health_center-create
    - health_center-edit
    - person-create
    - person-edit

### Standard config

- app
    - child_health_registration
    - delivery

**Comment by tatilepizs** [comment] 2022-08-31 22:07
@jkuester, I started to test this ticket, the default config was uploaded successfully with no issues 🎉 
But when I started to test the forms I saw that it is failing when I tried to edit a person.

![image](https://user-images.githubusercontent.com/94494491/187793544-1571b0f2-81d4-42a4-bd37-6193040556bf.png)

I checked in `master` happens the same, it fails when I try to edit a person.

Could you please check?

**Comment by jkuester** [comment] 2022-09-06 15:22
@tatilepizs I was not able to reproduce this error locally.  Out of curiosity, were running the latest cht-core code from from `7738_fix_sample_form_validate` (or at least from `master`)?  The `add-date` function from the error was very recently added to `master` and will not be present in other releases/branches...

**Comment by tatilepizs** [comment] 2022-09-06 15:39
I think that yes, I saw that error using `7738_fix_sample_form_validate` and `master`, and then I tried with `3.16` and in there I didn't see the error. 
But I will try again to be 100% sure, I will let you know. Thanks!

**Comment by tatilepizs** [comment] 2022-09-06 15:49
@jkuester you are completely right, I don't know what I did last time, but now I am not able to reproduce it.
Sorry for the confusion.

**Comment by tatilepizs** [comment] 2022-09-06 16:54
Using cht core version `7738_fix_sample_form_validate` the configs `default` and `standard` were uploaded successfully.

Tested forms for `default` config:
- district_hospital-create
- district_hospital-edit
- health_center-create
- health_center-edit
- clinic-create
- clinic-edit
- person-create
- person-edit
- pregnancy
- pregnancy_home_visit
- pregnancy_danger_sign_follow_up
- delivery
- pnc_danger_sign_follow_up_baby
- pnc_danger_sign_follow_up_mother
- death_report
- undo_death_report

Tested forms for `standard` config:
- district_hospital-create
- district_hospital-edit
- health_center-create
- health_center-edit
- clinic-create
- clinic-edit
- person-create
- person-edit
- pregnancy
- pregnancy_visit
- delivery
- child_health_registration
- nutrition_screening

**Closed** 2022-09-06 20:04 UTC
Labels: Type: Improvement
