### ISSUE TITLE
Values of non-relevant fields should be maintained until submission

### ISSUE THREAD

**Issue by abbyad** [medic/cht-core#4132] opened 2018-01-25 22:54 UTC
~As reported in https://github.com/medic/medic-webapp/issues/4111#issuecomment-360304644, clearing non-relevant fields while completing a form is problematic.~

My understanding of `relevant` in the [ODK specification](https://opendatakit.github.io/xforms-spec/#bind-attributes) is that the fields should only be removed when submitting the report, making their values accessible while still editing the form:
> `relevant`: Specifies whether the question or group is relevant. The question or group will only be presented to the user when the XPath expression evaluates to true(). When false() the data node (and its descendants) are removed from the primary instance on submission.

~Removing the non-relevant fields while editing a form seems to have appeared in the way we use Enketo between 2.13 and 2.14. Aside from improving the user experience, many active projects use forms that depend on this characteristic, likely making this a blocker for 2.14.~

_**Edit:** This is not new, as earlier versions exhibit this problem as well._

cc @sglangevin

**Comment by abbyad** [comment] 2018-01-26 23:17
It looks like the only benefits of this are for UX and being ODK XForm compliant. Contrary to previously reported we are not already relying on this functionality.

**Comment by vimemo** [comment] 2018-02-26 15:54
Assigning a low priority on this issue since we do not rely on this functionality at the moment.

**Comment by garethbowen** [comment] 2022-07-25 05:33
@jkuester Can you verify if this is fixed with the latest Enketo?

**Comment by jkuester** [comment] 2022-07-25 20:34
Short answer is yes, this is "fixed" by https://github.com/medic/cht-core/pull/7256 as was pointed out [here](https://github.com/medic/cht-core/issues/6345#issuecomment-1164635324).  However, as was mentioned in that issue thread, the way this is "fixed" can cause additional weird logic problems in complex forms.  So, https://github.com/medic/cht-core/issues/7674 has been logged to fix the fix.

But, I believe we should be able to close out this issue with https://github.com/medic/cht-core/pull/7256 since it will essentially be addressed.

**Comment by jkuester** [comment] 2022-07-25 20:38
@medic/quality-assurance This is going to be "fixed" by the Enketo uplift https://github.com/medic/cht-core/pull/7256, so it should be ready for AT.

**Comment by jkuester** [comment] 2022-08-11 21:46
@tatilepizs here is a sample form to use for testing the issue:

```.xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms">
  <h:head>
    <h:title>Enketo Widgets</h:title>
    <model>
      <itext>
        <translation lang="en">
          <text id="/enketo_widgets/select_widgets/question_to_check/dk:label">
            <value>Don't Know</value>
          </text>
          <text id="/enketo_widgets/select_widgets/question_to_check/na:label">
            <value>Not Applicable</value>
          </text>
          <text id="/enketo_widgets/select_widgets/question_to_check/no:label">
            <value>No</value>
          </text>
          <text id="/enketo_widgets/select_widgets/question_to_check/yes:label">
            <value>Yes</value>
          </text>
          <text id="/enketo_widgets/select_widgets/question_to_check:label">
            <value>Select an answer!</value>
          </text>
          <text id="/enketo_widgets/select_widgets/trigger/dk:label">
            <value>Don't Know</value>
          </text>
          <text id="/enketo_widgets/select_widgets/trigger/na:label">
            <value>Not Applicable</value>
          </text>
          <text id="/enketo_widgets/select_widgets/trigger/no:label">
            <value>No</value>
          </text>
          <text id="/enketo_widgets/select_widgets/trigger/yes:label">
            <value>Yes</value>
          </text>
          <text id="/enketo_widgets/select_widgets/trigger:label">
            <value>Should the previous question be relevant?</value>
          </text>
          <text id="/enketo_widgets/select_widgets:label">
            <value>Select widgets</value>
          </text>
        </translation>
      </itext>
      <instance>
        <enketo_widgets id="enketo_widgets" prefix="J1!enketo_widgets!" delimiter="#" version="2022-08-11 00:00:00">
          <select_widgets>
            <question_to_check/>
            <trigger>yes</trigger>
          </select_widgets>
          <meta tag="hidden">
            <instanceID/>
          </meta>
        </enketo_widgets>
      </instance>
      <instance id="contact-summary"/>
      <bind nodeset="/enketo_widgets/select_widgets/question_to_check" type="select1" relevant=" /enketo_widgets/select_widgets/trigger  = 'yes'"/>
      <bind nodeset="/enketo_widgets/select_widgets/trigger" type="select1"/>
      <bind nodeset="/enketo_widgets/meta/instanceID" type="string" readonly="true()" calculate="concat('uuid:', uuid())"/>
    </model>
  </h:head>
  <h:body class="pages">
    <group appearance="field-list" ref="/enketo_widgets/select_widgets">
      <label ref="jr:itext('/enketo_widgets/select_widgets:label')"/>
      <select1 ref="/enketo_widgets/select_widgets/question_to_check">
        <label ref="jr:itext('/enketo_widgets/select_widgets/question_to_check:label')"/>
        <item>
          <label ref="jr:itext('/enketo_widgets/select_widgets/question_to_check/yes:label')"/>
          <value>yes</value>
        </item>
        <item>
          <label ref="jr:itext('/enketo_widgets/select_widgets/question_to_check/no:label')"/>
          <value>no</value>
        </item>
        <item>
          <label ref="jr:itext('/enketo_widgets/select_widgets/question_to_check/dk:label')"/>
          <value>dk</value>
        </item>
        <item>
          <label ref="jr:itext('/enketo_widgets/select_widgets/question_to_check/na:label')"/>
          <value>na</value>
        </item>
      </select1>
      <select1 ref="/enketo_widgets/select_widgets/trigger">
        <label ref="jr:itext('/enketo_widgets/select_widgets/trigger:label')"/>
        <item>
          <label ref="jr:itext('/enketo_widgets/select_widgets/trigger/yes:label')"/>
          <value>yes</value>
        </item>
        <item>
          <label ref="jr:itext('/enketo_widgets/select_widgets/trigger/no:label')"/>
          <value>no</value>
        </item>
        <item>
          <label ref="jr:itext('/enketo_widgets/select_widgets/trigger/dk:label')"/>
          <value>dk</value>
        </item>
        <item>
          <label ref="jr:itext('/enketo_widgets/select_widgets/trigger/na:label')"/>
          <value>na</value>
        </item>
      </select1>
    </group>
  </h:body>
</h:html>
```

Basically just need to pay attention to what happens to the value for the first question (`question_to_check`).

**Comment by tatilepizs** [comment] 2022-08-11 22:41
**Config:** Default
**Environment:** Local with docker helper script
**Platform:** WebApp
**Browser:** Chrome

---

The file used to test was provided by @jkuester in [this comment](https://github.com/medic/cht-core/issues/4132#issuecomment-1212528444) 

### Reproducible on `Master`
When the question `question_to_check` was answered and becomes irrelevant, and then later becomes relevant again, **it loses its data.**

<details>
<summary>Test video</summary>

[video](https://user-images.githubusercontent.com/94494491/184253596-64ebc0c1-c710-4577-b2ea-069975bfe0c9.mov)

</details>

### Fixed on `6345-enketo-uplift`
When the question `question_to_check` was answered and becomes irrelevant, and then later becomes relevant again, it keeps its previous data.

<details>
<summary>Test video</summary>

[video](https://user-images.githubusercontent.com/94494491/184254312-bc7e53b3-0588-404d-88bb-ca09059e6397.mov)

</details>

**Closed** 2022-08-16 19:02 UTC
Labels: Type: Bug, Enketo, Priority: 3 - Low
